### ISSUE TITLE
Rspec under rails 4.1.8 doesn't apply rollback transaction to secondary database

### ISSUE THREAD

**Issue by jeremywadsack** [rails/rails#17776]
Our app has two databases, the second of which is shared with another app. My `database.yml` looks like this for the test environments:

```
test:
  adapter: postgresql
  database: my-app-test
  host: localhost
  encoding: utf8
  min_messages: WARNING

shared_test:
  adapter: postgresql
  database: shared-test
  host: localhost
  encoding: utf8
  min_messages: WARNING
```

Models that use the shared database inherit from this:

```
class ServiceModel < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :"shared_#{Rails.env}"

  def readonly?
    true if persisted?
  end

  def delete
    raise ActiveRecord::ReadOnlyRecord
  end

  def destroy
    raise ActiveRecord::ReadOnlyRecord
  end
end
```

We run rspec with transactional fixtures but the rspec team states that this is [a wrapper around Rails configuration](https://github.com/rspec/rspec-rails/issues/1235#issuecomment-64489255):

```
  config.use_transactional_fixtures = true
```

When I run `rspec` under rails 3.2.19, everything runs fine and I can run the tests over and over and they continue to pass.

When I run `rspec` under rails 4.1.8, they pass the first time, but running them again raises lots of `PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint` errors because the shared test database was not cleared out.

I have inspected the logs from postgresql for both branches and have made [gists](https://gist.github.com/jeremywadsack/8f3e95f4e26194686d7e) available that show that ROLLBACK is being called for the shared database under rails 3 but not under rails 4. Specifically, [line 235 in the rails_3.2.19](https://gist.github.com/jeremywadsack/8f3e95f4e26194686d7e#file-rails_3-2-19-L235) it calls ROLLBACK on the shared database (there's a corresponding BEGIN at line 98). This is missing in the rails 4.1.8 version.
