### ISSUE TITLE
Fixtures behaving flakily

### ISSUE THREAD

**Issue by Joshua-Anderson** [rails/rails#18357]
I'm having a really weird issue with fixtures in my rails project.

I've tested my project on two fresh, idencial vagrant machines on separate computers and travis-ci.

On one of the vagrant machines, this test passes.

``` ruby
  test 'Why is this test failing?' do
    assert_equal 25, questions(:question_old_6).catagories.length
    assert_equal 6, catagories(:catagory_old_11).questions.length
  end
```

The questions and categories models are bound together with a has and belongs to many relation.

On the other vagrant machine and travis-ci, the test fails with:

``` ruby
 1) Failure:
CatagoriesControllerTest#test_Why_is_this_test_failing? [/home/travis/build/memorizor/memorizor-api/test/controllers/catagories_controller_test.rb:9]:
Expected: 25
  Actual: 0
```

The vagrant machines are both freshly booted with only difference between them being that one was started on a different computer.

I've tried to get the same test to fail on fresh rails projects but haven't been able to reproduce the failures. I've tried to cut down on this code dump as much as possible, but it will still be a little long since this is from my small rails project. It's open source on github at [memorizor/memorizor-api](https://github.com/memorizor/memorizor-api), so you should be able to use this as a large-ish :cry:  reproduction project.

I'm using ruby 2.2.0 and rails 4.2.0.

### The Models

``` ruby
class Catagory < ActiveRecord::Base
  validates :name, presence: true
  validates :color, presence: true, format: { with: /\A[a-f0-9]{6}\z/ }

  belongs_to :user
  has_and_belongs_to_many :questions

  def add_questions(question_ids, user)
    question_ids.each do |question_id|
      @question = Question.find_by_id(question_id)
      questions << @question if @question.user == user
    end
  end
end


class Question < ActiveRecord::Base
  validates :content, presence: true
  validates :review_at, presence: true
  validates :answer_type, presence: true, inclusion: { in: [0] }

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_and_belongs_to_many :catagories
end
```

### The Database Schema:

``` ruby
ActiveRecord::Schema.define(version: 20141214183400) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "answers", force: true do |t|
    t.text    "content",     null: false
    t.integer "question_id", null: false
  end

  add_index "answers", ["question_id"], name: "index_answers_on_question_id", using: :btree

  create_table "catagories", force: true do |t|
    t.string  "name",    null: false
    t.string  "color",   null: false
    t.integer "user_id", null: false
  end

  add_index "catagories", ["user_id"], name: "index_catagories_on_user_id", using: :btree

  create_table "catagories_questions", id: false, force: true do |t|
    t.integer "catagory_id", null: false
    t.integer "question_id", null: false
  end

  create_table "questions", force: true do |t|
    t.text     "content",     null: false
    t.datetime "review_at",   null: false
    t.integer  "answer_type", null: false
    t.integer  "user_id",     null: false
  end

  add_index "questions", ["user_id"], name: "index_questions_on_user_id", using: :btree

  create_table "users", force: true do |t|
    t.string  "name",                            null: false
    t.string  "email",                           null: false
    t.string  "password_digest"
    t.boolean "verified",        default: false
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["name"], name: "index_users_on_name", unique: true, using: :btree

end
```

### Part of the question fixture

``` yml
<% 50.times do |n| %>
question_old_<%= n %>:
  user: super_active_user
  content: '<%= n %>'
  answer_type: 0
  review_at: '2000-01-01 01:00:00 +0000'
<% end %>

<% 50.times do |n| %>
question_new_<%= n %>:
  user: super_active_user
  content: '<%= n %>'
  answer_type: 0
  review_at: '2200-01-01 01:00:00 +0000'
<% end %>
```

### Part of the catagory fixture

``` yml
<% 25.times do |n| %>
catagory_old_<%= n %>:
  user: super_active_user
  questions:
    - question_old_1
    - question_old_2
    - question_old_3
    - question_old_4
    - question_old_5
    - question_old_6
  name: '<%= n %>'
  color: 'ffffff'
<% end %>

<% 25.times do |n| %>
catagory_new_<%= n %>:
  user: super_active_user
  questions:
    - question_new_1
    - question_new_2
    - question_new_3
    - question_new_4
    - question_new_5
    - question_new_6
  name: '<%= n %>'
  color: '000000'
<% end %>
```

### The flakey test

``` ruby
  test 'Why is this test failing?' do
    assert_equal 25, questions(:question_old_6).catagories.length
    assert_equal 6, catagories(:catagory_old_11).questions.length
  end
```

This bug has me had me stumped for weeks. If you need more of the code to solve my issue it's all open source on github at [memorizor/memorizor-api](https://github.com/memorizor/memorizor-api).  If you need any more data or any help with any part of this I am super happy to help. Thank you so much, you guys have done a awesome job with rails! :heart:
