### ISSUE TITLE
Issue with rake db:create/setup connecting to rails config/database.yml

### ISSUE THREAD

**Issue by zargold** [rails/rails#21009]
See: http://stackoverflow.com/questions/31595245/rake-dbsetup-or-rake-dbcreate-applying-wrong-username-wrong-database for full details.

I am not sure whether this is my issue or a rake/rails integration issue, but when I do 
`rake db:create` or `rake db:setup` I expect that it would create the db which is listed in the database.yml configuration file.

It does create that db in my postgres for the correct user/password for the test database but not for the development database... 

```yml
default: &default
  adapter: postgresql
  encoding: unicode
  username: project
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: Project_development

test:
  <<: *default
  database: Project_test
```
```bash
$ rake db:setup
=> user already exists
$ rake db:create
=> user already exists
=> Project_test already exists
```
Please help?
