### ISSUE TITLE
structure.sql not working with multiple schema_search_paths defined

### ISSUE THREAD

**Issue by johnhamelink** [rails/rails#23141]
Hi there,

After upgrading postgres from 9.4 to 9.5, and then upgrading rails from 9.4.2 to 9.4.5 (to fix #21931), I'm finding that running `db:migrate` is resulting in an error when multiple `schema_search_path`s are set in `database.yml`. Interestingly, the pg_dump command it provides seems to work - it does create a `structure.sql` file and it returns `0`.

### Example with multiple search paths set:

```yml
default: &default                                                                                                                                                                              
  adapter: postgis                                                                                                                                                                             
  schema_search_path: public,postgis,topology                                                                                                                                                  
  #schema_search_path: public                                                                                                                                                                  
  encoding: unicode                                                                                                                                                                            
  pool: 5                                                                                                                                                                                      
  username:                                                                                                                                                                                    
  password:
```

```
$ be rake db:drop db:create db:migrate

< snip >

-- add_index(:sms_verifications, :phone_number_id, {:name=>"sms_phone_number_id_idx"})
   -> 0.0250s
== 20160120133702 SmsVerifications: migrated (0.0836s) ========================

pg_dump: No matching schemas were found
rake aborted!
failed to execute:
pg_dump -s -x -O -f /home/john/Public/fap/api_2.0/src/db/structure.sql --schema=public --schema=postgis --schema=topology fap_development

Please check the output above for any errors and make sure that `pg_dump` is installed in your PATH and has proper permissions.


Tasks: TOP => db:structure:dump
(See full trace by running task with --trace)
```

### Example with more standard behaviour:

```yml
default: &default                                                                                                                                                                              
  adapter: postgis                                                                                                                                                                             
  #schema_search_path: public,postgis,topology                                                                                                                                                 
  schema_search_path: public                                                                                                                                                                   
  encoding: unicode                                                                                                                                                                            
  pool: 5                                                                                                                                                                                      
  username:                                                                                                                                                                                    
  password: 
```

```
$ be rake db:drop db:create db:migrate

< snip >

== 20160120133702 SmsVerifications: migrating =================================
-- create_table(:sms_verifications)
   -> 0.0579s
-- add_index(:sms_verifications, :phone_number_id, {:name=>"sms_phone_number_id_idx"})
   -> 0.0251s
== 20160120133702 SmsVerifications: migrated (0.0831s) ========================

Loading application environment...
Loading code in search of Active Record models...
ActiveJob::QueueAdapters::InlineAdapter does not support delayed retries, so does not work with ActiveJob::Retry. You may experience strange behaviour.
Generating Entity-Relationship Diagram for 42 models...
Done! Saved diagram to erd.pdf.
```
