### ISSUE TITLE
PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint

### ISSUE THREAD

**Issue by ryush00** [rails/rails#24219]
### Steps to reproduce
There is no way to reproduce this problem.

I start the server. It works great during only a few hours. After a few hours, It show me the error.

### Expected behavior
Insert record without error.

### Actual behavior
https://gist.github.com/ryush00/322cd74b3d8ed07d99ba

### System configuration
**Rails version**: 4.2.5.2

**Ruby version**: 2.2.4

**db.yml**

```
production:
  <<: *default
  database: minelist_production
  pool: 5
  host: <%= ENV["POSTGRESQL_HOST"] %>
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
```

**deploy/production.rb**

```
set :puma_threads, [16, 16]
set :puma_workers, 2
set :puma_worker_timeout, nil
set :puma_init_active_record, true
set :puma_preload_app, false
set :nginx_use_ssl, false
```
