### ISSUE TITLE
No file information is provided for fixtures ERB

### ISSUE THREAD

**Issue by denofevil** [rails/rails#24355]
### Steps to reproduce

1. Try to set a breakpoint in a test fixture ERB injection e.g on line 3 in the following file
```yaml
<% env = ENV['RAILS_ENV']%>
one:
  title: <%= env %>

two:
  title: MyString
```
2. Debug tests

### Expected behaviour
Debugger should stop at the breakpoint in fixture file

### Actual behaviour
Debugger does not stop at the breakpoint, because file information is not passed into ERB

### System configuration
**Rails version**:
Any
**Ruby version**:
Any

Corresponding issue in [RubyMine bugtracker](https://youtrack.jetbrains.com/issue/RUBY-17359)
