### ISSUE TITLE
Regression on 5.0.0.beta4 with JSONB fixtures

### ISSUE THREAD

**Issue by lucasmazza** [rails/rails#24872]
While upgrading from beta3 to beta4 I found a possible regression on how data for `JSONB` columns is loaded from fixtures:

```yml
jsob_as_string:
  # The raw String syntax is properly inserted on beta3,
  # but it fails on beta4.
  props: '{ "key": "value"}'

jsob_as_hash:
  # Using a nested YAML Hash works on both beta3 and beta4.
  props:
    key: 'value'
```

On beta4 / master the first fixture `props` attribute is inserted/accessed as a `String` instead of a `Hash`, while the second fixture works as expected on both versions. Using a `json` column seems to have the same type mismatch.

I'm not sure if there is a blessed way to deal with JSON/JSONB data inside fixture files, if we plan to support only the YAML format it might be worth to mention it on the `FixtureSet` docs or on the Testing guide.

There is a repository with a reproduction script and sample fixture at https://github.com/lucasmazza/jsonb_test.
