### ISSUE TITLE
Cannot run tests if I have db name different from model name.

### ISSUE THREAD

**Issue by uk4d** [rails/rails#26057]
Migration file:
```
class LocalEvent < ActiveRecord::Migration
  def up
    create_table "dbo.local_classes", :id => false do |t|
      t.string  :event_id
      t.string  :name
      t.date    :start_date
      t.date    :end_date
      t.string  :format      
      t.timestamps
    end
  end
   def down
     drop_table "dbo.local_classes"
   end
end
```

My fixtures:

/test/fixtures/local_events.yml

```
math101:
  event_id: "loc-12"
  name: "Math 101"
  start_date: "2015-10-05 00:00:00"
  end_date: "2015-10-05 00:00:00"
  format: "on site"
```

When I try to do run a simple controller test it complains me about:

LocalEventsControllerTest#test_should_get_home:
ActiveRecord::StatementInvalid: Could not find table 'local_events'

I have seen in Fixtures API that you can tell the fixtures what model to use by `model_class:` but there isn't a way to specify what table it should use. I am not sure why though in the migration I am specifying the table name explicitly the test is trying to look for table name which doesn't exist

#### System Config:

- Rails 3.2
- DB: MSSQL

Any guidance please?
