### ISSUE TITLE
Rails 5 schema.rb adding non-agnostic options.  dev mysql -> test sqlite

### ISSUE THREAD

**Issue by duffyjp** [rails/rails#26209]
### Steps to reproduce

Use MySQL for Development, and SQLite3 for Test.  On an app I'm upgrading from 4.2 to 5.0 I run into trouble **after** running a migration in the Rails5 branch. Here's why:

Rails 4:

``` bash
ack "create_table" db/schema.rb 
  create_table "absences", force: :cascade do |t|
  create_table "accounts", force: :cascade do |t|
  create_table "addresses", force: :cascade do |t|
  ...
```

Rails 5:

``` bash
ack "create_table" db/schema.rb 
  create_table "absences", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci" do |t|
  create_table "accounts", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci" do |t|
  create_table "addresses", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci" do |t|
  ...
```

That's fine for MySQL, but when I load the schema for tests I get this:

```
Tasks: TOP => db:test:load_schema
(See full trace by running task with --trace)
ActiveRecord::StatementInvalid: SQLite3::SQLException: near "ENGINE": syntax error: CREATE TABLE "absences" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "person_id" integer, "date" date, "source" varchar, "appointment_id" varchar, "reason" varchar, "category" varchar, "hours" decimal(4,2), "approved" boolean, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "entry_source" varchar, "voided" boolean DEFAULT 'f' NOT NULL, "mark_for_deletion" boolean DEFAULT 'f') ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
### Expected behavior

Migration ignores options it's can't use, or they're not in the schema.rb in the first place.
### Actual behavior

sqlite3 (1.3.11) builds invalid SQL (per sqlite3).
### System configuration

Working: 4.2.5.1
Broken: 5.0.0.1

**Ruby version**:
2.3.1p112

**Comment by vipulnsward** [comment]
Can you share your database config wrt extra options?

**Comment by duffyjp** [comment]
It's pretty stock.  Mysql for the local DB, and sqlite3 for test.  

```
development:
  adapter: mysql2
  encoding: utf8
  database: xxxx
  pool: 32
  username: xxxx
  password: xxxx
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  timeout: 5000
```

**Comment by duffyjp** [comment]
I setup a blank Rails 5.0.0.1 app, added mysql2, and set development to mysql and test/prod to sqlite3.  

Add a migration:
```ruby
rails g migration create_foos bar
```


### Observations of schema.rb


rake db:setup
```ruby
ActiveRecord::Schema.define(version: 20160822152937) do

  create_table "foos", force: :cascade do |t|
    t.string "bar"
  end

end

```

rake db:migrate
```ruby
ActiveRecord::Schema.define(version: 20160822152937) do

  create_table "foos", force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8" do |t|
    t.string "bar"
  end

end

```




database.yml
```
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: issue26209
  username: root
  password: your_pass_here
  host: 127.0.0.1

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
```
