### ISSUE TITLE
Associations with scope should assign scope conditions first

### ISSUE THREAD

**Issue by heaven** [rails/rails#26295]
We have the next set up:

``` ruby
class Video < ApplicationRecord
  has_many :posters,     -> { where(:kind => 0) },
    :as => :assetable, :class_name => "AssetImage", :dependent => :destroy
  has_many :thumbnails,  -> { where(:kind => 1) },
  # ...
end

class AssetImage < Asset
  CONFIG = Rails.application.config_for(:paperclip).symbolize_keys_recursively

  has_attached_file :data,
    CONFIG[:images].merge(:styles => lambda { |asset| asset.instance.image_styles })

  belongs_to :assetable, :polymorphic => true, :touch => true

  def image_styles
    # Here we need the kind and assetable attributes to get proper styles from CONFIG
    # E.g. CONFIG[:styles][assetable_type][kind] => styles for Video#thumbnails
  end
end
```

In our paperclip.yml we have styles defined as follows (just to give you an idea):

``` yaml
styles: &paperclip_image_styles
  defaults:
    thumb:  '100x100#'
  video:
    0: # Posters
      thumb:  '120x171'
      medium: '240x342'
      large:  '400x570'
      xlarge: '600x855'
    1: # Thumbnails
      thumb:  '208x117'
      medium: '304x171'
      large:  '448x252'
      xlarge: '608x342'
    # ...
```

The problem is that every time we do:

``` ruby
video.thumbnails.build(:rating => image.image_rating.to_i, :data => URI(url))
```

Inside `AssetImage#image_styles` both `kind` and `assetable` are always `nil`.

Actual results:
- Rails assigns the `data` attribute
- Paperclip then tries to download image and read the styles
- the `kind` and `assetable` are both `nil` at this point
- Rails assigns the `assetable` attribute (the inverse association, a `video` in this case)
- Rails assigns the `kind` attribute from the association scope

So the order isn't correct and isn't under our control.

Expected results:
- Rails should first assign the inverse association
- Rails should then assign attributes from the association scope (if given)
- Only after that the record could be treated as a properly initialized and the attributes we passed to `video.thumbnails.build()` should be assigned

There's a workaround:

``` ruby
video.thumbnails.build(
  :rating => image.image_rating.to_i,
  :data => URI(url),
  :assetable => video,
  :kind => 1
)
```

But:
- At first I don't think this is an acceptable way as we have to maintain association data in a second place
- This wouldn't work with the `kind` attribute because Rails will assign `assetable`, `data`, and only then `kind`

So a complete workaround would be what we're actually doing:

``` ruby
asset = video.try(type).build(:assetable => video, :rating => image.image_rating.to_i)
asset.data = URI(url)
```

But this doesn't work in the case of `accepts_nested_attributes_for :thumbnails`, where we can't control the order in any non-hackish way (AFAIK).
