### ISSUE TITLE
Model plurality inconsistent when defining custom human readable names and errors in locale files

### ISSUE THREAD

**Issue by johnwhelchel** [rails/rails#26544]
### Steps to reproduce

Create model `choice_question_option` with field called `text`. We want to customize the human readable name and error message when `:taken` validation (uniqueness) fails. Setup a simple validation for uniqueness on text. Try to add a new model with the same text as an old model. Examine error messages produced on the errors field. 
### Expected behavior

Overriding text in a YAML should only require the singular table name in both cases.

According to both [Rails](http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models) docs, singular model names should be used (this is also mirrored in comments in the ActiveRecord code). That would mean a yaml file like:

```
en:
  activerecord:
    attributes:
      choice_question_option:
        text: "Super question"
    errors:
      models:
        choice_question_option:
          attributes:
            text:
              taken: "is already used by another question."
```
### Actual behavior

However, this does not work. The plurality is inconsistent. I found only the following function as expected:

```
en:
  activerecord:
    attributes:
      choice_question_options: # note plural model name here
        text: "Super question"
    errors:
      models:
        choice_question_option:
          attributes:
            text:
              taken: "is already used by another question."
```
### System configuration

**Rails version**:
5.0.0.1
**Ruby version**:
2.3.1p112
