### ISSUE TITLE
rails console wont work with remote postgresql database

### ISSUE THREAD

**Issue by psantos10** [rails/rails#27120]
### Steps to reproduce

(Guidelines for creating a bug report are [available
here](http://guides.rubyonrails.org/contributing_to_ruby_on_rails.html#creating-a-bug-report))

### Expected behavior
My rails application are on vagrant box and the postgresql db on the Windows machine. 

my database.yml file:

```
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host: 10.0.2.2
  username: postgres
  password: root
  port: 5432

development:
  <<: *default
  database: api_demo_development
```

I created a demo API application using the command `rails new api_demo --api -d postgresql`.
The aplication is working fine, I can create a database with the command `rails db:create`, and run migrations with `rails db:migrate`

run : `rails console`, expect to run the console without any error.

### Actual behavior

but when I try to run the console ( `rails console`), I am getting this error:

> /home/ubuntu/.rvm/gems/ruby-2.3.2@demos/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize': could not connect to server: No such file or directory
>         Is the server running locally and accepting
>         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
>  (PG::ConnectionBad)

### System configuration
**Rails version**: 5.0.0.1

**Ruby version**: 2.3.2p217

**Comment by utilum** [comment]
Don't you need to set `host` for a remote connection?

**Comment by psantos10** [comment]
@utilum  I set the host on the `database.yml`` file:

```
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host: 10.0.2.2
  username: postgres
  password: root
  port: 5432

development:
  <<: *default
  database: api_demo_development
  
production:
  <<: *default
  database: api_demo_production
  username: api_demo
  password: <%= ENV['API_DEMO_DATABASE_PASSWORD'] %>
```
