### ISSUE TITLE
"FATAL:  Peer authentication failed for a database user" when creating a test database ONLY

### ISSUE THREAD

**Issue by ahmed-taj** [rails/rails#27398]
Hello,

I've got a credential error when trying to create & drop development and testing databases. The error says:

```bash
ghost@Ghost-PC:/work/Projects/myproject$ rails db:create 
Created database 'myproject_development'
FATAL:  Peer authentication failed for user "myuser"
...
```

Well, hold a second, this isn't a mistake in credentials, I have tested them many times, but later I noticed, the command behaves in unexpected way. as you might noticed this line:

    Created database 'myproject_development'

It says, the development database has been created! and it was, I checked it out in pgadmin. But, then how it possibly fail in creating a second database using the same credentials !!

If we took step further and try `db:drop` the output would be:

```bash
ghost@Ghost-PC:/work/Projects/myproject$ rails db:drop
Dropped database 'myproject_development'
FATAL:  Peer authentication failed for user "myuser"
Couldn't drop database 'myproject_test'
rails aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "myuser"
/media/ghost/Dev/Projects/myproject/bin/rails:9:in `require'
/media/ghost/Dev/Projects/myproject/bin/rails:9:in `<top (required)>'
/media/ghost/Dev/Projects/myproject/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
```

### Steps to reproduce

I have created a new project using the following command:

```
$ rails new --skip-test --skip-action-mailer --skip-action-cable --api -d postgresql myproject
```
Then modified the `database.yml` to look like this:

```yaml
# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  username: 'myuser'

  # The password associated with the postgres role (username).
  password: '*****'
  
  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  # host: 

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  # port:

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

development:
  <<: *default
  database: myproject_development


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: myproject_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  url: <%= ENV['DATABASE_URL'] %>
```

Then I ran:

```bash
$ rails db:create
```

### Expected behavior

```bash
$ rails db:create
Created database 'myproject_development'
Created database 'myproject_test'
...
```

### Actual behavior

```bash
ghost@Ghost-PC:/work/Projects/myproject$ rails db:create 
Created database 'myproject_development'
FATAL:  Peer authentication failed for user "myuser"
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "username"=>"myuser", "password"=>"*****", "pool"=>5, "database"=>"myproject_test"} 
rails aborted!
PG::ConnectionBad: FATAL:  Peer authentication failed for user "myuser"
/media/ghost/Dev/Projects/myproject/bin/rails:9:in `require'
/media/ghost/Dev/Projects/myproject/bin/rails:9:in `<top (required)>'
/media/ghost/Dev/Projects/myproject/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

### System configuration
**Rails version**:

`Rails 5.0.0.1`

**Ruby version**:

`ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`
