### ISSUE TITLE
Feature request: make i18n infer translated name of association attributes

### ISSUE THREAD

**Issue by Drenmi** [rails/rails#28820]
When working with translations, I am adding locale files for the application's models, including the name of the model, like so:

```yaml
sv:
  activerecord:
    models:
      author: "Författare"
```

### Desired behavior

It would be nice if Rails could use this to infer the name of association attributes of other models:

```ruby
class Book < ApplicationRecord
  belongs_to :author
end

Book.human_attribute_name(:author)
# => "Författare"
```

### Current behavior

In order to make this work right now, I need to add the name of the attribute to all related locale files:

```yaml
sv:
  activerecord:
    attributes:
      book:
        author: "Författare"
```

leading to this translation being duplicated in a lot of different places.

### System configuration
**Rails version**:

> Rails 5.1.0.rc1

**Ruby version**:

> ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
