### ISSUE TITLE
Rails 5.1.0 I18n not support write independent part in seperate files.

### ISSUE THREAD

**Issue by zw963** [rails/rails#28980]
Before update 5.1 from 5.0.2, I exists followings i18n settings:

```yml
# config/locales/api/v1/en.yml

en:
  api:
    v1:
      json_msg:
        '交易成功': 'success'
```

```yml
# config/locales/api/v1/zh-CN.yml

zh-CN:
  api:
    v1:
     json_msg:
       '交易成功': '交易成功'
```

I use above I18n in my controllers directly

```rb
#  app/controllers/api/v1/some_controller

def index
  render json: {code: '1111', msg: I18n.t('api.v1.json_msg.交易成功')}
end
```

my project is consist of many part(serve for several site),  and exist
so many independent I18n file like this, it worked very well in Rails 5.0.2.

```sh
├── locales
│   ├── xxx_www
│   ├── xxx_m
│   ├── xxx_api
│   ├── models
│   ├── kaminari
│   ├── framework7
│   ├── area_group_name
│   ├── app
│   └── api
│       └── v1
```

But, when update 5.1, we always get followings error messages in my 
controller test:

```rb
--- expected
+++ actual
@@ -1 +1 @@
-"交易成功"
+"translation missing: en.api.v1.json_msg.交易成功"
```

Seem like Rails 5.1 not load all I18n files in my test, I have no test
this in my production, but i think it should not worked too.
