### ISSUE TITLE
[Rails 5.1.1] I18n.stub :locale not worked in Integretion test

### ISSUE THREAD

**Issue by zw963** [rails/rails#29192]
Following is files:

```yml
# app/config/locales/en.yml

en:
  api:
    提示:
      一小时最多发送5次: 'Send 1 hour up to 5 times'
```

```yml
# app/config/locales/zh-CN.yml
zh-CN:
  api:
    提示:
      一小时最多发送5次: '一小时最多发送 5 次'
```

```rb
# controller

return render json: {code: '0002', msg: I18n.t('api.提示.一小时最多发送5次')}
```

In intergration test, I have following code:

```rb
# controller_test

  I18n.stub :locale, 'en' do
      assert_equal('Send 1 hour up to 5 times', content.msg)
  end
  I18n.stub :locale, 'zh-CN' do
      assert_equal('一小时最多发送 5 次', content.msg)
  end
```

The second test is failed.
