### ISSUE TITLE
`number_to_human_size` doesn't distinguish between singular and plural

### ISSUE THREAD

**Issue by pinewong** [rails/rails#30981]
### Steps to reproduce
```ruby
1.to_s(:human_size)             # => "1 Bytes"
helper.number_to_human_size(1)  # => "1 Bytes"
```

### Expected behavior & Actual behavior
Is it should get `"1 Byte"` here?

### System configuration
**Rails version**: 5.1.1

**Ruby version**: 2.3.1

**Comment by danielsousaio** [comment]
If this helps, here's my output:

```zsh
app % ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

app % rails c
Running via Spring preloader in process 10314
Loading development environment (Rails 5.1.1)
2.3.1 :001 > 1.to_s(:human_size)
 => "1 Byte" 
2.3.1 :002 > helper.number_to_human_size(1)
 => "1 Byte" 
2.3.1 :003 > 
```

Did you override those locales keys in your application?

```yml
en:
  number:
    human:
      storage_units:
        byte:
          one: "Byte"
          other: "Bytes"
```
