### ISSUE TITLE
Dynamic database parameters for AWS IAM database authentication

### ISSUE THREAD

**Issue by atyndall** [rails/rails#31211]
I am looking to use [IAM database authentication](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html) with Rails, as it allows a convenient way for AWS users to manage permissions and avoid storing database passwords in their codebases.

At a high level, it works by generating a password to connect to the database that is valid for only 15 minutes. If you want to connect again after the 15 minutes, you would need to generate a new password. 

This password can be generating using the AWS Ruby SDK easily, and thus can theoretically be embedded in `config/database.yml` like so;

```yaml
production:
  adapter: mysql2
  host: db_host
  database: db
  username: db_user
  password: <%=
              Aws::RDS::AuthTokenGenerator
                .new(credentials: Aws::InstanceProfileCredentials.new)
                .auth_token(
                  region: 'us-east-1',
                  endpoint: 'db_host:3306',
                  user_name: 'db_user'
                )
            %>
```

However, as far as I can tell, `config/database.yml` is evaluated once on startup, and remains cached in that state for Rails' lifetime.

Therefore, by using this approach, the Rails server would initially successfully connect to the database, but if at any point after the first 15 minute window Rails tried to open a new DB connection or reconnect a dropped connection, the expired cached credentials would be rejected.

Is there a sanctioned way to have database configuration that is re-evaluated on each connection establishment?

If not, this would be a useful feature to add.
