### ISSUE TITLE
Rails can't find fonts when assets are added with Yarn

### ISSUE THREAD

**Issue by luizkowalski** [rails/rails#31266]
I just added bootstrap to Rails using yarn
`yarn add bootstrap` 

```
bootstrap@^3.3.7:
  version "3.3.7"
  resolved "https://registry.yarnpkg.com/bootstrap/-/bootstrap-3.3.7.tgz#5a389394549f23330875a3b150656574f8a9eb71"
```

Locally works perfectly, but when deploying to Heroku, I can't see the assets

```
2017-11-28T20:14:52.861989+00:00 app[web.1]: I, [2017-11-28T20:14:52.861874 #4]  INFO -- : [6b764e01-ce48-46cb-977a-ccadd6eeb057] Started GET "/fonts/glyphicons-halflings-regular.ttf" for 95.91.247.235 at 2017-11-28 20:14:52 +0000
2017-11-28T20:14:52.862716+00:00 app[web.1]: F, [2017-11-28T20:14:52.862655 #4] FATAL -- : [6b764e01-ce48-46cb-977a-ccadd6eeb057]
2017-11-28T20:14:52.862778+00:00 app[web.1]: F, [2017-11-28T20:14:52.862721 #4] FATAL -- : [6b764e01-ce48-46cb-977a-ccadd6eeb057] ActionController::RoutingError (No route matches [GET] "/fonts/glyphicons-halflings-regular.ttf"):
```

I tried manually copy the `fonts` folder from bootstrap, tried add this:

```
Rails.application.config.assets.paths << Rails.root.join('node_modules/bootstrap/dist/fonts')
Rails.application.config.assets.paths << Rails.root.join('app', 'assets', 'fonts')
Rails.application.config.assets.precompile << %r{node_modules/bootstrap/dist/fonts/[\w-]+\.(?:eot|svg|ttf|woff2?)$}
Rails.application.config.assets.precompile << /\.(?:svg|eot|woff|ttf)\z/
```

nothing works, Rails doesn't see it

I'm using Rails 5.1.4 with MacOS High Sierra

**Comment by guilleiguaran** [comment]
I had exactly this problem today at work and was able to fix it in this way:

You can use `bootstrap-sass` instead and include this SCSS file to override fonts location using `sass-rails'` `asset-url` helper (that takes care of adding the files as dependencies during compile):

```scss
$bs-font-path: "bootstrap-sass/assets/fonts/bootstrap";

@font-face {
  font-family: 'Glyphicons Halflings';
  src: asset-url('#{$bs-font-path}/glyphicons-halflings-regular.eot');
  src: asset-url('#{$bs-font-path}/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
  asset-url('#{$bs-font-path}/glyphicons-halflings-regular.woff2') format('woff2'),
  asset-url('#{$bs-font-path}/glyphicons-halflings-regular.woff') format('woff'),
  asset-url('#{$bs-font-path}/glyphicons-halflings-regular.ttf') format('truetype'),
  asset-url('#{$bs-font-path}/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
