### ISSUE TITLE
5.2.0 RC1 Configure ActiveStorage for Disk Storage with DirectUpload

### ISSUE THREAD

**Issue by tomrossi7** [rails/rails#31842]
I upgraded our application from `5.2.0.beta2` to `5.2.0.rc1` and can't get the local/disk storage to work with our direct upload configuration.

```
local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
  host: http://myapp.test
```

My tests fail and I suspect it is related to the `host` running in development mode. With beta2, I was able to leave the host out of the configuration and the tests passed.

**How should our test environment be configured if we want to test direct upload?**
