### ISSUE TITLE
Direct uploads using ActiveStorage local option don't seem to work

### ISSUE THREAD

**Issue by kstratis** [rails/rails#32187]
tl;dr version:

I'm probably missing something here, but in my setup using ActiveStorage's **local** option with `direct_upload` option set to `true`:

```erb
<div class="form-group">
  <%= property.label :images %>
  <%= property.file_field :images, multiple: true, direct_upload: true, class: 'form-control' %>
</div>
```

... I get the following errors:

```bash
ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature):
```
and

```bash
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_active_storage_attachments_uniqueness"
```

I tried doing `rails db:reset` but it was no good.

Is this something to be expected? My goal is to get these nice little progress bars as shown in the [docs](http://edgeguides.rubyonrails.org/active_storage_overview.html#example). Please note that the form works fine if `direct_upload` is set to `false`.

---

### Steps to reproduce

Use ActiveStorage configured to store locally.

```ruby
# development.rb
config.active_storage.service = :local
```

```yml
# storage.yml
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  host: "http://shakalaka.lvh.me:3000"

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: ""
  secret_access_key: ""
```

```erb
<%#= new.html.erb %>
<div class="form-group">
  <%= property.label :images %>
  <%= property.file_field :images, multiple: true, direct_upload: true, class: 'form-control' %>
</div>
```

### Expected behavior

I'd expect active storage to store the files properly on upload. 

### Actual behavior

```bash
ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature):
```
...a couple of lines later

```bash
ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_active_storage_attachments_uniqueness"
```

### System configuration
**Rails version**: Rails 5.2.0.rc1
**Ruby version**: Ruby 2.5.0
