### ISSUE TITLE
undefined method `recognize_path_with_request' for #<Array:0x...>

### ISSUE THREAD

**Issue by S-YOU** [rails/rails#32312]
### Steps to reproduce

Routing specs on a rails app are failing after upgrade to rails 5.2.0.rc2

```
  # bundle exec rspec 
  1) GroupsController routing routes to #index
     Failure/Error: expect(:get => "/groups").to route_to("groups#index")
     
     NoMethodError:
       undefined method `recognize_path_with_request' for #<Array:0x00007fe6a7368590>
     # ./spec/routing/groups_routing_spec.rb:7:in `block (3 levels) in <top (required)>'
```

code (by rails generate)
```
    it "routes to #index" do
      expect(:get => "/groups").to route_to("groups#index")
    end
```

I am not sure this is the issue with rspec or rspec-rails but error seems to be come from rails 5.2.0.rc2.

### Expected behavior
No error

### Actual behavior
NoMethodError:
       undefined method `recognize_path_with_request' for #<Array:

### System configuration
**Rails version**:
Rails 5.2.0.rc2

**Ruby version**:
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

**Comment by pixeltrix** [comment]
@S-YOU I can't reproduce this in a test script - can you? Here's a script you can modify that currently passes:

``` ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"
  gem "rails", "5.2.0.rc2"
  gem "rspec-rails"
end

require "rack/test"
require "action_controller/railtie"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_key_base = "secret_key_base"

  config.logger = Logger.new("/dev/null")
  Rails.logger  = config.logger

  routes.draw do
    resources :groups
  end
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers
end

class GroupsController < ApplicationController
  def index
    render plain: "groups#index"
  end
end

require "rspec/rails"
require "rspec/autorun"

RSpec.describe "/groups", type: :routing do
  it "routes to #index" do
    expect(get: "/groups").to route_to("groups#index")
  end
end
```

**Comment by pixeltrix** [comment]
Also was this an upgrade from RC1 => RC2 or from an earlier Rails version.

**Comment by S-YOU** [comment]
Mine was from 5.1.5, but I can't seems to reproduce with new rails install, closing for now. 
Might reopen If I can reproduce reliably.

**Comment by S-YOU** [comment]
btw, this is the trace with -b (without home folder path) for more detail.

```
  routing
    routes to #index (FAILED - 1)

Failures:

  1) GroupsController routing routes to #index
     Failure/Error: expect(:get => "/groups").to route_to("groups#index")

     NoMethodError:
       undefined method `recognize_path_with_request' for #<Array:0x00007fed891c2fe0>
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/routing/route_set.rb:878:in `block in recognize_path_with_request'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/journey/router.rb:75:in `block in recognize'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/journey/router.rb:68:in `each'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/journey/router.rb:68:in `recognize'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/routing/route_set.rb:859:in `recognize_path_with_request'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/routing/route_set.rb:855:in `recognize_path'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/testing/assertions/routing.rb:208:in `block in recognized_request_for'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/testing/assertions/routing.rb:216:in `fail_on'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/testing/assertions/routing.rb:207:in `recognized_request_for'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-5.2.0.rc2/lib/action_dispatch/testing/assertions/routing.rb:48:in `assert_recognizes'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:107:in `block (4 levels) in initialize'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-rails-3.7.2/lib/rspec/rails/matchers/routing_matchers.rb:27:in `block in matches?'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-expectations-3.7.0/lib/rspec/matchers/built_in/base_matcher.rb:50:in `match_unless_raises'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-rails-3.7.2/lib/rspec/rails/matchers/routing_matchers.rb:25:in `matches?'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-expectations-3.7.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/routing/groups_routing_spec.rb:7:in `block (3 levels) in <top (required)>'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `instance_exec'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:254:in `block in run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `block in run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:606:in `block in run_around_example_hooks_for'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-rails-3.7.2/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:447:in `instance_exec'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:375:in `execute_with'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:608:in `block (2 levels) in run_around_example_hooks_for'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:342:in `call'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:609:in `run_around_example_hooks_for'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:466:in `run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example.rb:251:in `run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:628:in `block in run_examples'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `map'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:624:in `run_examples'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:590:in `run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `block in run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `map'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:591:in `run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
     # ~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
     # ~/.rbenv/versions/2.5.0/bin/rspec:23:in `load'
     # ~/.rbenv/versions/2.5.0/bin/rspec:23:in `<main>'

Finished in 0.07776 seconds (files took 8.64 seconds to load)
1 example, 1 failure
```
