### ISSUE TITLE
ActiveStorage: No Cache-Control header set on GCS, defaulting to "private,max-age=0"

### ISSUE THREAD

**Issue by lucaong** [rails/rails#32325]
### Steps to reproduce

Setup `ActiveStorage` with Google Cloud Storage service:

```yaml
# storage.yaml
google:
  service: GCS
  credentials: <%= ENV['GCS_CREDENTIALS'] %>
  project: "my-project-id"
  bucket: "my-bucket-name"
```

```ruby
class MyModel < ApplicationRecord
    has_one_attached :image
end
```

### Expected behavior
The `Cache-Control` header for the uploaded file should be set to a sensible and configurable default. Otherwise, on Google Cloud Storage, the default is particularly problematic (`private,max-age=0`). There is currently no way to set the default on Google Cloud side, making the problem particularly annoying compared to other storage backends.

Ideally, `ActiveStorage` could read a global default in the `storage.yml` file, maybe with a way to override it for specific cases. Something like:

```yaml
# Global default on storage.yml
google:
  service: GCS
  credentials: <%= ENV['GCS_CREDENTIALS'] %>
  project: "my-project-id"
  bucket: "my-bucket-name"
  object_defaults:
    cache-control: "public, max-age=3600"
```

### Actual behavior
No `Cache-Control` header is set, causing Google Cloud Storage to default to `Cache-Control: private,max-age=0`. This causes files to never be cached by the browser, which can easily become very problematic on pages showing many uploaded files. There is currently no way on Google Cloud Storage to set a default cache control for the whole bucket, therefore the only reasonable way seems to be to set the cache control upon file upload.

### System configuration
**Rails version**: `5.2.0-rc2`

**Ruby version**: `2.5.0`
