### ISSUE TITLE
belongs_to and i18n not working

### ISSUE THREAD

**Issue by DrobyshevAlex** [rails/rails#32351]
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
Rails 5.1.5

```
I have models:
class Address < ApplicationRecord
...
end
```

```
class Order < ApplicationRecord
  belongs_to :address, optional: true
  accepts_nested_attributes_for :address, allow_destroy: true, reject_if: proc { |attributes| attributes[:zip].blank? }
...
```

and nested form
```
<%= form_for @model do |f| %>
...
<%= f.fields_for :address_attributes do |addr| %>
<%= addr.label :zip %>
...
```
I tried to

```
ru:
  activerecord:
    attributes:
      address:
        zip: 'Индекс'
      order:
        ...
```

```
...
      address:
        zip: 'Индекс'
      order:
        address:
          zip: 'Индекс'
```

```
      address:
        zip: 'Индекс'
      order:
        address_attributes:
          zip: 'Индекс'

```
```
      address:
        zip: 'Индекс'
      address_attributes:
        zip: 'Индекс'
      order:
        ...

```
```
...
      address:
        zip: 'Индекс'
      order:
        address.zip:'Индекс'
```

```
...
      address:
        zip: 'Индекс'
      order:
        address[zip]:'Индекс'
```

```
...
      address:
        zip: 'Индекс'
      order:
        address_attributes[zip]:'Индекс'
```

```
...
      address:
        zip: 'Индекс'
      order:
        address_attributes.zip:'Индекс'
```

Nothing work for me :) Help me please what i'm doing wrong?
