### ISSUE TITLE
Rake DB tasks don't properly initialize environment when switching from development to test env

### ISSUE THREAD

**Issue by thisismydesign** [rails/rails#32926]
When executing Rake DB tasks in development environment they are also executed in test environment ([see](https://github.com/rails/rails/blob/v5.1.5/activerecord/lib/active_record/tasks/database_tasks.rb#L300)). This environment change doesn't prompt the usual intialization but the existing environment config is used, not taking into account that it can dynamically change between environments.

Why is this a problem?

1,  Consider the following [Rails feature]((http://edgeguides.rubyonrails.org/configuring.html#configuring-a-database)):

> The config/database.yml file can contain ERB tags <%= %>. Anything in the tags will be evaluated as Ruby code. You can use this to pull out data from an environment variable or to perform calculations to generate the needed connection information.

For example having different values in test env will not be taken into account in this case. This is known to cause issues with dotenv: https://github.com/bkeepers/dotenv/issues/302.

2,  AFAICT `Rails.env` and `DatabaseTasks.env` are not set correctly after the env change. Amongst other possible issues I believe is the root cause of #26731 which is being solved by [hardcoding test env](https://github.com/rails/rails/pull/30579/files#diff-28a5ae383b291583c513ad8eeed99a3aR316) instead of using [`current_environment`](https://github.com/rails/rails/pull/30579/files#diff-1452ba37bae4c4676b4288be7db09b8dL243).

3, I would imagine there are further implications which I didn't discover.

### Steps to reproduce

I reproduce the dotenv issue with a dummy project in the gem [dotenv_rails_db_tasks_fix](https://github.com/thisismydesign/dotenv_rails_db_tasks_fix) (see [db config](https://github.com/thisismydesign/dotenv_rails_db_tasks_fix/blob/v0.2.1/config/database.yml), [.env.test](https://github.com/thisismydesign/dotenv_rails_db_tasks_fix/blob/v0.2.1/.env.test), [.env.development](https://github.com/thisismydesign/dotenv_rails_db_tasks_fix/blob/v0.2.1/.env.development), [test](https://github.com/thisismydesign/dotenv_rails_db_tasks_fix/blob/v0.2.1/spec/dotenv_rails_db_tasks_fix_spec.rb#L18-L30))

### Expected behavior

When switching environments the new one is properly initialized at least in a way to respect existing Rails features (i.e. set env variables such as `Rails.env` and reload `database.yml)`.

### Actual behavior

The existing environment config is used, not taking into account that it can dynamically change between environments.

### System configuration
**Rails version**: Rails 5.1.6

**Ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

**Comment by deivid-rodriguez** [comment]
Have a look at https://github.com/rails/rails/issues/27299. Even if this is a misbehavior for a lot of us, the Rails team acknowledges it as a feature. So the only way out seems monkeypatching the tasks to do the right thing... There's a link to a gem in that thread to help with that.

**Comment by thisismydesign** [comment]
@deivid-rodriguez Thanks. Yep I saw that issue and my concerns are different here. Although a solution could be made along those lines as well, e.g. a simple ENV option to disable "double" execution would also work.

**Comment by morgoth** [comment]
It's also an issue for me, where my `config/database.yml` looks like:
```yaml
development:
  url: <%= ENV["DATABASE_URL"] %>
test:
  url: <%= ENV["DATABASE_URL"] %>
```

and trying to run `bin/rails db:structure:load` it runs it twice on same db (just happening to be the same db for development and test), raising errors (as structure cannot be loaded twice on the same db).

At least having some switch to turn it off would be helpful.

**Comment by thisismydesign** [comment]
Same issue with 5.2.0, see: https://github.com/rails/rails/blob/v5.2.0/activerecord/lib/active_record/tasks/database_tasks.rb#L311

**Comment by noma4i** [comment]
Issue occurs on master as for 8th November 2018.

**Comment by thisismydesign** [comment]
Still present. In my experience, this issue affects a lot of people. Would be great to get some sort of feedback.

**Comment by phil** [comment]
I'm getting the same issue as @morgoth in rails 6.0.0rc1. My `database.yml` uses DATABASE_URL for both development and test envs. as the default is to use development, i cannot using any `db:*` tasks as they're being run on the same database, the development database, and fail because structure already exists.

**Comment by romansavrulin** [comment]
Still exists on Rails 6.0.0. Very annoying!

**Comment by noma4i** [comment]
@tenderlove open this issue back. It's quite clear this is not working for last year

**Comment by romansavrulin** [comment]
quick follow-up

if I use `DATABASE_URL` with the following `database.yml` and `RAILS_ENV=development` running `rake db:create` even tries to create production DB, that is absolutely weird and unexpected!

```yml
# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cm7_rails_api_development

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  username: root

  # The password associated with the postgres role (username).
  password: 123321

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  host: 192.168.1.10

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  port: 5532

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: cm7_rails_api_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
```

```
===== DB Actions start RAILS_ENV: development =====
Database 'cm7_rails_api_production' already exists
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Couldn't create 'cm7_rails_api_test' database. Please check your configuration.
rake aborted!
ActiveRecord::NoDatabaseError: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1111:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:231:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:199:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'

Caused by:
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:879:in `new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:923:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:902:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:863:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:587:in `checkout'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:431:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:1111:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:231:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/connection_handling.rb:199:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:126:in `create'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:185:in `block in create_current'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:479:in `block (2 levels) in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `each'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:476:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:475:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:184:in `create_current'
/usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:39:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
===== DB Actions end =====
```
