### ISSUE TITLE
ActiveStorage Cannot load `Rails.config.active_storage.service`

### ISSUE THREAD

**Issue by vadimstroganov** [rails/rails#35106]
If you select a openstack_username value that does not contain letters, then you get an error: 
```
Cannot load `Rails.config.active_storage.service`: JSON::ParserError
```

### Steps to reproduce
Use this gems for activestorage service:
```
gem 'activestorage-openstack', '0.5.0'
gem 'fog-openstack', '0.3.1'
```

Add service to storage.yml:
```
dev_openstack:
  service: OpenStack
  container: my_container
  credentials:
    openstack_auth_url: https://auth.selcdn.ru
    openstack_username: 23456
    openstack_api_key: password
```

Set active_storage service:
```
config.active_storage.service = :dev_openstack
```

Try upload image via activestorage

### Expected behavior
I expect the file to load successfully

### Actual behavior
I got error:
```
Cannot load `Rails.config.active_storage.service`: JSON::ParserError
```

But if openstack_username contains letters, then all is well. (example: 23456_letters)

I also tried to wrap the value in quotes. But it didn't.

### System configuration
**Rails version**: 5.2.1

**Ruby version**: 2.5.1

[app.zip](https://github.com/rails/rails/files/2814240/demo_openstack.zip)
