### ISSUE TITLE
Connection switching to support multiple databases is not working in Rails 6.0.0.beta3 version

### ISSUE THREAD

**Issue by userrails** [rails/rails#36078]
### Steps to reproduce
I have read the documentation about MultiDb connection switching of Rails 6.0.0.beta3 and implemented this way:

### database.yml
```
default: &default
   adapter: mysql2
   encoding: utf8mb4
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   username: root
   password: root
   socket: /var/run/mysqld/mysqld.sock

development:
  main:
    <<: *default
    database: r6_multidb_development

  main_replica:
    <<: *default
    database: r6_multidb_development_copy
    replica: true
```

### Article Model
```
class Article < ApplicationRecord
  connect_to database: { writing: :main, reading: :main_replica }
end
```

### Expected behavior
Both the databases r6_multidb_development and r6_multidb_development_copy have different records, i was expecting when record is created records should inserted on r6_multidb_development Database and when retrieving record it should from r6_multidb_development_copy database. But in both cases when record is inserted and retrieved it is happening from main configuration that is r6_multidb_development database.

I believe write to the database should happen from r6_multidb_development and read should happen from r6_multidb_development_copy. I would appreciate if anybody figure out this issue.

### System configuration
**Rails 6.0.0.beta3**

**Ruby 2.6.2p47**
