### ISSUE TITLE
Migrations not namespaced by database in Rails 6

### ISSUE THREAD

**Issue by ionut998** [rails/rails#36205]
### Steps to reproduce
- `rails new project5`
- change config/database.yml file for multiple databases like here: https://github.com/ionut998/project5/blob/master/config/database.yml
- `bin/rails g migration create_dogs --database=animals`

### Expected behavior
The migration file gets created under db/migrate/animals

### Actual behavior
The migration file gets created under db/migrate

### System configuration
**Rails version**: 6.0.0.rc1
**Ruby version**: 2.5.0p0

I am trying to understand if I am doing something wrong or the migrations don't get created in the right folder.
I am trying to create an app with 2 databases that have different structures.
- database primary that contains users table
- database animals that contains dogs table

Here is the config that I have in config/database.yml file
```
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  primary:
    <<: *default
    database: my_primary_db
    user: root
  animals:
    <<: *default
    database: my_animals_db
    user: root
```

When I run `bin/rails g migration create_users` the 2019..._create_users.rb migration get's created under `db/migrate` folder. I expect this to get created under `db/migrate/primary`.
The same happens when I run `bin/rails g migration create_dogs --database=animals`. The file `2019..._create_dogs.rb` gets created under `db/migrate` and I expect this to get created under `db/migrate/animals`

If I then go ahead and migrate the database then Rails does create 2 schemas under the db folder (schema.rb and animals_schema.rb), however they both have the same content.

Project to reproduce: https://github.com/ionut998/project5
