### ISSUE TITLE
database.yml no longer supports arbitrary ERB output

### ISSUE THREAD

**Issue by chukitow** [rails/rails#36285]
### Steps to reproduce
This issue is similar to https://github.com/rails/rails/issues/36088 and was fixed https://github.com/rails/rails/pull/36237 but I think the following scenario was not fixed.

```yml
          development:
            database: <%= Rails.application.config.database ? 'db/development.sqlite3' : 'db/development.sqlite3' %>
            adapter: sqlite3
```

### Expected behavior
DummyERBCompiler should return a valid YAML file

### Actual behavior
`Psych::SyntaxError shown above.`
