### ISSUE TITLE
Multiple db connection issues

### ISSUE THREAD

**Issue by morgoth** [rails/rails#36382]
While integrating multiple databases feature (Rails 6.0.0.rc1) I found surprising behavior:
Given:
```yaml
# database.yml
test:
  primary:
    <<: *default
    database: db/test.sqlite3
  replica:
    <<: *default
    database: db/test.sqlite3
    replica: true
```
```ruby
# application_record.rb
class ApplicationRecord < ActiveRecord::Base
￼  self.abstract_class = true
￼  connects_to database: {writing: :primary, reading: :replica}
￼end
```
and then creating some record `User.create!` and in the same transaction quering for it:
```ruby
ApplicationRecord.connection.execute("select count(*) from users;").first.values.first
```
this works as expected, however 
```ruby
ActiveRecord::Base.connection.execute("select count(*) from users;").first.values.first
```
 does not, as it returns 0.

I'm not sure if this is an issue in the Rails itself, as it might surprise developers or just not refreshed documentation after introducing multiple db support. If the other, should we now recommend to use `AppliationRecord.connection` and `ApplicationRecord.transaction` in all places?
You can see the commit reproducing issue here https://github.com/morgoth/ar_issue/commit/ff01fe3b54d92540ebe1e501d504218f23aed8d7

@eileencodes let me know if I can help somehow.
