### ISSUE TITLE
6.0.0rc1 Psych::BadAlias: Unknown alias: dummy_compiler in load_database_yaml

### ISSUE THREAD

**Issue by klyonrad** [rails/rails#36540]
### Steps to reproduce

database yaml
```yaml
sqlite: &sqlite
  adapter: sqlite3
  database: db/test.sqlite3

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: lazybar_ci_test
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "sqlite" %>

test:
  <<: *defaults
```

$DB env variable is 'postgresql'

`RAILS_ENV=test bundle exec rails db:migrate`

### Expected behavior

Successful execution of database migrations

### Actual behavior

Following exception is raised:

```
rails aborted!
Psych::BadAlias: Unknown alias: dummy_compiler
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/railties-6.0.0.rc1/lib/rails/application/configuration.rb:207:in `load_database_yaml'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/tasks/database_tasks.rb:147:in `for_each'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:26:in `block (2 levels) in <main>'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:21:in `block in <main>'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc1/lib/active_record/railties/databases.rake:5:in `<main>'
/home/travis/build/klyonrad/lazybar/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:69:in `load'

....

/lib/active_support/dependencies.rb:302:in `require'
bin/rails:4:in `<main>'
Caused by:
Bootsnap::LoadPathCache::FallbackScan: 

```

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

## Additional Notes

I removed the inline ERB and then it went through.
