### ISSUE TITLE
Specific database URL in database.yml config is overwritten if ENV['DATABASE_URL'] exists 

### ISSUE THREAD

**Issue by jholmes12** [rails/rails#36610]
### Steps to reproduce
1. Set up new rails v6.0.0.rc1 app

2. Add an additional database config in database.yml with specific url.

```
external_database:
  url: <%= ENV['EXTERNAL_DB_URL'] %>
````
3.   Add environment variables 'DATABASE_URL' as well as a different 'EXTERNAL_DB_URL' (used in the config above).

### Expected behavior
As stated in the Rails Guides:

> The only way to explicitly not use the connection information in ENV['DATABASE_URL'] is to specify an explicit URL connection using the "url" sub key:

The external_database connection should be using the specified url, not ENV['DATABASE_URL'].

### Actual behavior
When rails builds the database configs on loading, if DATABASE_URL is present, it is used for ALL configs in database.yml, even if a "url:" is specified.

### System configuration
**Rails version**: 6.0.0.rc1

**Ruby version**: 2.6.3

### Additional Notes
It appears that this functionality has changed since 5.2.3. Here's the code in 5.2.3 where this appeared to allow db configs with a url key to keep the specified url:

https://github.com/rails/rails/blob/b9ca94caea2ca6a6cc09abaffaad67b447134079/activerecord/lib/active_record/connection_handling.rb#L76-L84

Here is the code in 6.0.0.rc1 where the url configs are built, but a specific url in the database.yml file is over-written if the ENV['DATABASE_URL'] exists

https://github.com/rails/rails/blob/01b7e9b73ac9dca92be0969e047b9cb0c767f261/activerecord/lib/active_record/database_configurations.rb#L156-L167

A small conditional check if a database config specifies a url fixes this issue and allows the configs to be built correctly, with any "specific" urls defined in database.yml to pass through.

```
configs.map do |config|
              if config.url_config?
                config
              else
                ActiveRecord::DatabaseConfigurations::UrlConfig.new(config.env_name, config.spec_name, url, config.config)
              end
            end
```

**Comment by eileencodes** [comment]
Can you make a new app and share it with me so I can debug easier? Otherwise I'm guessing a little bit at what behavior should be preserved.

**Comment by jholmes12** [comment]
Hi @eileencodes , yes of course thanks so much for looking into this!

Here is a basic app setup to demonstrate this issue:

https://github.com/jholmes12/external-db-urls-config

Let me know if you have any thoughts or questions, really appreciate it!

**Comment by wjessop** [comment]
I took a look into this and I think I understand the issue. @jholmes12 is expecting the database URL for the `external_db` database config (copied here for ease of reference):

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: external_db_url_config_development

production:
  <<: *default
  database: external_db_url_config_production
  url: <%= ENV['DATABASE_URL'] %>

external_db:
  url: <%= ENV['EXTERNAL_DB_URL'] %>
```

to be set to the value of the EXTERNAL_DB_URL env var when running the app in development mode, however it ends up being set to the DATABASE_URL env var instead, despite having a `url:` key which should prevent that.

I think the reason this happens is [`database_configurations.rb:156`](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/database_configurations.rb#L156):

```ruby
      def build_url_config(url, configs)
        env = ActiveRecord::ConnectionHandling::DEFAULT_ENV.call.to_s

        if original_config = configs.find(&:for_current_env?) # <----------------- here
          if original_config.url_config?
            configs
          else
            configs.map do |config|
              ActiveRecord::DatabaseConfigurations::UrlConfig.new(config.env_name, config.spec_name, url, config.config)
            end
          end
        else
          configs + [ActiveRecord::DatabaseConfigurations::UrlConfig.new(env, "primary", url)]
        end
    end
```

On this line we *only* get the development env from the database.yml:

```
(byebug) configs.find(&:for_current_env?)
#<ActiveRecord::DatabaseConfigurations::HashConfig:0x00007fa0a565b038 @env_name="development", @spec_name="primary", @config={"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"external_db_url_config_development"}>
```

As the development env is not a `original_config.url_config?` in this situation we fall through to the code:

```ruby
configs.map do |config|
  ActiveRecord::DatabaseConfigurations::UrlConfig.new(config.env_name, config.spec_name, url, config.config)
end
```

Where `url` is [populated earlier from ENV["DATABASE_URL"] ](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/database_configurations.rb#L111). This code doesn't have a `url_config?` condition as @jholmes12 points out, so even if the config has a `url:` parameter in the database.yml at this point it will be trampled by `ActiveRecord::DatabaseConfigurations::UrlConfig.new` which doesn't match the behaviour described in the docs.

To fix this we could use the suggested patch, but that doesn't take into account the situation where the current env config (in this case development) *does* have a url config, eg:

```yaml
development:
  <<: *default
  database: external_db_url_config_development
  url: "postgres://static/foo"

production:
  <<: *default
  database: wrong

external_db:
  database: wrong
```

In this situation the docs suggest that the database config should be replaced by the DATABASE_URL env value, but it is not:

```
$ RAILS_ENV=development rake db_configs
------  Production database config using the provided DATABASE_URL --------
{"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"wrong"}


------  External database config, is still using DATABASE_URL instead of EXTERNAL_DB_URL --------
{"database"=>"wrong"}

```
