### ISSUE TITLE
Heroku - Multi database - Rails 6

### ISSUE THREAD

**Issue by saslani** [rails/rails#36850]
https://stackoverflow.com/questions/57335433/heroku-rails-6-multi-database
I have tried solution in "closed" issues, but still not working

rails: `gem "rails", "6.0.0.rc2"`

I have multiple databases. None are replicas (I am reading and writing in all 3):
Before rails 6, I used multiverse gem and everything looked fine.I followed rails 6 and multiverse change to rails 6 docs. But I cannot run db:migrate in Heroku, even though, everything works perfectly locally.

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :primary
end

.

class ObsRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :obs
end

.

class AbcRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :abc
end

```

database.yml
```
staging:
  primary:
    <<: *default
    adapter: postgresql
    url:  <%= ENV['DATABASE_URL'] %>
    username: <%= ENV['DATABASE_USER'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
  obs:
    <<: *default
    adapter: postgresql
    url: <%= ENV['OBS_DATABASE_URL'] %>
    username: <%= ENV['OBS_DATABASE_USER'] %>
    password: <%= ENV['OBS_DATABASE_PASSWORD'] %>
    migrations_paths: db/obs_migrate
  abc:
    <<: *default
    adapter: postgresql
    url: <%= ENV['ABC_DATABASE_URL'] %>
    username: <%= ENV['ABC_DATABASE_USER'] %>
    password: <%= ENV['ABC_DATABASE_PASSWORD'] %>
    migrations_paths: db/abc_migrate

```

`rails db:migrate` shows nothing, as if there are no migrations but when I run `rails c` I see the following error. And yes, I am sure the lates code is pushed. 

`heroku restart` is not helping

Heroku error:
```
Traceback (most recent call last):
	102: from /app/bin/rails:4:in `<main>'
	101: from /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:322:in `require'
.
.
4: from /app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc2/lib/active_record/connection_handling.rb:50:in `establish_connection'
	  3: from /app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc2/lib/active_record/connection_handling.rb:180:in `resolve_config_for_connection'
	  2: from /app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc2/lib/active_record/connection_adapters/connection_specification.rb:140:in `resolve'
	  1: from /app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc2/lib/active_record/connection_adapters/connection_specification.rb:219:in `resolve_connection'.
.

/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.0.rc2/lib/active_record/connection_adapters/connection_specification.rb:251:in `resolve_symbol_connection': The `abc` database is not configured for the `staging` environment. (ActiveRecord::AdapterNotSpecified)

Available databases configurations are:

default
prod_uat_default
development
test
staging
uat
production
```

^^ I am expecting primary database as well as abc and obs under staging.
