### ISSUE TITLE
Rails 6 - Oracle-enhanced adapter - connection issues

### ISSUE THREAD

**Issue by saslani** [rails/rails#36938]
### Steps to reproduce
When using multidatabase feature in which one database is on postgres and the other on oracle, connection gets lost and resets to the primary database defaults

### Expected behavior
- ApplicationRecord that uses primary database and is on postgres should alway connect to postgres
- Db2Record that uses oracle database should always connect to the oracle database with configurations that's been provided

### Actual behavior
- The first time I run `Db2Record.connection_config` is shows correct configuration
- When I establish the connection, is switches back to postgres `Db2Record.establishconnection.connection` shows that it's connected to postgres
- Therefore is shows the tables that are in primary database, postgres instead of those that are in Db2 oracle
- Now if I run `Db2Record.connection_config` "again" it shows the primary database's configs

**Please note** that 
- I am using **service_name** not SID 
- I am passing **schema** for oracle
- My Db2 (oracle) is **not** a replica, and I just need to read from it

```
Rais c:

Db2Record.connection_config
=> {:adapter=>"oracle_enhanced", :pool=>5, :timeout=>5000, :encoding=>"unicode", :host=>"host_dab_address.com", :database=>"/service_name", :port=>1521, :schema=>"DB2_ELEC", :username=>"db2_viewer", :password=>db2_pass}

irb(main):002:0> Db2Record.establish_connection.connection.tables
=> ["schema_migrations", "ar_internal_metadata", "tables that are in my primary postgres db"]
irb(main):003:0> Db2Record.connection_config
=> {:adapter=>"postgresql", :pool=>5, :timeout=>5000, :encoding=>"unicode", :user=>"postgres", :database=>"db1"}

^^ note that's switched to postgers and primary database config 
```

- However, manually in the terminal, if I run:
```
ActiveRecord::Base.establish_connection(adapter: 'oracle_enhanced', host: 'host_dab_address.com', port: '1521', database: '/service_name', username: 'db2_viewer', password: 'db2_pass', schema: 'DB2_ELEC').connection.tables
``` 
I see correct connections and tables.
- If I put this exact line in Db2Record, to establish connection, it goes back to postgres

### System configuration
**Rails version**: 6.0-stable (gem "rails", github: "rails/rails", branch: "6-0-stable")
**Ruby version**: 2.6.3

- Reproducible in linux, redhat (I was able to reproduce that once on Mac and none on Debian so far)
- activerecord-oracle_enhanced-adapter , git: "https://github.com/rsim/oracle-enhanced.git", branch: "release60"

local oracle setup on my mac, Debian and Redhat:

**/opt/oracle:**
```
drwxr-xr-x   3 root  Aug 14 14:02 instantclient_12_2
-rw-rw-r--   1 blahuser  Aug 14 13:42 instantclient-basic-linux.x64-12.2.0.1.0.zip
-rw-rw-r--   1 blahuser Aug 14 13:42 instantclient-sdk-linux.x64-12.2.0.1.0.zip
-rw-rw-r--   1 blahuser Aug 14 13:42 instantclient-sqlplus-linux.x64-12.2.0.1.0.zip
-rw-rw-r--   1 blahuser Aug 14 13:42 instantclient-tools-linux.x64-12.2.0.1.0.zip
lrwxrwxrwx   1 root        Aug 14 13:50 libclntsh.dylib -> libclntsh.dylib.12.1
```

**Exported environment variables**
```
OCI_DIR=/opt/oracle/instantclient_12_2
ORACLE_HOME=/opt/oracle/instantclient_12_2
LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2
```

**Gemfile:**
```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.3"
..
gem "bootsnap", "1.4.4", require: false
..
gem "pg", "1.1.4"
gem "puma", "4.0.1"
..
gem "rails", github: "rails/rails", branch: "6-0-stable"
..

group :development, :uat, :production do
  gem "activerecord-oracle_enhanced-adapter", git: "https://github.com/rsim/oracle-enhanced.git", branch: "release60"
  gem "ruby-oci8", "2.2.7"
end
```

I have 2 databases in my env. (let's focus on Development environment). My primary database is called db1 and it's using postgres. The other database, db2 is on oracle.

**database.yml**
```
development:
  primary:
      adapter: postgresql
      pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
      timeout: 5000
      encoding: unicode
      user: postgres
     database: db1
  db2:
    adapter: oracle_enhanced
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
    encoding: unicode
    database: <%= ENV['DB2_DATABASE'] %>
    host: <%= ENV['DB2_DATABASE_HOST'] %>
    port: <%= ENV['DB2_DATABASE_PORT'] %>
    schema:  <%= ENV['DB2_DATABASE_SCHEMA'] %>
    username: <%= ENV['DB2_DATABASE_USER'] %>
    password: <%= ENV['DB2_DATABASE_PASSWORD'] %>
```

Not much change in my **application_record.rb** (postgres)
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :primary
end
```

db2_record establishes connection to db_2, which is oracle
```
class Db2Record < ActiveRecord::Base
  self.abstract_class = true
  establish_connection :db2
end
```
Last bug not the list, I have a model that inherits from **Db2Record**:
```
class Customer < Db2Record
.
.

```

Is this a race issue?
