### ISSUE TITLE
accepts_nested_attributes_for not support `belongs_to`

### ISSUE THREAD

**Issue by 7uthaifah** [rails/rails#37151]
### Steps to reproduce

I'm trying to store state with the selected country.

```
# app/models/country.rb
class Country < ApplicationRecord
  has_many :states
end
```

```
# app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  accepts_nested_attributes_for :country
end
```

```
# app/controllers/states_controller.rb
def new
  @state = State.new
  @state.build_country
end

def create
  @state = State.new(state_params)

  if @state.save
    redirect_to @state, notice: 'State was successfully created.'
  else
    render :new
  end
end

private
def state_params
  params.require(:state).permit(:name, country_attributes:[:id])
end
```

```
# app/views/states/_form.erb
<%= form.fields_for :country, state.country do |country_fields| %>
  <div class="field">
    <%= country_fields.label :name %>
    <%= country_fields.collection_select :id, Country.all, :id, :name %>
  </div>
<% end %>
<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
```

### Expected behavior
I think this is because the relationship is `belongs_to` so rails is trying to get the country with the id of state but the state is not created yet!

### System configuration
**Rails version**:6.0

**Ruby version**:5.2.3

**Comment by p8** [comment]
This happens because `belongs_to` defaults to `required: true`.
You have to add optional: true to the `belongs_to`
```
belongs_to :country, optional: true
```

**Comment by 7uthaifah** [comment]
> This happens because `belongs_to` defaults to `required: true`.
> You have to add optional: true to the `belongs_to`
> 
> ```
> belongs_to :country, optional: true
> ```

Thanks @p8 for your help, but actually, I've tried this before.

I think that the main problem is because rails is trying to find country according to state_id and the state_id still nil, so rails don't support `id` attributes as I found at 

https://github.com/rails/rails/blob/179a5b8770e99dd468ae5e7a1eb49fcea3b411b9/activerecord/lib/active_record/nested_attributes.rb#L416

so rails throw error
https://github.com/rails/rails/blob/179a5b8770e99dd468ae5e7a1eb49fcea3b411b9/activerecord/lib/active_record/nested_attributes.rb#L593

**Comment by latortuga** [comment]
The way you're setting up your form is backwards. Because `State` `belongs_to :country`, I expect that the `states` table has a `country_id` column. Your form does not need to use nested attributes, you can build a select for the `country_id` column.

**Comment by 7uthaifah** [comment]
I'm trying to use `accepts_nested_attributes_for` because it instantiates association class and that helps while using `i18n` localization.

I need to pass every translation if I didn't use `accepts_nested_attributes_for`, for example:
```
# config/locales/en.yml
en:
  activerecord:
    errors:
      models:
        state:
          attributes:
            country:
              required: Country must exists
```

but if the association is instancated using `accepts_nested_attributes_for`, I can use:
```
# config/locales/en.yml
en:
  activerecord:
    models:
      country:
        one: Country
        other: Countries
      state:
        one: State
        other: States
    attributes:
      country:
        name: Country name
      state:
        name: State name
```

**Comment by latortuga** [comment]
This isn't really the place to troubleshoot this kind of thing - this isn't a bug with Rails. The original presented use of nested attributes isn't what it's for because you aren't creating a Country, just associating an existing one.

However, I think what you're looking for is this: you can globally override the text used when a `belongs_to` required validation fails. You can use the following locale key:

```yml
en:
  activerecord:
    errors:
      messages:
        required: "must be 100% real"
```

Which will result in:

```ruby
State.create.errors.full_messages #=> ["Country must be 100% real"]
```

Lastly, and you might already know this, but "Country must exists" is not correct in English, it should be "Country must exist".
