### ISSUE TITLE
configuration guide for PostgresQL should also mention 'host' key

### ISSUE THREAD

**Issue by numice** [rails/rails#37513]
### Steps to reproduce
If you have configuration in database.yml like this as in the guide for configuring suggests [link](https://guides.rubyonrails.org/configuring.html#configuring-a-postgresql-database), then you'll get an error ``FATAL: Peer authentication failed``. This is also mentioned in StackOverflow [link](https://stackoverflow.com/questions/9987171/rails-3-2-fatal-peer-authentication-failed-for-user-pgerror). Basically, 'host' key is needed for development on a local machine to properly setup and run ``rails db:create``. This is, however, not mentioned anywhere in the guides. 

### Expected behavior
Expect to follow the configuration as shown in the guides and be able to run ``rails db:create``

### Actual behavior
Get ``FATAL: Peer authentication failed`` error

### System configuration
**Rails version**: 6.0

**Ruby version**: 2.5.1

**Comment by wonda-tea-coffee** [comment]
It worked fine without 'host' key.

config/database.yml
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <username>
  password: <password>

development:
  <<: *default
  database: *_development
```

**Rails version**: 6.0

**Ruby version**: 2.5.1

**PostgreSQL**: 11.5
