### ISSUE TITLE
Edge ActiveStorage unnecessarily tries to configure unused service (S3) in test environment

### ISSUE THREAD

**Issue by khustochka** [rails/rails#37569]
### Steps to reproduce
**[Demo application](https://github.com/khustochka/storageconfigtest)**

Reproduced on edge Rails but not on 6.0.

I have config/storage.yml as follows:

````
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV["aws_access_key_id"] %>
  secret_access_key: <%= ENV["aws_secret_access_key"] %>
  region: us-east-1
  bucket:  <%= ENV["aws_bucket"] %>
````

These environment variables are not set on my development machine, because I am not using S3 in dev or test environment.

But when I run the tests (which are supposed to use `test` storage service), they unnecessarily try to configure the S3 storage and fail to do so:

````
Error:
ArticleTest#test_attach:
Aws::Sigv4::Errors::MissingCredentialsError: missing credentials, provide credentials with one of the following options:
  - :access_key_id and :secret_access_key
  - :credentials
  - :credentials_provider
    test/models/article_test.rb:7:in `block in <class:ArticleTest>'


rails test test/models/article_test.rb:4
````
**[Demo application](https://github.com/khustochka/storageconfigtest)**

This happens somewhere in https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service_registry.rb#L13, when trying to fetch test configuration, but it also tries to configure all available configurations.

### Notes
It is not reproduced in Rails 6.0

### Expected behavior
If environment is not using S3 storage service, it should not try to configure it.

### Actual behavior
It fails because of failing to configure S3 service, even though it is not using S3 in test env.

### System configuration
**Rails version**:
Master branch (82f9d7c8b6b0d541a4cf264ac735a14fa6fee405)

**Ruby version**:
ruby 2.6.5p114
