### ISSUE TITLE
ActionText not setting public read permission for storage with public: true

### ISSUE THREAD

**Issue by vitobotta** [rails/rails#37805]
### Steps to reproduce
- Configure the S3 storage as public 
- Attach files to a rich text area

### Expected behavior
Files should be set in the bucket with public permission and be downloadable from the s3 endpoint.

### Actual behavior
Files are stored as private and thus cannot be downloaded from the s3 endpoint.

### System configuration
**Rails version**:
6.1 (master)

**Ruby version**:
2.6.5

In the same application I am also using ActiveStorage directly, and it does set the public read permission for the attachments. So the problem occurs only with attachments uploaded with ActionText for some reason. Is there any change I can make to work around/fix? Thanks!

**Comment by theasteve** [comment]
Hi @vitobotta, can you please add more context? I would like to help if you can guide me on how to reproduce this issue. What file format are you uploading via ActionText?

**Comment by vitobotta** [comment]
Hi @theasteve :) So I am using a DigitalOcean Space configured as follows:

```yaml
s3:
  access_key_id: "<%= ENV.fetch("S3_ACCESS_KEY_ID", "") %>"
  secret_access_key: "<%= ENV.fetch("S3_SECRET_ACCESS_KEY", "") %>"
  region: "<%= ENV.fetch("S3_REGION", "") %>"
  bucket: "<%= ENV.fetch("S3_BUCKET", "") %>"
  endpoint: "<%= ENV.fetch("S3_ENDPOINT", "") %>"
  public: true
```

So I am setting the bucket/space as public. When I upload files with ActiveStorage (e.g. user profile pictures), the files are uploaded and, as expected, the URLs generated are non-expiring URLs and the acl for those files is set to public.

However, if I attach an image with ActionText, the image is uploaded but cannot be accessed from the endpoint URL because the acl is set to private. 

Am I missing something? I would expect ActionText's uploads to behave the same way as the uploads with ActiveStorage directly. Thanks!
