### ISSUE TITLE
where clause inside 'connected_to' block is not fetching data from replica database

### ISSUE THREAD

**Issue by mdaftab88** [rails/rails#38332]
### Steps to reproduce

1. Create a new rails app using postgresql database
```
rails new replica-test-app database=postgresql
```
2. database.yml config

```
development:
  primary:
    database: my_primary_database
    user: mdaftab88
    adapter: postgresql
  primary_replica:
    database: my_replica_database
    user: mdaftab88
    adapter: postgresql
    replica: true
```
3. Update `application_record.rb`
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :primary_replica }
end
```
4. `rails generate scaffold User name:string role:string`
5. I have updated my `my_replica_database`  to identify the diff.  See the attached image.
<img width="393" alt="Screenshot 2020-01-28 at 12 51 55 PM" src="https://user-images.githubusercontent.com/25167441/73243310-429e6780-41cd-11ea-88a7-70454786b951.png">

### Actual behavior (On Rails Console)

When i fire
```
User.connected_to(role: :reading) { User.find_by(id: 1) }
```
it retrieves record from `my_replica_database`
But when I fire
```
User.connected_to(role: :reading) { User.where(id: 1) }
```
it retrieves record from `my_primary_database`.

Look at the attached console image.
<img width="1048" alt="Screenshot 2020-01-28 at 2 08 37 PM" src="https://user-images.githubusercontent.com/25167441/73247834-c9584200-41d7-11ea-9125-a43705bb81ec.png">

### Expected behavior
On firing
```
User.connected_to(role: :reading) { User.where(id: 1) }
```
it should retrieve record from `my_replica_database`

### System configuration
**Rails version**: 6.0.2.1

**Ruby version**: 2.6.3
