### ISSUE TITLE
Config files live reload on filesystem changes

### ISSUE THREAD

**Issue by jdescelliers** [rails/rails#38406]
### System configuration
**Rails version**: 6.X

**Ruby version**: 2.5

Currently Rails only runs initializers once meaning a server restart is required for changes to take effect.

It would be interesting to mark certain directories/files to be live reloaded.

For example: 
```yml
# <RAILS ROOT>/config/links.yml
some_link: https://some_link.example.com
some_other_link: https://some_other_link.example.com
```

Is it something that can be easily done with Ruby/Rails?

Or maybe add annotation at the top of the the file like so:
```ruby
# <RAILS ROOT>/config/links.yml
# live_reload: true
```
