### ISSUE TITLE
 The `primary_replica` database is not configured for the `development` environment.

### ISSUE THREAD

**Issue by lpelorosso** [rails/rails#38680]
### Expected behavior
Read database configuration from database.yml.

### Actual behavior
Seems to be ignoring the config when specifying a replica database, inside a rake task.
Note that there are no database configurations listed on the error. However, if I remove the `connects_to` from the `Doctors` class, it correctly connects to the `primary` database.

### System configuration
**Rails version**: Rails 6.0.2.1

**Ruby version**: ruby 2.6.3p62

**Rake version**: version 13.0.1

### Error:

ActiveRecord::AdapterNotSpecified: The `primary_replica` database is not configured for the `development` environment.

Available databases configurations are:

/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:252:in `resolve_symbol_connection'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:219:in `resolve_connection'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/connection_specification.rb:140:in `resolve'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:187:in `resolve_config_for_connection'
/home/vertexar/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.2.1/lib/active_record/connection_handling.rb:50:in `establish_connection'
/home/vertexar/Projects/Nusive/patologia.api/lib/tasks/migrate_data.rake:20:in `<class:Doctor>'
/home/vertexar/Projects/Nusive/patologia.api/lib/tasks/migrate_data.rake:18:in `block in <main>'
/home/vertexar/Projects/Nusive/patologia.api/lib/tasks/migrate_data.rake:4:in `<main>'

...

### database.yml

```
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ***
  password: ***
  host: localhost

development:
  primary:
    <<: *default
    database: ****
  primary_replica:
    <<: *default
    adapter: mysql2
    database: ****
    replica: true
```
### Rake Task

Inside rake task I define:

```
  class Doctor < ActiveRecord::Base
    connects_to database: { writing: :primary_replica, reading: :primary_replica }
  end
```
