### ISSUE TITLE
Rails.application.credentials.aws reserved for aws credentials?

### ISSUE THREAD

**Issue by majkelcc** [rails/rails#38754]
### Steps to reproduce
1. Configure Active Storage with a s3 bucket
2. Add the following keys to `config/credentials/{env}.yml.enc`:
```
aws:
  custom_key: 123
``` 
3. Start the application with `eager_load=true` or call `ActiveStorage::Blob.last` in the console.

### Expected behavior
I can run my Rails application and access `Rails.application.credentials.aws[:custom_key]`.

### Actual behavior
Exception when starting the application or calling `ActiveStorage::Blob.last`:

```
Cannot load `Rails.config.active_storage.service`: (ArgumentError)
invalid configuration option `:custom_key'
```
[Full stack strace](https://gist.github.com/majkelcc/1d36a22d76e57fb88d3c3e24fd4f3be3)

### System configuration
**Rails version**: `6.0.2.1`
**AWS SDK S3 version**: `1.60.2`

**Comment by Tiltorito** [comment]
Can you show us, your storage.yml file

**Comment by majkelcc** [comment]
@Tiltorito my `storage.yml` looks like this:

```
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

staging_s3:
  service: S3
  bucket: xyz-bucket-staging

production_s3:
  service: S3
  bucket: xyz-bucket-production
```

I am using an IAM role associated with my ec2 instances for authentication, so I don't have to use any additional credentials.
