### ISSUE TITLE
[Rails 6.0.2.2] - Unable to set MySql database name

### ISSUE THREAD

**Issue by EdOverride** [rails/rails#38862]
### Steps to reproduce
1. Run command
```
rails _6.0.2.2_ new test_abc
```

2. Add to `Gemfile`: `gem 'mysql2'`

3. Run `bundle install`

4. Edit `config/database.yml` to:
```yaml
development:
  adapter: mysql2
  encoding: utf8
  sql_mode: TRADITIONAL
  variables:
    sql_mode: TRADITIONAL
  host: localhost
  port: 3306
  username: root
  password: develop
  database: rails_test-name_development
```

5) Run `rails db:create`

Result:
```
Created database 'localhost'
```

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**:ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

**mysql2 gem version**: 0.5.3
