### ISSUE TITLE
webpacker.yml "source_path" doesn't change "rails generate" locations

### ISSUE THREAD

**Issue by SampsonCrowley** [rails/rails#38989]
## Preface/Explanation
Using the Webpacker gem that now ships with rails by default, I've changed the default `source_path` to use `app/media` instead of `app/javascript`.

Now I would expect anything from `rails generate` that would normally create files under `app/javascript` under default circumstances, would instead properly use the new `source_path`. 

Instead, files continue to be generated under the default `app/javascript`.

The problems seems to stem from a lack of definite ownership; whether `Webpacker` or `Rails` should be in charge of what directory to use for source_files.

Because the _default_ is to use `Webpacker` now, I believe rails should work with the defaults that are update-able in `Webpacker`.

I started with an issue in `rails/webpacker`, but soon after realized the problem actually lies with hard coded paths for `javascript` output with no matching configurable option. `Webpacker.config.source_path` and the output of anything currently going to `app/javascript` should always be aligned

## Problem Code
- set `source_path: app/media` in `config/webpacker.yml`
- `rails g channel Test`

## Expected Behavior
`test_channel.js` is generated under `app/media/channels`

## Actual Behavior
- `app/javascript` is regenerated
- `app/javascript/channels` is regenerated
- a new `index.js` is generated under `app/javascript/channels`
- a new `consumer.js` is generated under `app/javascript/channels`
- `test_channel.js` is generated under `app/javascript/channels`

## System configuration
**Rails version**: 6.0.2

**Ruby version**: 2.7.1

Brand new Rails app (v6.0.2); **only** `source_path` has been modified in webpacker.yml

## config/webpacker.yml
```yml
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/media
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: true

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that correct packages and versions are installed by inspecting package.json, yarn.lock, and node_modules
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true

```
