### ISSUE TITLE
Rails 6.0 causes MySQL database to be emptied during start command in Kubernetes

### ISSUE THREAD

**Issue by sjieg** [rails/rails#39095]
### Steps to reproduce

Let me start by saying I really love the work that everyone does for Rails! I feel like this issue will be difficult to reproduce, but after spending 3 days trying to figure out the problem, I decided to stay with Rails 5.2 for now. Still, because of the severity of the issue (pretty much a database drop), I hope this might shed some light on the cause.

1) Change Gemfile from `gem rails '~> 5.2.0' to `gem rails '~> 6.0.0'`
2) See below the list of gems I used for both Rails 6 and 5.2
3) I've set the autoloader to classic, and even though the Webpacker is installed, it's unused.
```
config.autoloader = :classic
config.load_defaults 5.2
```
4. Build the Image with Docker
5. Deploy to Kubernetes

### Expected behavior

The following commands are executed once the container is up:
```Dockerfile
CMD rm -f tmp/pids/server.pid && \
       bundle exec rails db:migrate && \
	bundle exec rails db:seed && \
	bundle exec rake rswag:specs:swaggerize GROUP=all && \
	bundle exec rake recurring:init && \
	bundle exec ruby bin/delayed_job -n 1 start && \
        bundle exec rails s -b 0.0.0.0 -p 3000
```
Once completed, the server should be up and running with all the database data in place.

### Actual behavior

The database is completely empty. The tables still exists with all the columns, but even the `db:seed` data is not there.

Other notes:

- MySQL is on a separate container.
- Locally the DB is not affected when running the same commands
- Locally with Docker, the DB is not affected
- In the logs between `db:seed` and `rails s` there is nothing showing a dump of the database
- Running `rails db:seed` on the container **after** the deployment is done, seeds the database successfully.
- The MySQL database is actually empty. Also logged in to the MySQL container and checked manually.
- The `:migrate` command does nothing, as the database is completely up to date with the latest migrations.

### System configuration
**Rails version**:
6.0.2.2
**Ruby version**:
2.6.6 & 2.5.7

**Gemfile**
```Ruby
source 'https://rubygems.org'
ruby '~> 2.6'

gem 'rails', '~> 5.2.0'
gem 'sprockets', '~> 3'  # Sprockets 4 has too many bugs. Update to 4 with https://github.com/rails/sprockets/blob/master/UPGRADING.md
gem "webpacker", '~> 5' # Currently Webpacker is unused, but we will move all css, js and images there to make sprockets obsolete
gem 'sass-rails', '~> 6.0'
gem 'sassc', '~> 2.2.1' # Bug on 2.3: https://github.com/sass/sassc-ruby/issues/197
gem 'activerecord-import', '~> 1.0'
gem 'puma', '~> 4.3'
gem 'authlogic', '~> 5'
gem 'google-id-token'
# gem 'symbolize' # very old
# gem 'dynamic_form' # Even older
gem 'paper_trail'
gem 'sneaky-save' # Adds the ability to save a record without doing any callbacks like validations or after_save
gem 'i18n' # Localization gem, seem unused since we only have 1 locale.
gem 'json', '~> 2.0' # Allows faster json reading and writing through a C extension
gem 'jbuilder' # Adds extra helpers to build a json file more codified
gem 'mysql2', '~> 0.5.3' # 0.5.3 came out a week ago
gem 'acts_as_list', '~> 1.0' # Helps with sorting tables using :position
gem 'rack' # We use some of its utilities, but I don't think we use it to serve the webserver
gem 'mimemagic' # Helps detecting mime type files
gem 'rest-client' # Used for doing API calls to other systems
gem 'rufus-scheduler'
gem 'acts_as_tree'
gem 'uuid'
gem 'tzinfo-data'
gem 'uglifier'
gem 'pundit'
gem 'graphql', '1.9.11'
gem 'stripe', '5.2.0'
gem 'delayed_job_active_record'
gem 'delayed_job_recurring'
gem 'activejob-cancel'
gem 'daemons'
gem 'goldiloader'
gem 'rswag' # Used to generate swagger documentation from spec files
gem 'plist' # Required to read .plist.xml files (for XC Test)
gem 'rubyzip', '~> 2' # Used for unzipping files send through the API

#notifications gem
gem 'activity_notification'

#Gems included in the gem 'gentelella-rails'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'font_awesome5_rails'
gem 'coffee-rails'
gem 'coffee-script-source', '1.8.0' # Bug for windows x64 https://stackoverflow.com/questions/28312460
gem 'select2-rails'
gem 'fastclick-rails'
gem 'flot-rails'
gem 'client_side_validations' # Used for inline form validation.
gem 'jquery-datatables' # Front-end table library gem https://github.com/mkhairi/jquery-datatables & https://datatables.net/


#gem 'bootstrap-daterangepicker-rails', '>= 0.1.7' # Including manually in vendors
#gem 'jquery-rails'
#gem 'icheck-rails'
#gem 'nprogress-rails'
#gem 'chart-js-rails'
#gem 'switchery-rails'
#gem 'parsley-rails'

#Gems Admin pages
gem 'activeadmin', '2.7.0'
gem 'country_select'
# gem 'pry', '0.10'
gem 'arctic_admin', '3.2.0' # Active admin design layer
gem 'kaminari' # Pagination tool
gem 'browser', '~> 4' # Used to detect what browser is visiting
gem 'gibbon'

group :test, :staging, :production do
  gem "stackdriver" # Google Cloud debugger tool
end

group :development do
  gem 'web-console' # Debugger tool to allow calling console from view
  gem 'better_errors'
  gem 'sqlite3', '~> 1.4'
  # gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
  gem 'spring-watcher-listen', '~> 2.0'
  gem 'spring-commands-rspec'
  gem 'spring', '~> 2.1'
  gem 'rspec-rails', '~> 3.9'
  gem 'byebug'
  gem 'rspec_junit_formatter'
  gem 'graphiql-rails'
  gem 'wdm', '>= 0.1.0' if Gem.win_platform? # Prevents polling for changes on windows machines.
  gem 'binding_of_caller'
  gem 'memory_profiler'
  gem 'derailed'
  gem 'sys-proctable'
  gem "letter_opener", '~> 1.7.0'  # Opens send emails as file in the browser
end
```

**Dockerfile**
```Dockerfile
FROM ruby:2.6.6

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash \
 && apt-get update && apt-get install -y nodejs && rm -rf /var/lib/apt/lists/* \
 && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
 && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
 && apt-get update && apt-get install -y yarn && rm -rf /var/lib/apt/lists/*
RUN node -v
RUN yarn -v

RUN gem install bundler -v 2.1.4

# Add Gemfile.lock as well so whenever we link our local volume we use the same gem versions
# Remove the Gemfile.lock locally in order to use the latest gem versions
ADD Gemfile* /srv/

RUN mkdir /cache/

WORKDIR /srv

# BUG https://github.com/sass/sassc-ruby/issues/146 > FIX is on master, but not released: https://github.com/sass/sassc-ruby/pull/158
ENV BUNDLE_BUILD__SASSC=--disable-march-tune-native
RUN bundle install

# Install portal & dependencies
ADD . /srv
RUN yarn install

# Clean up APT and bundler when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#Overwrite the revision number in the image
RUN git rev-list --count HEAD > REVISION

EXPOSE 3000

RUN rake assets:precompile

# Set webpacker as asset host
ENV WEBPACKER_DEV_SERVER_HOST=0.0.0.0
# When linking the local volume we need to make sure that no rails server is running and remove server.pid
CMD rm -f tmp/pids/server.pid && \
    bundle exec rails db:migrate && \
	bundle exec rails db:seed && \
	bundle exec rake rswag:specs:swaggerize GROUP=all && \
	bundle exec rake recurring:init && \
	bundle exec ruby bin/delayed_job -n 1 start && \
        bundle exec rails s -b 0.0.0.0 -p 3000
```

**Kubernetes deployment.yml**
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: myapp
      name: myapp
    spec:
      containers:
      - image: eu.gcr.io/google-cloud-project/myapp:latest # Replace with tag if you want to deploy a specific version
        imagePullPolicy: Always
        name: myapp
        ports:
        - containerPort: 3000
          name: myapp
        env:
        - name: RAILS_ENV
          value: production                                       # Replace if you want to deploy a specific environment
        - name: SPROCKETS_CACHE
          value: /cache
        volumeMounts:
        - name: web-persistent-volume
          mountPath: /srv/test_result_assets/
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: web-persistent-volume
        persistentVolumeClaim:
          claimName: web-persistent-volume-claim
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
```

**gitlab-ci-yml (very simplified)**

```
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - docker build --tag=eu.gcr.io/$GC_PROJECT/myapp:$CI_COMMIT_REF_SLUG-$REVISION .
    - docker login -u _json_key --password-stdin https://eu.gcr.io < key.json
    - docker push eu.gcr.io/$GC_PROJECT/myapp:$CI_COMMIT_REF_SLUG-$REVISION
    - docker rmi eu.gcr.io/$GC_PROJECT/myapp:$CI_COMMIT_REF_SLUG-$REVISION
    - cat kube/web-deployment.yml | sed s/myapp:latest/myapp:$CI_COMMIT_REF_SLUG-$REVISION/ | sed s/value:\ production/value:\ test/ | kubectl apply -f -
```
