### ISSUE TITLE
migrations_path setting ignored when using multiple databases

### ISSUE THREAD

**Issue by madejejej** [rails/rails#39090]
#### Create a new rails app:
```
rails new rails-multidb-test
cd rails-multidb-test
```

#### Use the following db config (similar to [the official guides](https://guides.rubyonrails.org/active_record_multiple_databases.html#setting-up-your-application))

```
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  animals:
    <<: *default
    database: db/animals_development.sqlite3
    migrations_path: "db/animals_migrate"

test:
  primary:
    <<: *default
    database: db/test.sqlite3
  animals:
    <<: *default
    database: db/animals_test.sqlite3
    migrations_path: "db/animals_migrate"
```

#### Run migrations:

```
➜  rails-multidb-test git:(master) ✗ rails g migration create_users
Running via Spring preloader in process 71027
      invoke  active_record
      create    db/migrate/20200430114933_create_users.rb
➜  rails-multidb-test git:(master) ✗ rails g migration create_animals --database animals
Running via Spring preloader in process 71140
      invoke  active_record
      create    db/migrate/20200430114936_create_animals.rb
➜  rails-multidb-test git:(master) ✗ rails db:migrate:animals
== 20200430114933 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0021s
== 20200430114933 CreateUsers: migrated (0.0023s) =============================

== 20200430114936 CreateAnimals: migrating ====================================
-- create_table(:animals)
   -> 0.0017s
== 20200430114936 CreateAnimals: migrated (0.0018s) ===========================
```

### Expected behavior

- When I run `rails g migration create_animals --database animals`, the migration file should be created under `db/animals_migrate`
- When I run `rails db:migrate:animals`, only migrations that are present in `db/animals_migrate` should be run

### Actual behavior

`migrations_path` is ignored and both databases use the `db/migrate` folder for migrations.

### System configuration
**Rails version**: Rails 6.0.2.2
**Ruby version**: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
