### ISSUE TITLE
Multi-database shards (Multi-tenancy) issue with shared models

### ISSUE THREAD

**Issue by uxxman** [rails/rails#39226]
I am working on migrating a multi-tenant app to rails 6.1 database shards feature. Now in a typical multi-tenant app, there the 2 types of models,

* Shared Models (Common for all tenants)
* Tenant specific Models

Each tenant have their own sub-domain, so for each request inside an around_action filter, I check the domain and switch to the shard accordingly. Now within the actions, all tenant specific model queries are sent to the right database, but shared model queries raise **ActiveRecord::ConnectionNotEstablished**. Shouldn't shared models not be effected by shard switching? since both inherit from different base class. 

### Steps to reproduce
```yaml
# database.yml
development:
  primary:
    database: primary_db
  shard_default:
    database: shard_default_db
    migrations_paths: db/shard_migrate
  shard_one:
    database: shard_one_db
    migrations_paths: db/shard_migrate
  shard_two:
    database: shard_two_db
    migrations_paths: db/shard_migrate
```

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary }
end

class ShardApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to shards: {
    default: { writing: :shard_default },
    shard_one: { writing: :shard_one },
    shard_two: { writing: :shard_two }
  }
end

class User < ApplicationRecord
end

class Project < ShardApplicationRecord
end

# around_action
ActiveRecord::Base.connected_to(shard: :shard_one) { yield }

# Usage
Project.find(1) # Works and queries shard_one_db
User.find(1) # Raises ActiveRecord::ConnectionNotEstablished
```

### Expected behavior
Since the User model inherits from ApplicationRecord with single primary database connection, switching shards should not effect User model. Switching shards should only effect models that inherit from ShardApplicationRecord.

### Additional info
Everything works as expected when ApplicationRecord is written like this;

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to shards: {
    default: { writing: :primary },
    shard_one: { writing: :primary },
    shard_two: { writing: :primary }
  }
end
```
Is this expected to work? There are no docs to address this.

### System configuration
**Rails version**: 6.1.0.alpha

**Ruby version**: 2.7.0
