### ISSUE TITLE
ActiveRecord::DatabaseConfigurations::InvalidConfigurationError while setting up database

### ISSUE THREAD

**Issue by akankshajain9290** [rails/rails#39346]
### Steps to reproduce

I have following configuration settings in database.yml. It was working in expected manner in rails 5.2.4.2

```yaml
default: &default
  adapter: postgresql
  encoding: utf8
  template: template0
  pool: 10

docker: &docker
  <% unless ENV['DATABASE_HOST'].blank? %>
  username: postgres
  host: <%= ENV['DATABASE_HOST'] %>
  <% end %>

development:
  <<: *default
  <<: *docker
  database: platform_development

test:
  <<: *default
  <<: *docker
  database: platform_test<%= ENV['TEST_ENV_NUMBER'] %>
  <% unless ENV["DATABASE_URL_TEST"].blank? %>
  url: <%= ENV["DATABASE_URL_TEST"] %>
  <% end %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
```

While doing "bundle exec rails db:create" or "bundle exec rails reset" I am getting following error 
`ActiveRecord::DatabaseConfigurations::InvalidConfigurationError: '{ docker =>  }' is not a valid configuration. Expected '' to be a URL string or a Hash.
platform/config/environment.rb:5:in `<top (required)>'
bin/rails:4:in `<main>'
Tasks: TOP => db:reset => db:drop => db:load_config => environment`

### Expected behavior
Database should get reset successfully. 

### System configuration

**Rails version**: 6.0.2.2

**Ruby version**: 2.5.1
