### ISSUE TITLE
Adding retry policy to AzureStorageService

### ISSUE THREAD

**Issue by adamzolotarev** [rails/rails#39574]
### Steps to reproduce

When connection to Azure times out, the request simply fails with Faraday::TimeoutError. azure-storage-ruby implements retry filters - https://github.com/Azure/azure-storage-ruby/tree/0d3e5acf3327652fa2ffe1ed1df73b61a5a17c1e/common/lib/azure/storage/common/core/filter.

Would you consider adding new code to [AzureStorageService](https://github.com/rails/rails/blob/master/activestorage/lib/active_storage/service/azure_storage_service.rb#L16) constructor, so that we can pass a parameter in `storage.yml`, that would enable retry behavior.

For example, storage.yml:
```
azure:
  service: AzureStorage
  storage_account_name: ...
  storage_access_key: ...
  container: ...
  retry_policy: :exponential_retry_policy_filter
  retry_count: 3
  min_retry_interval: 10
  max_retry_interval: 90
```

Then in the AzureStorageService, we'd have something like this:
```
def initialize(storage_account_name:, storage_access_key:, container:, public: false, **options)
  @client = Azure::Storage::Blob::BlobService.create(storage_account_name: storage_account_name, storage_access_key: storage_access_key, **options)
  if (options[:retry_policy] == :exponential_retry_policy_filter)
      retry_count = options[:retry_count] || 3
      min_retry_interval = options[:min_retry_interval] || 10
      max_retry_interval = options[:max_retry_interval] || 90
      @client.with_filter(Azure::Storage::Common::Core::Filter::ExponentialRetryPolicyFilter.new(retry_count, min_retry_interval, max_retry_interval))
  end
  @signer = Azure::Storage::Common::Core::Auth::SharedAccessSignature.new(storage_account_name, storage_access_key)
  @container = container
  @public = public
end
```

### Expected behavior
ActiveStorage retries when download or upload fails

### Actual behavior
ActiveStorage fails with an error

### System configuration
**Rails version**: 5.2.4.3

**Ruby version**: 2.6

I'd like to open a PR for it if it's something you want to consider.
