### ISSUE TITLE
Multiple databases in RoR: Issue with migration applied to the wrong database

### ISSUE THREAD

**Issue by NelsonEU** [rails/rails#39590]
### Steps to reproduce
I want to add a secondary database to my RoR project, so I followed this: https://guides.rubyonrails.org/active_record_multiple_databases.html

So now I have two databases: `jobtitleio` & `profiles`
Here is my database.yml file: 

``` 
development:
  jobtitleio:
    <<: *default
    database: jobtitleio_development
  profiles:
    <<: *default
    database: profiles_development
    migrations_paths: db/profiles/migrate
```

I created a migration by running: `rails g migration CreateUsers url:text external_id:integer --database profiles` which created the migration in the right folder (db/profiles/migrate)

### Expected behavior
When running `rails db:migrate:profiles`, I expect my new table to be created in the `profiles` database (aka apply the migration to the specified database, in this case `profiles`)

### Actual behavior
It applies the migration to my other database (jobtitleio, the primary one), thus the table is added to the wrong database.

What did I do wrong ? 

### System configuration
**Rails version**: Rails 6.0.3.1

**Ruby version**: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
