### ISSUE TITLE
Can a replica be a master?

### ISSUE THREAD

**Issue by xxx44yyy** [rails/rails#39751]
### Steps to reproduce

I have two servers, two web applications, two databases (one master, the second replica). Sometimes, in different parts of the project, I sometimes see this error:

```
gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:650:in `execute_and_clear': 
Write query attempted while in readonly mode: DELETE FROM "books" WHERE "books"."author_id" = $1 (ActiveRecord::ReadOnlyError)
    from gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:111:in `exec_delete'
    from gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:180:in `delete'
    from gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `delete'
    from gems/activerecord-6.0.3.2/lib/active_record/relation.rb:587:in `delete_all'
    from gems/activerecord-6.0.3.2/lib/active_record/associations/has_many_association.rb:84:in `delete_count'
    from gems/activerecord-6.0.3.2/lib/active_record/associations/has_many_association.rb:91:in `delete_or_nullify_all_records'
    from gems/activerecord-6.0.3.2/lib/active_record/associations/collection_association.rb:165:in `delete_all'
    from gems/activerecord-6.0.3.2/lib/active_record/associations/has_many_association.rb:30:in `handle_dependency'
    from gems/activerecord-6.0.3.2/lib/active_record/associations/builder/association.rb:129:in `block in add_destroy_callbacks'
    from gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:428:in `instance_exec'
    from gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:428:in `block in make_lambda'
    from gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
```

The same method can sometimes work correctly, and sometimes with this error.

```
class Book < ApplicationRecord
  belongs_to :author
end
```

```
class Author < ApplicationRecord
  has_many :books
end
```

I can't understand why this is happening. I have an assumption that this is due to the fact that in the first server I use the **master as a replica**. Tell me, can it bring similar problems or can there be another reason?

First server (**master**):
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

production:
  primary:
    <<: *default
    database: db_name
    host: localhost                                                 <---- master locally
    port: 5432
    user: replicator_user
    password: replicator_user_pass_db

  primary_replica:
    <<: *default
    database: db_name
    host: localhost                                                 <---- replica use master
    port: 5432
    user: replicator_user
    password: replicator_user_pass_db
    replica: true
```

Second server (**replica**):
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

production:
  primary:
    <<: *default
    database: db_name
    host: ip_master_server
    port: 5432
    user: replicator_user
    password: replicator_user_pass_db

  primary_replica:
    <<: *default
    database: db_name
    host: localhost
    port: 5432
    user: replicator_user
    password: replicator_user_pass_db
    replica: true
```

### System configuration

Rails: 6.0.3.2 (both servers)
Ruby: 2.7.1  (both servers)
Postgres: 12 (both servers)
OS: Debian (both servers)
