### ISSUE TITLE
New Advisory Lock that opens a second connection causes bug in Postgres app

### ISSUE THREAD

**Issue by jules2689** [rails/rails#40029]
### Steps to reproduce
1. Use Rails after https://github.com/rails/rails/pull/38235 was merged
2. Use postgres 11, pg gem 1.1.4 (might be relevant, I'm unsure)
3. Run `bin/rails db:create db:migrate db:test:prepare`
4. Get error `ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "team_app" is being accessed by other users DETAIL:  There is 1 other session using the database.`

Note: I can only replicate on CI

### Expected behavior
1. Run `bin/rails db:create db:migrate db:test:prepare`
2. Succeeds

### Actual behavior

I was able to bisect the diff between Rails 6.0.2.2 and Rails 6.0.3 and determine that this PR (https://github.com/rails/rails/pull/38235) introduced a bug that causes migrations to fail in my app's CI.

When my CI system runs `bin/rails db:create db:migrate db:test:prepare`, it used to succeed with no problem in 6.0.2.2. Now it fails with:

```
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "team_app" is being accessed by other users
DETAIL:  There is 1 other session using the database.
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `async_exec'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/runner/work/team_app/team_app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
...
```

Oddly enough, I cannot replicate this locally, only on CI, so I'm at a loss of next steps.
The Postgres that I am using is the default postgres that comes with GitHub Actions.

### Workaround

Split up the command. Instead of  `bin/rails db:create db:migrate db:test:prepare`, run ` `bin/rails db:create db:migrate; bin/rails db:test:prepare`. This seems to clean up connections and we are all happy.

### System configuration

**Rails version**: bf11820213ba0f1a3b3ba556f1f8da2d132357a1
**Ruby version**: 2.6.6

**Comment by rafaelfranca** [comment]
cc @eileencodes

**Comment by eileencodes** [comment]
@jules2689 can you see if this is fixed on master by https://github.com/rails/rails/pull/39758? I forgot I backported the advisory locks to 6-0-stable and can backport that if it fixes it.

**Comment by jules2689** [comment]
Took a bit to figure out as https://github.com/rails/rails/issues/40031 got in my way, but I can confirm that this issue is not fixed on master.

**Comment by tgxworld** [comment]
@jules2689 Can I confirm that it is failing on `db:test:prepare` and if so do you have multiple databases in your database test config? Can you also try disabling advisory locks on your CI so that we can narrow down the issue further? You can disable it with 

```
test:
  adapter: postgresql
  advisory_locks: false
```

**Comment by jules2689** [comment]
> Can I confirm that it is failing on db:test:prepare

Correct!

> do you have multiple databases in your test config? 

I have 1 database setup

> Can you also try disabling advisory locks on your CI so that we can narrow down the issue further?

Adding `advisory_locks: false` fixes the problem.

**Comment by tgxworld** [comment]
Do you mind sharing your github action? I’m trying to replicate this on CI with a fresh Rails app. Thank you :)

**Comment by jules2689** [comment]
This should work!

```yml
name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    # Setup System
    - name: Set DISPLAY
      run: echo "::set-env name=DISPLAY:::99"
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: nanasess/setup-chromedriver@master
    - name: "Install Bundler"
      run: gem install bundler --no-document

    # Setup App
    - uses: actions/checkout@v1
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Get hash for the assets dir
      run: |
        shasum=$(find ./app/assets -type f -print0  | xargs -0 sha1sum)

    # Caching
    - uses: actions/cache@v1
      name: Yarn Cache
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-v2-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-v2-yarn-
    - uses: actions/cache@v1
      name: Bundler Cache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-v2-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-v2-gems-
    - uses: actions/cache@v1
      name: Packs Test Cache
      with:
        path: public/packs-test
        key: ${{ runner.os }}-v2-public-packs-test-${{ hashFiles('app/assets/**/*') }}-${{ hashFiles('app/javascripts/**/*') }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-v2-public-packs-test-
    - uses: actions/cache@v1
      name: Packs Cache
      with:
        path: public/packs
        key: ${{ runner.os }}-v2-public-packs-${{ hashFiles('app/assets/**/*') }}-${{ hashFiles('app/javascripts/**/*') }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-v2-public-packs-
    - uses: actions/cache@v1
      name: Tmp Assets Cache
      with:
        path: tmp/cache/assets
        key: ${{ runner.os }}-v2-tmp-assets-${{ hashFiles('app/assets/**/*') }}-${{ hashFiles('app/javascripts/**/*') }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-v2-tmp-assets-
    - uses: actions/cache@v1
      name: Tmp WebPacker Cache
      with:
        path: tmp/cache/webpacker
        key: ${{ runner.os }}-v2-tmp-webpacker-${{ hashFiles('app/assets/**/*') }}-${{ hashFiles('app/javascripts/**/*') }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-v2-tmp-webpacker-

    # Install Dependencies
    - name: Bundle Install
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_ENV }}
        POSTGRES_HOST: localhost
        POSTGRES_DB: team_app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
        CI: "1"
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Yarn Install
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_ENV }}
        POSTGRES_HOST: localhost
        POSTGRES_DB: team_app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
        CI: "1"
      run: |
        yarn install
    - name: DB Setup
      env:
        BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}
        RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_ENV }}
        POSTGRES_HOST: localhost
        POSTGRES_DB: team_app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
        CI: "1"
      run: |
        bin/rails db:create db:migrate
        bin/rails db:test:prepare
    - name: Precompile Assets
      run: bin/rails webpacker:compile

    # Run Tests
    - name: Run Tests
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_ENV }}
        POSTGRES_HOST: localhost
        POSTGRES_DB: team_app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        COVERAGE: "1"
        DISABLE_SPRING: "1"
        CI: "1"
      run: bin/rails test

```
