### ISSUE TITLE
Unable to use the public: true option for active storage s3

### ISSUE THREAD

**Issue by jamesmacwilliam** [rails/rails#40514]
### Steps to reproduce

configure active storage using the `public: true` option

config/storage.yml
```
amazon:
  service: S3
  public: true
  access_key_id: ...
  secret_access_key: ..
  region: ...
  bucket: ...
```

config/environments/development.rb
```
config.active_storage.service = :amazon
```
app/models/school.rb
```
has_attached :logo_image
```

within a rails console:
- given the logo_image has been previously attached to the model below, I run the following in a rails console
- given the s3 bucket has been edited to no longer block public access

then:

```
   School.first.logo_image.url
```

### Expected behavior
calling `.url` returns the public url to the s3 asset

### Actual behavior
calling `.url` raises the following error:

```
ArgumentError (Cannot load `Rails.config.active_storage.service`:)
invalid configuration option `:public'
```

### System configuration
**Rails version**: 6.0.3.4

**Ruby version**: 2.7.1p83

***aws-sdk-s3: 1.83.1
