### ISSUE TITLE
Missing service_name for Disk service

### ISSUE THREAD

**Issue by jankeesvw** [rails/rails#40898]
I'm upgrading our Rails 6.0 app to Rails 6.1 and I'm running into an ActiveStorage issue, when I run my specs I see this error:

```
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "service_name" violates not-null constraint
DETAIL:  Failing row contains (1, j97m6cy8m95lm372pk5lrdkoyydi, file_3.jpg, image/jpeg, {"identified":true}, 59799, iI/7LCZqHqSyOL+vPEJ7JQ==, 2020-12-21 09:19:12.757828, null).
```

This is my `storage.yml`

```yml
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
```

I found [the migration](https://github.com/rails/rails/blob/5cfd58bbfb8425ab1931c618d98b649bab059ce6/activestorage/db/update_migrate/20190112182829_add_service_name_to_active_storage_blobs.rb) that should add this column, there is this line in the migration which yields no result for me:

```ruby
>> configured_service = ActiveStorage::Blob.service.name
Traceback (most recent call last):
        1: from (irb):3
NoMethodError (undefined method `name' for #<ActiveStorage::Service::DiskService:0x00007f98af1ba2e8>)
```
