### ISSUE TITLE
Development enviroment connected to production database

### ISSUE THREAD

**Issue by Shalashtein** [rails/rails#40948]
After deploying my app to heroku, my local rails app, while running in its development enviroment is getting connected to the remote production database.

My database.yml

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: labbesne_development

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

```
I deployed a few days ago, and my app got slower on development, and I failed to debug the issue, I only noticed what was happening because my internet connection was disrupted for a few minutes while I was running `rails s`

### Steps to reproduce

```
ActiveRecord::Base.connection.current_database
```

### Expected behavior

`"labbesne_development"`

### Actual behavior
`""d33lm84fjpm05f""`

### System configuration
**Rails version**:
Rails 6.0.3.4

**Ruby version**:
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
