### ISSUE TITLE
Writing tests around horizontal sharding

### ISSUE THREAD

**Issue by uxxman** [rails/rails#41061]
First of all great work adding horizontal sharding and granular switching ❤️ 

I am developing and writing tests around horizontal sharding. For a real application the production/staging environment will have many shards while in development/testing just 1 or 2 are enough. If it works for them it should work for all. 

Sample database.yml

```yaml
test:
  primary:
    database: test_primary_database
  shard1:
    database: test_primary_shard_one

production:
  primary:
    database: my_primary_database
  shard1:
    database: my_primary_shard_one
  shard2:
    database: my_primary_shard_two
  shard3:
    database: my_primary_shard_three
  ... # so on...
```

And ApplicationRecord.rb

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to shards: {
    default: { writing: :primary },
    shard1: { writing: :primary_shard_one },
    shard2: { writing: :primary_shard_two },
    shard3: { writing: :primary_shard_three },
    # so on..
  }
end
```

### Issue
Running tests in test env raises **The `shard2` database is not configured for the `test` environment.**

### Question
Do we have to define all shards for tests as well? Or should we create environment specific ApplicationRecord class?

### Thoughts
Wouldn't it be better to only create connection_handlers for shards that have a matching database.yml entry and discard the rest?. Since we already raise an exception while switching to a non-existing shard **No connection pool for 'ApplicationRecord' found for the 'shard1' shard.**

### System configuration
**Rails version**: 6.1.1

**Ruby version**: 3.0.0
