### ISSUE TITLE
6.1 Active Record can't switch between local and remote DB

### ISSUE THREAD

**Issue by colmexdev** [rails/rails#41282]
I'm trying to connect to a local postgresql DB to read and write some data and to a remote mysql DB to strictly read from it. Access to my local DB works just fine, but it seems that host parameter for remote DB is not used.

### Steps to reproduce
According to the actual Active Record settings for multiple databases, I've followed thiese steps.

I've got my _database.yml_ file set like this:

```
production:
  primary:
    <<: *default
    database: <%= ENV['PROD_DB'] %>
    username: <%= ENV['PROD_USR'] %>
    password: <%= ENV['PROD_PWD'] %>
    port: <%= ENV['PROD_PORT'] %>
  pubs:
    adapter: mysql2
    encoding: utf8
    socket: /var/run/mysqld/mysqld.sock
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV["REM_USR"] %>
    password: <%= ENV["REM_PWD"] %>
    host: "<%= ENV["REM_HOST"] %>"
    database: <%= ENV["REM_DB"] %>
    port: <%= ENV["REM_PORT"] %>
```

And I'm seeting the connection to remote DB in a file named _pub.rb_ like this:

```
class Pub < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :pubs, reading: :pubs }
end
```

I've uncommented the following lines in _production.rb_:
```
  config.active_record.database_selector = { delay: 2.seconds }
  config.active_record.database_resolver = ActiveRecord::Middleware::DatabaseSelector::Resolver
  config.active_record.database_resolver_context = ActiveRecord::Middleware::DatabaseSelector::Resolver::Session
```

My local DB connection works great, but `Pub` is not connecting because `host` isn't set. It keeps throwing this error:

`ActionView::Template::Error (Access denied for user '<pub_username>'@'<localhost_IP>' (using password: YES)):`

So it seems that `host` is used as if it was local. I managed to make it work on Rails 5.2 with these settings:
- On _database.yml_:
```
pub:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock
  database: <%= ENV["REM_DB"] %>
  username: <%= ENV["REM_USR"] %>
  password: <%= ENV["REM_PWD"] %>
  host: <%= ENV["REM_HOST"] %>

production:
  <<: *default_pg
  database: <%= ENV["PROD_DB"] %>
  username: <%= ENV["PROD_USR"] %>
  password: <%= ENV["PROD_PWD"] %>
``` 

- On my model associated to remote DB:
```
class PubDB < ActiveRecord::Base
  establish_connection(:pub)
end

class Pub < PubDB
  self.table_name = "<db_table>"
end
```

But even this settings aren't working in 6.1. Before stating that maybe remote DB isn't accepting remote connections, I've made sure that I can connect remotely with the specified parameters and it's working fine on prompt and even on IRB (setting manually the params).

### Expected behavior
Connection to either local and remote databases should switch and work.

### Actual behavior
Connection to remote DB isn't working because it's setting `host` as local and not the one specified in _database.yml_.

### System configuration
**Rails version**: 6.1.1
**Ruby version**: 3.0.0
**Operative System**: Ubuntu 20.04

Thanks in advance for your help.
