### ISSUE TITLE
Confusing behavior while using connected_to block

### ISSUE THREAD

**Issue by phuongnd08** [rails/rails#41497]
### Steps to reproduce
I have a Rails app running Rails 6.0.2.2 which I noticed using very little resource on reading database and use all the resource on writing database. This is my database configuration:
```
production:
  writer:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  reader:
    <<: *default
    url: <%= ENV["DATABASE_READER_URL"] %>
    replica: true
```

My AR declaration:
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :writer, reading: :reader }
end

class AdminUser < ApplicationRecord
end
```

I run this code:

```
AdminUser.connected_to(role: :reading) do
AdminUser.count
end
```

### Expected behavior
The query is executed on the reading database

### Actual behavior
The query is executed on the writing database

### System configuration
**Rails version**: 6.0.2.2

**Ruby version**: 2.7.1
