### ISSUE TITLE
Multiple Database for Replica not working

### ISSUE THREAD

**Issue by coding-bunny** [rails/rails#41662]
### Steps to reproduce
1. Adjust your ApplicationRecord:

```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Rails 6 database configuration
  connects_to database: { writing: :primary, reading: :primary_replica }
end
```

2. Adjust your database.yml:
```
# Rails database.yml configuration file.
#
# This file defines the default settings to be able to run in development and test mode on a local system.
# Staging and Production environments however should be setting the DATABASE_URL environment variable to correctly
# configure the system for connecting to the correct database.
#
# See https://edgeguides.rubyonrails.org/configuring.html#configuring-a-database
#
# Because this application is running under Rails 6, we also add support for a primary and replica database.
# This allows the Rails framework to swap to different endpoints, and distribute the load of the application
# across the databases, and perform reads against the replica and writes against the primary.
#
# See https://edgeguides.rubyonrails.org/active_record_multiple_databases.html
#
default: &default
  username: 'root'
  password: ''
  host: 'localhost'
  adapter: "mysql2"
  encoding: "utf8mb4"
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: "project_development"
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    database: "project_development"
    replica: true

test:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: "project_development"
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    database: "project_development"
    replica: true

staging:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    replica: true

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    <<: *default
    url: <%= ENV['DATABASE_REPLICA_URL'] %>
    replica: true
```

Check your generated rake tasks with `bundle exec rails -T`:

```
rake db:create                          # Creates the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:create:all to create all databases in the config). Without RAILS_ENV or when RAI...
rake db:drop                            # Drops the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:drop:all to drop all databases in the config). Without RAILS_ENV or when RAILS_ENV...
rake db:environment:set                 # Set the environment value for the database
rake db:fixtures:load                   # Loads fixtures into the current environment's database
rake db:migrate                         # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)
rake db:migrate:down                    # Runs the "down" for a given migration VERSION
rake db:migrate:redo                    # Rolls back the database one migration and re-migrates up (options: STEP=x, VERSION=x)
rake db:migrate:status                  # Display status of migrations
rake db:migrate:up                      # Runs the "up" for a given migration VERSION
rake db:prepare                         # Runs setup if database does not exist, or runs migrations if it does
rake db:reset                           # Drops and recreates the database from db/schema.rb for the current environment and loads the seeds
rake db:rollback                        # Rolls the schema back to the previous version (specify steps w/ STEP=n)
rake db:schema:cache:clear              # Clears a db/schema_cache.yml file
rake db:schema:cache:dump               # Creates a db/schema_cache.yml file
rake db:schema:dump                     # Creates a database schema file (either db/schema.rb or db/structure.sql, depending on `config.active_record.schema_format`)
rake db:schema:load                     # Loads a database schema file (either db/schema.rb or db/structure.sql, depending on `config.active_record.schema_format`) into the database
rake db:seed                            # Loads the seed data from db/seeds.rb
rake db:seed:replant                    # Truncates tables of each database for current environment and loads the seeds
rake db:setup                           # Creates the database, loads the schema, and initializes with the seed data (use db:reset to also drop the database first)
rake db:structure:dump                  # Dumps the database structure to db/structure.sql
rake db:structure:load                  # Recreates the databases from the structure.sql file
rake db:version                         # Retrieves the current schema version number
```

### Expected behavior
I expect to see the required rake tasks per database

### Actual behavior
The tasks do not show up, and `rake db:migrate` fails because the replica database is in read-only mode.

### System configuration
**Rails version**: 6.1.3

**Ruby version**: 3.0.0
