### ISSUE TITLE
ActiveStorage direct upload with DigitalOcean Spaces failed after 5 minutes

### ISSUE THREAD

**Issue by gregogalante** [rails/rails#41694]
I'm tring to upload a big video 2GB with DirectUpload to AcitveStorage using DigitalOcean Spaces as service. After 5 minutes of upload i receive a network error in console and i found the file partially uploaded on the storage (1.8GB of 2GB).
With small videos the upload works without problem.

I have set the **config.active_storage.service_urls_expire_in** to 1.days. In fact the X-Amz-Expires value in the query string is correctly set to 86400. However the upload fail after 5 minutes.

### Steps to reproduce

Storage configuration:
```yml
production:
  service: S3
  access_key_id: <%= Rails.application.credentials.digitalocean_spaces[:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.digitalocean_spaces[:secret_access_key] %>
  endpoint: <%= Rails.application.credentials.digitalocean_spaces[:endpoint] %>
  bucket: <%= Rails.application.credentials.digitalocean_spaces[:bucket] %>
  region: <%= Rails.application.credentials.digitalocean_spaces[:region] %>
```

Javascript code:
```javascript
const upload = new DirectUpload(file, this.data.get('url'), {
        directUploadWillStoreFileWithXHR: (request) => {

          request.upload.addEventListener("progress", (e) => {
            const percentage = Math.round(e.loaded * 100 / e.total)
            console.log('%', percentage)
          })
        }
      })
      
      upload.create((error, blob) => {
        if (error) {
          console.log(error)
          return reject(error)
        }

        resolve()
 })
```

CORS configuration in DigitalOcean Spaces
<img width="561" alt="Schermata 2021-03-17 alle 18 15 56" src="https://user-images.githubusercontent.com/14337248/111509366-f30e5880-874c-11eb-814d-9676cf833ab7.png">

Request query string:
<img width="433" alt="Schermata 2021-03-17 alle 18 18 42" src="https://user-images.githubusercontent.com/14337248/111509677-42ed1f80-874d-11eb-9056-08a56bdbc6b9.png">

### Expected behavior

Valid upload.

### Actual behavior

Error after exaclty five minutes of upload.

### System configuration
**Rails version**: 2.7.2

**Ruby version**: 6.1.0
