### ISSUE TITLE
PostGIS adapter cannot create a new database

### ISSUE THREAD

**Issue by darkisa** [rails/rails#41836]
### Steps to reproduce
When trying to create a new database using `db:create`, if the adapter in the `database.yml` file is `postgis` then I get the following error:

```
backend % rails db:create
undefined local variable or method `configuration' for #<ActiveRecord::ConnectionAdapters::PostGIS::PostGISDatabaseTasks:0x00007f93461bb4e0>
Did you mean?  configuration_hash
Couldn't create 'development' database. Please check your configuration.
rails aborted!
NameError: undefined local variable or method `configuration' for #<ActiveRecord::ConnectionAdapters::PostGIS::PostGISDatabaseTasks:0x00007f93461bb4e0>
Did you mean?  configuration_hash

Tasks: TOP => db:create
(See full trace by running task with --trace)
```

However, if I change the adapter to `postgresql` then all works fine and as expected. Once the db is created I can then change the adapter back to `postgis` and all seems fine.

### Expected behavior
Ability to create a new database using `postgis` in the `database.yml` e.g.

```
default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development
```

### Actual behavior
When running `db:create` I get the following error:

`undefined local variable or method `configuration' for #<ActiveRecord::ConnectionAdapters::PostGIS::PostGISDatabaseTasks:0x00007f93461bb4e0>`

### System configuration
**Rails version**:  6.1.3

**Ruby version**: 2.7.2
