### ISSUE TITLE
Ruby on Rails error[BUG] Segmentation fault at 0x0000000000000110 ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin15]

### ISSUE THREAD

**Issue by kk-nair** [rails/rails#42110]
### Steps to reproduce
following tutorial 

   https://www.youtube.com/watch?v=nlKIJfv50U0

On this command
    `$ rails g scaffold Survey name:text laptop:binary os:text
    `
the following error was generated with the following instruction

```
[BUG] Segmentation fault at 0x0000000000000110
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin15]
```

```
-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports. 
```

### Expected behavior
should have created a scaffold with the above three fields which would facilitate migrating to db after this

### Actual behavior
got the above error
[ruby crash report_2021-04-30-194015.pdf](https://github.com/rails/rails/files/6405988/ruby.crash.report_2021-04-30-194015.pdf)

### System configuration
Rails 6.1.3.1 

ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin15]

I am using OS X EL Capitan 10.11.6

**Comment by meliborn** [comment]
Getting the same segmentation fault error. Might happens every hour. Unfortunately I can't provide the exact reproduction step.
![Снимок экрана 2021-04-30 в 18 43 55](https://user-images.githubusercontent.com/735194/116719672-05361480-a9e4-11eb-8e90-b8ca10c70e3b.png)

**Comment by jhawthorn** [comment]
This looks more likely to be a bug in Ruby or _possibly_ a C extension rather than in Rails. If you could file a bug on https://bugs.ruby-lang.org and include the entire error (especially including "C level backtrace information") and any other available information it would be appreciated ❤️.

**Comment by XrXr** [comment]
@meliborn In case you are still running into the crash, upgrading to Ruby 3.0.1 might fix it. The crash looks like the one from this [report](https://bugs.ruby-lang.org/issues/17536) and 3.0.1 includes a fix for it.

**Comment by PrathameshSurve** [comment]
# Resolving Segmentation Faults with PostgreSQL 12, Ruby 2.6.5, and Rails ^6.0.0 on Ubuntu 22.04

If you are using PostgreSQL 12, Ruby 2.6.5, and Rails ^6.0.0 on Ubuntu 22.04 and encounter a segmentation fault, this guide is for you.

## Issue
By default, Ubuntu 22.04 uses OpenSSL 3. However, your Ruby version requires OpenSSL 1.0.1 or 1.1.1, which Ubuntu does not natively support.

## Solution
There is no need to modify OpenSSL. Instead, follow these steps:

1. **Check your `database.yml` file:**

    ```yaml
    development:
      adapter: postgresql
      encoding: unicode
      host: 
      port: 5432
      pool: 5
      database: database_name
      username: username
      password: password

    test:
      adapter: postgresql
      encoding: unicode
      host: 
      port: 5432
      pool: 5
      database: database_name
      username: username
      password: password
    ```

2. **Modify the `host` field:**

    Replace `host: localhost` with `host:`, leaving it blank. This adjustment can help resolve the segmentation fault.

## Additional Help
If your environment doesn't allow you to install Ruby or you encounter other issues related to versions, feel free to reach out to me for personalized assistance.

---
For any further problems or personalized help, please contact me directly.
