### ISSUE TITLE
ActiveRecord::Base.connected_to doesn't use replica connection when used in rspec

### ISSUE THREAD

**Issue by SreekarReddyBollam** [rails/rails#42258]
### Steps to reproduce

database.yml
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
 test:
  main:
    <<: *default
    database: test_database
  main_replica:
    <<: *default
    host: <%= ENV["REPLICA_DB_HOST"] %>
    username: <%= ENV["REPLICA_DB_USER"] %>
    database: test_database
    replica: true 
```

application_record.rb
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :main, reading: :main_replica }
end
```

test_spec.rb
```ruby
it "should use read replica" do
  ActiveRecord::Base.connected_to(role: ActiveRecord::Base.reading_role) do
     expect(ApplicationRecord.connection_config.fetch(:replica, false)).to(be(true))
  end
end
```
### Expected behavior

Test should pass with `ApplicationRecord.connection_config.fetch(:replica, false)` evaluating to `true`

### Actual behavior

Test is failing with `ApplicationRecord.connection_config.fetch(:replica, false)` evaluating to `false`

### System configuration
**Rails version**:
`6.0.1`

**Ruby version**:
`2.6.5`

Note: Didn't face this problem in `RAILS_ENV=test rails console` or in development environment
