### ISSUE TITLE
Rails 6 could not load databse config.yml only on server ubuntu works locally on mac

### ISSUE THREAD

**Issue by pckrishnadas88** [rails/rails#42272]
### Steps to reproduce

Wen I try to execute `rake db:migrate` or start the server 

There is no syntax or tab issues as i validated it at https://yamlchecker.com/
Here is the link to SO question: https://stackoverflow.com/questions/65988776/rails-6-could-not-load-databse-config-yml

```yml
My database YML file:
# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: <%= ENV['DB'] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: backend_lpm_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV['MY_APP_DATABASE_URL'] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  <<: *default
  database: <%= ENV['DB'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['BACKEND_LPM_DATABASE_PASSWORD'] %>

```

### Expected behavior

Server must start or migrations must execute

### Actual behavior

rake aborted!
Cannot load database configuration:
YAML syntax error occurred while parsing /home/das/rail-apps/lpm-rails/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): found character that cannot start any token while scanning for the next token at line 17 column 13
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:24:in `rescue in parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:21:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:18:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3.2/lib/rails/application/configuration.rb:275:in `database_configuration'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/railtie.rb:221:in `block (2 levels) in <class:Railtie>'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/base.rb:15:in `<main>'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/railties/databases.rake:22:in `block (2 levels) in <main>'

Caused by:
Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 17 column 13
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:22:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:18:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3.2/lib/rails/application/configuration.rb:275:in `database_configuration'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/railtie.rb:221:in `block (2 levels) in <class:Railtie>'
das@ubuntu-s-1vcpu-1gb-blr1-01:~/rail-apps/lpm-rails$ rake db:migrate
rake aborted!
Cannot load database configuration:
YAML syntax error occurred while parsing /home/das/rail-apps/lpm-rails/config/database.yml. Please note that YAML must be consistently indented using spaces. Tabs are not allowed. Error: (<unknown>): found character that cannot start any token while scanning for the next token at line 17 column 13
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:24:in `rescue in parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:21:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:18:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3.2/lib/rails/application/configuration.rb:275:in `database_configuration'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/railtie.rb:221:in `block (2 levels) in <class:Railtie>'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/base.rb:15:in `<main>'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/railties/databases.rake:22:in `block (2 levels) in <main>'

Caused by:
Psych::SyntaxError: (<unknown>): found character that cannot start any token while scanning for the next token at line 17 column 13
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:22:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/configuration_file.rb:18:in `parse'
/usr/share/rvm/gems/ruby-3.0.0/gems/railties-6.1.3.2/lib/rails/application/configuration.rb:275:in `database_configuration'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/railtie.rb:221:in `block (2 levels) in <class:Railtie>'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/share/rvm/gems/ruby-3.0.0/gems/activesupport-6.1.3.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/base.rb:15:in `<main>'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/share/rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/share/rvm/gems/ruby-3.0.0/gems/activerecord-6.1.3.2/lib/active_record/railties/databases.rake:22:in `block (2 levels) in <main>'
Tasks: TOP => db:migrate => db:load_config
(See full trace by running task with --trace)

### System configuration
**Rails version**:
Rails 6.1.3.2
**Ruby version**:
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
