### ISSUE TITLE
Rails credentials no longer returns hash if the value of key is hash

### ISSUE THREAD

**Issue by ashiksp** [rails/rails#42351]
Recently we have allowed to access nested secrets by method calls by this [PR 42106](https://github.com/rails/rails/pull/42106).

It changed the structure of the result while accessing nested key when the the nested key value is another hash. Earlier it used to return the hash as a result and we could use it to assign or pass set of values to certain code block.

Eg:

```
mailer:
    smtp_settings:
      user_name: mailer_username
      password: mailer_password
      domain: domain
      address: smtp.mailer.com
      authentication: plain
      enable_starttls_auto: true
```

```
ActionMailer::Base.smtp_settings = Rails.application.credentials.mailer[:smtp_settings].symbolize_keys
```

After patching the [PR changes](https://github.com/rails/rails/pull/42106/files), it always gives ActiveSupport::InheritableOptions object instead of actual hash. This is because of [deep_transform](https://github.com/rails/rails/blob/58b46e9440f3460e93b8164205614e3ab85784da/activesupport/lib/active_support/encrypted_configuration.rb#L42) of hash keys introduced in the PR.

```
#<ActiveSupport::InheritableOptions {}>
```

### Steps to reproduce

[EncryptedConfigurationTest](https://github.com/rails/rails/blob/58b46e9440f3460e93b8164205614e3ab85784da/activesupport/test/encrypted_configuration_test.rb#L39)
```ruby
# Your reproduction script goes here

test "reading configuration by key file" do
    @credentials.write({ something: { good: true, bad: false, nested: { foo: "bar" } } }.to_yaml)

    ...

   assert_equal ({ good: true, bad: false, nested: { foo: "bar" } }), @credentials.something
  end
```

### Expected behavior
 Earlier the above test case passes, but it fails with latest main branch after the PR changes

### Actual behavior

The above test fails (Returns `#<ActiveSupport::InheritableOptions {}>`)

### System configuration
**Rails version**:
rails main branch
**Ruby version**:
2.7.0

cc: @ghiculescu  @rafaelfranca
