### ISSUE TITLE
`on_rescue ActiveStorage::FileNotFoundError, :delete`

### ISSUE THREAD

**Issue by dorianmariefr** [rails/rails#42923]
### Steps to reproduce

- have an app with active storage

### Expected behavior

- no errors from active storage

### Actual behavior

- `ActiveStorage::FileNotFoundError`s

### System configuration

**Rails version**: Rails 6.1.4

**Ruby version**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

I'm not sure which file I should delete and how to not receive this type of errors

**Comment by intrip** [comment]
Have you followed the [setup instructions](https://guides.rubyonrails.org/active_storage_overview.html#setup)?

If yes can you provide us a sample app and reproduction steps?

**Comment by dorianmariefr** [comment]
I'm not sure how to reproduce it, it just happens a lot on my production app, I'm using 

```
amazon:
  service: S3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>
  bucket: <%= ENV["AWS_BUCKET"] %>
```

```
config.active_storage.service = :amazon
```

and 

```
Rails.application.config.active_storage.resolve_model_to_route =
  :rails_storage_proxy
```
