### ISSUE TITLE
ArgumentError (unknown keyword: :iam) raised when using ActiveStorage to write to a GCS bucket with GKE Workload Identity

### ISSUE THREAD

**Issue by danielyazbek** [rails/rails#43108]
### Steps to reproduce
Configure ActveStorage with GKE Workload Identity (as documented [here](https://edgeguides.rubyonrails.org/active_storage_overview.html#google-cloud-storage-service)):
```yaml
google:
  service: GCS
  iam: true
  project: <%= ENV['ACTIVE_STORAGE_PROJECT'] %>
  bucket: <%= ENV['ACTIVE_STORAGE_BUCKET'] %>
```

Define a class:
```ruby
class Transaction < ApplicationRecord
  has_one_attached :csv_report
end
```

Attempt to write to ActiveStorage
```ruby
t = Transaction.create
t.csv_report.attach(io: StringIO.new("A,B,C"), filename: 'test.csv')
```

### Expected behavior
The file is written to the GCS bucket via ActiveStorage

### Actual behavior
Error raised:
```
gems/google-cloud-storage-1.34.1/lib/google/cloud/storage.rb:78:in `new': unknown keyword: :iam (ArgumentError)
```

### System configuration
**Rails version**: 6.1.4.1

**Ruby version**: 2.7.4

**google-cloud-storage gem version**: 1.34.1
