### ISSUE TITLE
Default Rails 7 setup with CSS processor breaks rich_text

### ISSUE THREAD

**Issue by rogiervandenberg** [rails/rails#43441]
### Steps to reproduce
Create a new project, using local Rails, with esbuild for javascript and Bootstrap for CSS, install Action Text and create a new model having `rich_text`, migrate and start the server:

```
rails/railties/exe/rails new example-project --dev -j esbuild  --css bootstrap && cd example-project && bin/rails action_text:install && rails g scaffold article title:string content:rich_text && rails db:migrate && ./bin/dev
```

### Expected behavior
When going to http://127.0.0.1:3000/articles/new I would expect to be able to change my Article content, using the Trix editor, with properly having setup the styles that are compatible with my chosen CSS processor.

### Actual behavior
The Trix editor seems broken, and only works when not using Bootstrap (or e.g. Bulma for that matter).

![ExampleProject](https://user-images.githubusercontent.com/3534391/137099648-62154e2b-0e3c-40ec-8234-2219e1ab7eb5.png)

### System configuration
**Rails version**:
`Rails 7.0.0.alpha2`

**Ruby version**:
`ruby 3.0.0-p0`

**Comment by jacobherrington** [comment]
I opened a PR to address this issue. I'm happy to hear any feedback you have on the implementation @rogiervandenberg.

**Comment by rogiervandenberg** [comment]
Seems to work _almost_ perfect. When checking with Bootstrap it's fine. But with tailwind it is not.

## Why?
The file `app/assets/stylesheets/application.tailwind.css` is populated with the new `@import "actiontext.css";` at the end, looking like this:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
@import "actiontext.css";
```

and then it does not work. But when I change the file like this (moving the added line to the top):

```css
@import "actiontext.css";
@tailwind base;
@tailwind components;
@tailwind utilities;
```

This way it works (for me at least)! 🎉 

So, apparently that line needs to be on top for Tailwind. But I'm not a CSS expert (and don't know anything about ordering here). This is just what occurs to me. ¯\_(ツ)_/¯

**Comment by EdwardBarton** [comment]
I faced this same issue and was able to resolve by simply running the build commands defined in `package.json`

```sh
yarn build
yarn build:css
```

**Comment by enowmbi** [comment]
I've tried all the above and none works 😞

**Comment by aroth** [comment]
Same.

**Comment by zahidalik** [comment]
I also tried the options. One option solved it in development but not in production.

**Comment by simonsapiel** [comment]
I have the same problem. The solution @rogiervandenberg suggested works for action text, but it in turn results in bugs with tailwind such as input fields not loading correctly. Also if you try to import custom fonts to tailwind as follows

```
@tailwind base;
@tailwind components;
@tailwind utilities;

@import url('https://fonts.googleapis.com/css2?family=Lexend:wght@200;300;400;500;600;700;800&display=swap');
@import 'actiontext.css';
```
the fonts are not loading.

The ordering

```
@import url('https://fonts.googleapis.com/css2?family=Lexend:wght@200;300;400;500;600;700;800&display=swap');
@import 'actiontext.css';

@tailwind base;
@tailwind components;
@tailwind utilities;
```
will work, but I would guess that this suggests that there is a problem with the tailwind imports.

**Comment by spaquet** [comment]
@simonsapiel and @rogiervandenberg ordering seems to matter. I'm like you asking myself why.
I know that when overriding some tailwind classes the order matters, but this is not the case.
The only thing I noticed is that when you have the @import at the bottom for the application.tailwind.css file, they end up in the middle of the final application.css file that is generated by `yarn build:css`. So could that be the issue?

**Comment by simonsapiel** [comment]
@spaquet This might be of help (https://stackoverflow.com/questions/9860763/css-import-and-the-order-of-it).

**Comment by enowmbi** [comment]
> @spaquet This might be of help (https://stackoverflow.com/questions/9860763/css-import-and-the-order-of-it).



> @simonsapiel and @rogiervandenberg ordering seems to matter. I'm like you asking myself why. I know that when overriding some tailwind classes the order matters, but this is not the case. The only thing I noticed is that when you have the @import at the bottom for the application.tailwind.css file, they end up in the middle of the final application.css file that is generated by `yarn build:css`. So could that be the issue?

I changed the order in application.bootstrap.css to no avail. What worked for me was using bootstrap via CDN

**Comment by zahidalik** [comment]
What really solved this issue for me is that I linked actiontext.css directly in application.html.erb.

**Comment by simonsapiel** [comment]
@zahidalik how did you accomplish this?

**Comment by zahidalik** [comment]
@simonsapiel I could do it by:
1. Adding in app/views/layouts/application.html.erb this line:
```
<%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
```
2. Adding in app/assets/config/manifest.js this line:
```
//= link actiontext.css
```

**Comment by Zicrou** [comment]
> <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

Really thanks for this answer it helped me a lot. Thanks Again.

**Comment by enowmbi** [comment]
Also noticed that when I install bootstrap adding `gem cssbundling-rails` to Gemfile and then running `rails css:install:bootstrap`, my links (e.g. link_to "Like", like_articles_path(article), data: {"turbo-method": :post} )now fire a get request and not a post request.

**Comment by joshuaneedham** [comment]
I managed to fix the above shared image issue by running `rails css:build` and I'm not sure if it had any effect but I usually run `rails javascript:build` along with the other just to be safe and it worked itself right out.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/63559/152625904-876d6e8a-c43e-4b79-8141-5cfdcf566056.png">

**Comment by enowmbi** [comment]
> I managed to fix the above shared image issue by running `rails css:build` and I'm not sure if it had any effect but I usually run `rails javascript:build` along with the other just to be safe and it worked itself right out. <img alt="image" width="601" src="https://user-images.githubusercontent.com/63559/152625904-876d6e8a-c43e-4b79-8141-5cfdcf566056.png">

ok. I'll give it a try. 👍🏾

**Comment by noguerajulioces** [comment]
Thanks @enowmbi . The `rails javascript:build` solved my problem.

**Comment by kat-mcbrooks** [comment]
> <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>

Thank you! Putting this directly into application.html.erb has been the only working solution for me. Using Rails 7, bootstrap 5, importmap.

**Comment by amree** [comment]
This worked for me:

```css
/* app/assets/stylesheets/application.tailwind.css */
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import "actiontext";
```

```css
/* app/assets/stylesheets/actiontext.css */
/*
 * Provides a drop-in pointer for the default Trix stylesheet that will format the toolbar and
 * the trix-editor content (whether displayed or under editing). Feel free to incorporate this
 * inclusion directly in any other asset bundle and remove this file.
 *
*/
@import "trix/dist/trix"; /* I'm importing it this way */

/*
 * We need to override trix.css’s image gallery styles to accommodate the
 * <action-text-attachment> element we wrap around attachments. Otherwise,
 * images in galleries will be squished by the max-width: 33%; rule.
*/
.trix-content .attachment-gallery > action-text-attachment,
.trix-content .attachment-gallery > .attachment {
  flex: 1 0 33%;
  padding: 0 0.5em;
  max-width: 33%;
}

.trix-content .attachment-gallery.attachment-gallery--2 > action-text-attachment,
.trix-content .attachment-gallery.attachment-gallery--2 > .attachment, .trix-content .attachment-gallery.attachment-gallery--4 > action-text-attachment,
.trix-content .attachment-gallery.attachment-gallery--4 > .attachment {
  flex-basis: 50%;
  max-width: 50%;
}

.trix-content action-text-attachment .attachment {
  padding: 0 !important;
  max-width: 100% !important;
}
```
