### ISSUE TITLE
Rails 7 assets:precompile webpack not found

### ISSUE THREAD

**Issue by jason-hobbs** [rails/rails#43906]
I have a Rails 6.1/Ruby 3.0.3 app where I ran bundle update rails, upgraded yarn versions, and ran rails app:update.
This worked fine locally with no issues.  I then pushed to production where one of the steps is 'rails assets:precompile'
This command fails with:

```
Compiling...
Compilation failed:
yarn run v1.22.17
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Command "webpack" not found.
```

If I revert back to Rails version 6.1.4.4 the command works perfectly fine and compiles assets.

**Comment by bradbajuz** [comment]
Having the same issue as well. Reran ```rails webpack:install```. Tried updating webpack packages using yarn. Nothing seems to work.

**Comment by Jentci** [comment]
revert back to Rails version 6.1.4.4 the command works perfectly fine and compiles assets.

**Comment by Jentci** [comment]
My Chromebook  is not factory  reset.  It's hacked. I do the ctrl alt shift r. It still won't go to reset . Only power wash and revert.

**Comment by bradbajuz** [comment]
If you're using heroku, I resolved this by ```heroku buildpacks:add --index 1 heroku/nodejs```

**Comment by jason-hobbs** [comment]
I am using docker so that won't work for me unfortunately.  It's just so strange that I can go back to 6 and everything works.

**Comment by bradbajuz** [comment]
yarn isn't included anymore in rails as a dependency per this [PR](https://github.com/rails/rails/pull/43641). I'm wondering if this change is causing this issue.

**Comment by ghiculescu** [comment]
Check if you aren't getting an error earlier in the heroku logs that looks like this

```
       error app@0.1.0: The engine "node" is incompatible with this module. Expected version "14.x". Got "16.13.1"
       error Found incompatible module.
```

**Comment by jason-hobbs** [comment]
Here is the Dockerfile I am using to create the image:
`FROM ruby:3.0.3

RUN apt-get update -yqq

# Install node from nodesource
RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash - \
	&& apt-get install -y nodejs

# Install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
	&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
	&& apt-get update -qq \
	&& apt-get install -y yarn

WORKDIR /usr/src/app
COPY Gemfile* /usr/src/app/
RUN gem update --system
RUN gem install bundler
RUN gem install openssl
RUN bundle install --jobs=4
RUN bundle package
RUN useradd --create-home -s /bin/bash -u 1000 1000
COPY . /usr/src/app/
RUN chown -R 1000:1000 /usr/src/app
USER 1000`

I then deploy it to kubernetes where I run the image.  The part that's failing is one of my init containers that runs:
`RAILS_ENV=production rails assets:precompile`

This container fails with the error message.

**Comment by cirdes** [comment]
@bradbajuz, I had the same problem here. It seems to be related to ```yarn install```  not been called https://github.com/heroku/heroku-buildpack-ruby/issues/1240#issuecomment-996885689

Instead of add node buildpack I just update the webpacker gem to 6.0.0.rc.6 and it was working again.
https://github.com/heroku/heroku-buildpack-ruby/issues/1240#issuecomment-996912552

Maybe upgrading webpacker solves docker as well.

**Comment by goandgit** [comment]
Has anyone gotten around this? I'm experiencing the same in my CI pipeline. Here's the script:

test-job:
    stage: test
    image: ruby:3.1
    services:
      - postgres:12.7
    variables:
      POSTGRES_USER: depot_postgresql
      POSTGRES_PASSWORD: depot_postgresql
      DB_USERNAME: depot_postgresql
      DB_PASSWORD: depot_postgresql
      DB_HOST: postgres
      RAILS_ENV: test
      # BUNDLE_PATH: vendor/bundle
    before_script:
      - gem update --system
    script:
      - apt-get update
      - apt-get --assume-yes install sudo
      - sudo apt install curl
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update
      - sudo apt-get install nodejs yarn
      - node -v
      - npm -v
      - yarn -v
      - gem install bundler -v 2.3.8
      # - bundle config set --local path 'vendor'
      - bundle install
      # - gem install webpacker
      - bundle exec ruby -v
      - bundle exec bundle version
      - bundle exec rails -v
      - export RAILS_ENV=development
      - bundle exec rails db:create db:schema:load --trace
      - bundle exec rails webpacker:compile
      - bundle exec rake assets:precompile
      - bundle exec rails test
      # - bundle exec rails test:system

**Comment by cirdes** [comment]
@goandgit , are you using webpacker@6.0.0.rc.6 ?

**Comment by goandgit** [comment]
@cirdes , package.json and Gemfile.lock state 5.4.3.

Deployment works on Heroku once I removed yarn (using npm only) and placed the nodejs buildpack in front of the ruby buildpack.

**Comment by cirdes** [comment]
@goandgit , in my case I was having this issue. I had to upgrade the webpacker gem to 6.0.0.rc.6 to make it work again.

**Comment by goandgit** [comment]
The upgrade to webpacker alone did not fix the issue for me so I reverted pack to the official release. As far as I can tell the crux of the issue is really the nodejs configuration. It does not appear to be a Rails issue (aside from the now legacy reliance on Node). I tried to migrate to importmaps to avoid all of this but I don't have time to roll my own Bootstrap Javascript so I reverted back. (otherwise it worked swimmingly)

My advice for anyone coming across this is to use a recent version of Node, (I'm using v16.14.0) make sure to add all of your packages via yarn so that package.json is correct and then run yarn install. Once I did this I was able to remove the Heroku buildpack and as of now it is working in my CI Pipeline (this also covers since deployment since it's part of my CI).

In case it is useful to anyone here is my package.json:
```
{
  "name": "top_secret",
  "private": true,
  "dependencies": {
    "@babel/core": "^7.8.0",
    "@hotwired/turbo-rails": "^7.1.1",
    "@rails/actioncable": "^7.0.2-3",
    "@rails/activestorage": "^7.0.2-3",
    "@rails/ujs": "^7.0.2-3",
    "@rails/webpacker": "5.4.3",
    "bootstrap": "3.4.1",
    "jquery": "3.5.1",
    "stimulus": "^2.0.0",
    "yarn": "^1.22.17"
  },
  "version": "0.9.0",
  "devDependencies": {
    "babel-jest": "^27.0.6",
    "babel-preset-env": "^1.7.0",
    "jest": "^27.0.6",
    "webpack-dev-server": "^3.11.0"
  },
  "scripts": {
    "test": "jest --passWithNoTests"
  },
  "jest": {
    "roots": [
      "test/javascript"
    ],
    "moduleDirectories": [
      "node_modules",
      "app/javascript"
    ]
  }
}
```
And here's the relevant portion of the CI YAML file
```
test-job:
    stage: test
    image: ruby:3.1
    services:
      - postgres:12.7
    variables:
      POSTGRES_USER: depot_postgresql
      POSTGRES_PASSWORD: depot_postgresql
      DB_USERNAME: depot_postgresql
      DB_PASSWORD: depot_postgresql
      DB_HOST: postgres
      RAILS_ENV: test
    script:
      - apt-get update
      - apt-get --assume-yes install sudo
      - sudo apt install curl
      - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt update
      - sudo apt install nodejs
      - npm install yarn -g
      - node -v
      - npm -v
      - yarn -v
      - gem install bundler -v 2.3.8
      - bundle install
      - ruby -v
      - bundle version
      - rails -v
      - rails db:create db:schema:load --trace
      - yarn
      - rake assets:precompile
      - rails test
```

Hopefully that helps someone. (sorry about all of the parentheses)
