### ISSUE TITLE
Flash error when in API mode

### ISSUE THREAD

**Issue by jcoyne** [rails/rails#43922]
In an API only app (no session store) I'm seeing an error because the session is a hash:
https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/middleware/flash.rb#L62

The Flash middleware is not in my stack, because I'm in API mode.
```
[Honeybadger::Rack::UserInformer, Honeybadger::Rack::UserFeedback, Honeybadger::Rack::ErrorNotifier,
 ActionDispatch::HostAuthorization, Rack::Sendfile, ActionDispatch::Static, ActionDispatch::Executor,
 ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, ActionDispatch::RequestId,
 RequestStore::Middleware, ActionDispatch::RemoteIp, Rails::Rack::Logger, ActionDispatch::ShowExceptions,
 ActionDispatch::DebugExceptions, ActionDispatch::ActionableExceptions, ActionDispatch::Callbacks, Rack::Head,
 Rack::ConditionalGet, Rack::ETag]
```

This used to work in rails 6.1, but starts failing after upgrading to 7.0.0

I believe this is because Metal calls commit_flash directly: https://github.com/rails/rails/blame/main/actionpack/lib/action_controller/metal.rb#L189

And the object returned by `Rack::Request#session` is a plain Hash

and this change did not account for this use case: https://github.com/rails/rails/commit/ca7c820c6962788d510c99a68e725de83cbe9cad

```
Failures:

  1) Update a workflow step for an object with error XML updates the step with error message/text
     Failure/Error: put "/dor/objects/#{druid}/workflows/#{wf.workflow}/#{wf.process}", params: process_xml

     NoMethodError:
       undefined method `enabled?' for {}:Hash
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/flash.rb:62:in `commit_flash'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb:189:in `dispatch'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_controller/metal.rb:251:in `dispatch'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb:32:in `serve'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb:50:in `block in serve'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb:32:in `each'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/routing/route_set.rb:850:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/callbacks.rb:99:in `run_callbacks'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/rack/logger.rb:36:in `call_app'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/rack/logger.rb:25:in `block in call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb:99:in `block in tagged'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb:37:in `tagged'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/tagged_logging.rb:99:in `tagged'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/rack/logger.rb:25:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/request_id.rb:26:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/static.rb:23:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/agent.rb:426:in `with_rack_env'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/error_notifier.rb:30:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/user_feedback.rb:31:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/honeybadger-4.9.0/lib/honeybadger/rack/user_informer.rb:21:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-7.0.0/lib/rails/engine.rb:530:in `call'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/testing/integration.rb:279:in `process'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/testing/integration.rb:34:in `put'
     # /Users/jcoyne85/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0/lib/action_dispatch/testing/integration.rb:370:in `put'
```
