### ISSUE TITLE
Clarification on how multiple databases feature works when switching roles

### ISSUE THREAD

**Issue by andrewonyango** [rails/rails#44166]
This is less a bug report, and more a docs-could-be-clearer-or-I'm-missing-something-and-I've-ran-out-of-search-keywords report, so apologies in advance

We are migrating away from [Octopus](https://github.com/thiagopradi/octopus) due to our Rails 6 upgrade and I've read the [docs](https://guides.rubyonrails.org/active_record_multiple_databases.html) and implemented a few changes without too much fuss on a relatively simple app, but then on our core app, I don't understand why I get ActiveRecord::RecordNotFound errors on some **tests**

I'm not in a position to produce a full example right now, but I think the code here is fairly straightforward, and if there's something I'm missing, someone who knows how the feature should work might be able to quickly see the problem

### Steps to reproduce

database.yml
```yaml
test:
  default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    reaping_frequency: 10
    database: core_test
    username:
    password:
    host: localhost

  primary:
    <<: *default

  replica:
    <<: *default # for the tests i'm just using the same database, roles, etc, although for this issue, I did try both a readonly user and the database owner
    replica: true
```
application_record.rb
```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  connects_to database: { writing: :primary, reading: :replica }
end
```
controller.rb
```ruby
puts "in controller action...(outside connected_to block)"
puts "company id: #{current_user.company_id}"
puts "company exists?: #{Company.exists?(current_user.company_id)}"  #=> true
puts "writing role: #{ActiveRecord::Base.connected_to?(role: :writing)}" #=> true
puts "reading role: #{ActiveRecord::Base.connected_to?(role: :reading)}" #=> false
puts Company.count

ActiveRecord::Base.connected_to(role: :reading) do
  puts "in controller action...(inside connected_to block)"
  puts Company.count # I expected this to equal the count above
  puts "company id: #{current_user.company_id}"
  puts "company exists?: #{Company.exists?(current_user.company_id)}"  #=> false (I expected this to be true)
  puts "writing role: #{ActiveRecord::Base.connected_to?(role: :writing)}" #=> false
  puts "reading role: #{ActiveRecord::Base.connected_to?(role: :reading)}" #=> true
```
results
```bash
in controller action...(outside connected_to block)
company id: 11588
company exists?: true
writing role: true
reading role: false
1915 # company count
in controller action...(inside connected_to block)
1914 # company count (less by 1)
company id: 11588
company exists?: false
writing role: false
reading role: true
```

### Expected behavior
I expected the query to return the user's company/the last company created. In general, since I'm using the same database, I expected queries immediately before entering the block/switching roles, and immediately after entering the block, to be consistent

### Actual behavior
Inside the block, the company isn't found, and it looks like there's one less record in that table. I tried setting a delay of 3 seconds (not shown in this code) just in case something was happening during the switch but there was no difference

### System configuration
**Rails 6.1.4.4**:

**Ruby 2.7.4p191**:

Thanks
