### ISSUE TITLE
Skip schema load when schema_dump is false

### ISSUE THREAD

**Issue by aliismayilov** [rails/rails#44281]
### Steps to reproduce
- rails new dummy
- disable schema dump

```diff
+++ b/config/database.yml
@@ -8,6 +8,7 @@ default: &default
   adapter: sqlite3
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   timeout: 5000
+  schema_dump: false
```
- rails db:create

### Expected behavior

```ruby
irb(main):001:0> ActiveRecord::Migration.maintain_test_schema!
nil
```

The above call should not do anything, since the schemas are disabled. The argument can be made that the above should not be called if the schema is disabled. This is a simplified example. The real issue is hard to deal with when opting for multiple databases, where schema dump is disabled for at least 1 database. Then the below error is happening.

### Actual behavior
The call is currently throwing an exception:

```ruby
irb(main):001:0> ActiveRecord::Migration.maintain_test_schema!
/Users/ali/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/activerecord-7.0.1/lib/active_record/tasks/database_tasks.rb:392:in `exist?': no implicit conversion of nil into String (TypeError)
```
### System configuration
**Rails version**: 7.0.1

**Ruby version**: 3.1.0

**Comment by fatkodima** [comment]
Sorry, I did not understand the issue and why are you calling `ActiveRecord::Migration.maintain_test_schema!` manually? Can you explain a bit more?

Because the fix is simple:
```diff
--- a/activerecord/lib/active_record/tasks/database_tasks.rb
+++ b/activerecord/lib/active_record/tasks/database_tasks.rb
@@ -389,7 +389,7 @@ def schema_up_to_date?(configuration, format = ActiveRecord.schema_format, file

         file ||= schema_dump_path(db_config)

-        return true unless File.exist?(file)
+        return true unless file && File.exist?(file)

         ActiveRecord::Base.establish_connection(db_config)
```

**Comment by aliismayilov** [comment]
> Sorry, I did not understand the issue and why are you calling `ActiveRecord::Migration.maintain_test_schema!` manually? Can you explain a bit more?


it's usually called as part of test frameworks (such as rails_helper generated by rspec-rails) to ensure that the database schema is up to date.

**Comment by fatkodima** [comment]
I see in the newly generated app in `test_helper.rb` this line `require "rails/test_help"` which then calls `ActiveRecord::Migration.maintain_test_schema!` down the road.

I have the following `database.yml`:
```yml
default: &default
  adapter: postgresql

development:
  primary:
    <<: *default
    database: blog_development
  animals:
    <<: *default
    database: animals_development
    migrations_paths: db/animals_migrate
    schema_dump: false
```

And when I run `rake test`, I do not see the mentioned error, everything works as expected. What I'm doing wrong?

**Comment by aliismayilov** [comment]
> I have the following database.yml:

Could you please confirm the result of `rake test` when you disable `schema_dump` for only one of the databases in the test environment as well?

**Comment by fatkodima** [comment]
Updated `database.yml` with:
```yml
test:
  primary:
    <<: *default
    database: blog_test
  animals:
    <<: *default
    # adapter: sqlite3
    # database: db/animals_development.sqlite3
    database: animals_test
    migrations_paths: db/animals_migrate
    schema_dump: false
```

Still works.
