### ISSUE TITLE
Configure ActiveStorage with AzureStorage given SAS token

### ISSUE THREAD

**Issue by BrandonBalala** [rails/rails#44590]
Based on ActiveStorage document, we're only presented with the option to pass a storage_access_key in `config/storage.yml`. 

e.g.
```
azuretest:
  service: AzureStorage
  storage_account_name: "[account_name]"
  storage_access_key: "[storage_access_key]"
  container: "[container_name]"
```

I've been provided a SAS (storage access signature), is there a way to configure storage such that I make use of the SAS token, or will I have to request a storage access key to make use of ActiveStorage with Azure

### System configuration
**Rails version**:  6.0.4.6

**Ruby version**: 2.6.5
