### ISSUE TITLE
Update module comment for ActiveRecord::Tasks::DatabaseTasks

### ISSUE THREAD

**Issue by pedz** [rails/rails#44801]
I could not get [this suggested line of code](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/tasks/database_tasks.rb#L37) to work.

### Steps to reproduce
Rakefile
```rake
require 'active_record'
include ActiveRecord::Tasks

DatabaseTasks.database_configuration = YAML.load_file('db/config.yml')
DatabaseTasks.db_dir = 'db'
DatabaseTasks.env = 'production'

DatabaseTasks.create_current('production')
```

db/config.yml
```yaml
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
```

Gemfile
```ruby
source 'https://rubygems.org'

gem 'activerecord'
gem 'rake'
```

### Expected behavior

`bundler exec rake --tasks` should list out the tasks

### Actual behavior

```
rake aborted!
Psych::BadAlias: Unknown alias: default
/Users/pedz/Source/find-duplicates/Rakefile:5:in `<top (required)>'
/Users/pedz/.config/rbenv/versions/3.1.1/bin/bundler:25:in `load'
/Users/pedz/.config/rbenv/versions/3.1.1/bin/bundler:25:in `<main>'
```

If `aliases: true` is added to the `YAML.load_file` call, then the error is:

```
rake aborted!
ActiveRecord::AdapterNotSpecified: The `production` database is not configured for the `default_env` environment.

  Available database configurations are:

  
/Users/pedz/Source/find-duplicates/Rakefile:10:in `<top (required)>'
/Users/pedz/.config/rbenv/versions/3.1.1/bin/bundler:25:in `load'
/Users/pedz/.config/rbenv/versions/3.1.1/bin/bundler:25:in `<main>'
(See full trace by running task with --trace)
```

### System configuration
**Rails version**:
activerecord (7.0.2.3)
**Ruby version**:
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-freebsd12.2]

Not related to Rails but currently `standalone-migrations` has an issue since `schema_file` was removed.

The best solution to using ActiveRecord in a stand alone application is this [answer](https://stackoverflow.com/a/26046277/341980) in StackOverflow.
