### ISSUE TITLE
Active Storage doesn't work with temporary credentials

### ISSUE THREAD

**Issue by ritaamritkar1212** [rails/rails#44880]
### Steps to reproduce
1. When have temporary credentials created for AWS, which expires in certain amount of time.
2. trying to use active_storage to save user avatar in s3 
3. User.rb has
   ` has_one_attached :avatar, dependent: :destroy`
4. storage.yml has

```
amazon:
       service: S3
       access_key_id: ENV["AWS_ACCESS_KEY_ID"]
       secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"]
       session_token: ENV["AWS_SESSION_TOKEN"]
       region: us-east-1
       bucket: ENV["BUCKET_NAME"]
```

5. in controller,
    `user.avatar.attach(io: File.open('public/test.jpeg'), filename: 'test.jpeg')`

This results in below error
 **The AWS Access Key Id you provided does not exist in our records. (Aws::S3::Errors::InvalidAccessKeyId)**

6. If we try to upload the image directly to s3 Bucket it gets uploaded
  ```
options = {
      region: ENV["AWS_REGION"],
      access_key_id: ENV["AWS_ACCESS_KEY_ID"],
      secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
      session_token: ENV["AWS_SECURITY_TOKEN"]
    }

    r = Aws::S3::Resource.new(options)
    obj = r.bucket(ENV["BUCKET_NAME"]).object('test.jpeg')
    obj.put(body: params[:avatar].to_io)
```

### Expected behavior
Image should have been uploaded in S3 bucket.

### Actual behavior
**The AWS Access Key Id you provided does not exist in our records. (Aws::S3::Errors::InvalidAccessKeyId)**

### System configuration
**Rails version**:
Rails 7.0.2.3
**Ruby version**:
ruby 3.1.1
