### ISSUE TITLE
Cannot add ActiveModel::Attribute::FromDatabase to permitted YAML safe load classes

### ISSUE THREAD

**Issue by stanhu** [rails/rails#45609]
### Steps to reproduce

We have some database entries serialized to YAML. For example:

```
---
:custom_message: Repository Download Started
:author_name: !ruby/object:DeployToken
  concise_attributes:
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: deploy_token_type
    value_before_type_cast: 1
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: id
    value_before_type_cast: 2
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: revoked
    value_before_type_cast: false
  - !ruby/object:ActiveModel::Attribute::FromDatabase
    name: read_repository
    value_before_type_cast: true
```

However, since the security release announced inhttps://rubyonrails.org/2022/7/12/Rails-Versions-7-0-3-1-6-1-6-1-6-0-5-1-and-5-2-8-1-have-been-released to address CVE-2022-32224, we cannot simply add `ActiveModel::Attribute::FromDatabase` to the permitted class list:

```ruby
(byebug) YAML.safe_load(payload, permitted_classes: [ActiveModel::Attribute::FromDatabase, Symbol, DeployToken], aliases: true)
*** NameError Exception: private constant ActiveModel::Attribute::FromDatabase referenced
```

```ruby
# Your reproduction script goes here
```

### Expected behavior

YAML loading should work. Should this constant no longer be private since it's been serialized to YAML?

### Actual behavior

YAML loading fails with:

```
*** NameError Exception: private constant ActiveModel::Attribute::FromDatabase referenced
```

### System configuration

**Rails version**:
v6.1.6.1

**Ruby version**:
v2.7.5
