### ISSUE TITLE
Configure a Base class per database for multi db setups

### ISSUE THREAD

**Issue by jwoodrow** [rails/rails#45841]
### Steps to reproduce

I don't know if this is the right place for this but I've been having issues with multi-db setups where the `schema_migrations` tabl for a database ends up filled in by another database's migration timestamps. This would result in permanent `Pending migrations` preventing code execution.

I've worked around it somehow by creating my own `ActiveRecord::Migration[6.1]` inherited classes to use for each type of migration a little like this

```ruby
class PrimaryMigration < ActiveRecord::Migration[6.1]
  def connection
    @connection ||= Primary::Base.establish_connection.connection
  end
end
```

But this implies manually modifying future migrations to use the right `Migration` class which does feel right.

By looking into the code it seems there might be the `connection_specification_name` in the [`schema_migration`](https://github.com/rails/rails/blob/d6973d50d01fe55e5c65368b92160708fb60a3da/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L195) method that might look like what I'm looking for but I have no idea if and how this can be configured 🤔 

Maybe an option like this might be interesting to have ?

```yaml
# database.yml
primary:
  url: some_url
  migrations_paths: db/migrate/primary
  base: 'Primary::Base'
secondary:
  url: some_other_url
  migrations_paths: db/migrate/secondary
  base: 'Secondary::Base'
tertiary:
  url: yet_another_other_url
  migrations_paths: db/migrate/tertiary
  base: 'Tertiary::Base'
```

### Expected behavior

`schema_migrations` are stored in the right database for each database

### Actual behavior

`schema_migrations` seem all jumbled up and maybe even ascii order dependent (with 2 databases ahoy/primary my ahoy migrations get run first but are saved in the `primary` database's `schema_migrations` table)

### System configuration
**Rails version**: 6.1.6.1

**Ruby version**: 3.0.4

**Comment by eileencodes** [comment]
Hey @jwoodrow this doesn't sound right. I think something is wrong with your setup. Can you create a new app that reproduces this bug? I can't figure out what's wrong based on the information here.

**Comment by eileencodes** [comment]
Actually this sounds like you don't have your base classes set up correctly. Do you have the appropriate abstract classes set up as documented in the guides? Your classes should look something like this:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary }
end

class Secondary::Base < ApplicationRecord
  self.abstract_class = true
  connects_to database: { writing: :secondary }
end

class Tertiary::Base < ApplicationRecord
  self.abstract_class = true
  connects_to database: { writing: :tertiary }
end
```

The migration paths also look incorrect, I highly doubt nesting migrations into the default directory works. It should be:

```
# database.yml
primary:
  url: some_url
  migrations_paths: db/migrate
secondary:
  url: some_other_url
  migrations_paths: db/migrate_secondary
tertiary:
  url: yet_another_other_url
  migrations_paths: db/migrate_tertiary
```

**Comment by jwoodrow** [comment]
I'm trying to reproduce on a new project since the issue is happening on our private repo but can't seem to get the behaviour happening again although I have things setup in the same manner

I have 3 base classes setup as such

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :secondary }
end

class Ahoy::Base < ApplicationRecord
  self.abstract_class = true
  connects_to database: { writing: :ahoy }
end

class Data::Base < ApplicationRecord
  self.abstract_class = true
  connects_to database: { writing: :data }
end
```

and then in the database.yml it's configured like this

```yaml
default: &default
  adapter: postgresql
  encoding: unicode

  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['RAILS_MAX_THREADS'] || 8 %>

  # https://devcenter.heroku.com/articles/postgres-logs-errors#ruby-activerecord-and-prepared-statements
  prepared_statements: false

default_primary: &default_primary
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  migrations_paths: 'db/migrate/primary'
  schema_search_path: 'public,heroku_ext'

default_primary_slave: &default_primary_slave
  <<: *default
  url: <%= ENV['SLAVE_DATABASE_URL'].presence || ENV['DATABASE_URL'] %>
  migrations_paths: "db/migrate/primary_slave" # Always empty !
  schema_search_path: 'public,heroku_ext'

default_ahoy: &default_ahoy
  <<: *default
  url: <%= ENV['AHOY_DATABASE_URL'].presence || ENV['DATABASE_URL'] %>
  migrations_paths: 'db/migrate/ahoy'
  schema_search_path: 'public,heroku_ext'

default_datateam: &default_datateam
  <<: *default
  url: <%= ENV['PATRYK_DATABASE_URL'].presence || ENV['DATABASE_URL'] %>
  migrations_paths: 'db/migrate/datateam'
  schema_search_path: 'public,heroku_ext'

development:
  primary:
    <<: *default_primary
  primary_slave:
    <<: *default_primary_slave
    url: <%= ENV['SLAVE_DATABASE_URL'].presence || ENV['DATABASE_URL'] %>
  ahoy:
    <<: *default_ahoy
    url: <%= ENV['AHOY_DATABASE_URL'] %>
  datateam:
    <<: *default_datateam
    url: <%= ENV['PATRYK_DATABASE_URL'].presence || ENV['DATABASE_URL'] %>
```

migrations work correctly too in the test project in which I'm attempting to recreate the issue (with the same timestamps 
on the migrations too) with nested folders for the migration folder structure
