### ISSUE TITLE
ActiveRecord::AdapterNotSpecified: The `primary_replica` database is not configured for the `staging` environment.

### ISSUE THREAD

**Issue by sajjadmurtaza** [rails/rails#46099]
### Steps to reproduce

I am implementing multiple-database in the rails application. Locally i was working fine. I merged and push my changes to staging and after that, i am getting

> ActiveRecord::AdapterNotSpecified: The `primary_replica` database is not configured for the `staging` environment.

I have `database.yml`

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1
  timeout: 5000
  username: <%= ENV['POSTGRES_USERNAME'] %>
  host: <%= ENV['POSTGRES_URL'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>


staging:
  <<: *default
  database: <%= ENV['POSTGRES_DB_NAME'] %>
  primary:
    host: <%= ENV['POSTGRES_URL'] %>
  primary_replica:
    host: <%= ENV['POSTGRES_READ_URL'] %>
    port: <%= ENV['POSTGRES_READ_PORT'] %>
    replica: true

```

```
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  connects_to database: { writing: :primary, reading: :primary_replica }
end
```

<img width="824" alt="Screenshot 2022-09-22 at 15 46 57" src="https://user-images.githubusercontent.com/8552702/191764285-03703033-d463-4f6c-b4f0-e27ba1bf5e39.png">

### System configuration
**Rails version**: 7.0.3

**Ruby version**: 2.7.1

**Comment by eileencodes** [comment]
Hey @sajjadmurtaza this issue tracker is for bugs in the framework. With all the issues that have been opened so far they're issues with your application. We don't have the bandwidth to debug applications. 

In this case you have a bug in your database configuration. You can't add the `default` alias in like this, it won't apply to the `primary` or `primary_replica`.

```
staging:
  <<: *default
  database: <%= ENV['POSTGRES_DB_NAME'] %>
  primary:
    host: <%= ENV['POSTGRES_URL'] %>
  primary_replica:
    host: <%= ENV['POSTGRES_READ_URL'] %>
    port: <%= ENV['POSTGRES_READ_PORT'] %>
    replica: true
```

You must include default in each like this:

```
staging:
  primary:
    <<: *default
    database: <%= ENV['POSTGRES_DB_NAME'] %>
    host: <%= ENV['POSTGRES_URL'] %>
  primary_replica:
    <<: *default
     database: <%= ENV['POSTGRES_DB_NAME'] %>
    host: <%= ENV['POSTGRES_READ_URL'] %>
    port: <%= ENV['POSTGRES_READ_PORT'] %>
    replica: true
```
