### ISSUE TITLE
Error when setting a wildcard cookie domain

### ISSUE THREAD

**Issue by heaven** [rails/rails#46713]
### Steps to reproduce
The following code in the controller makes the test fail
```ruby
cookies[:token] = {
  secure:   true,
  httponly: false,
  value:    @token,
  expires:  30.seconds.from_now,
  domain:   ".customdomain.com"
}
```

The test case is as follows (using the RSwag gem)
```ruby
path "/login" do
  post "Validates the token" do
    tags 'Login'
    security []

    parameter name: :data, in: :body, schema: {
      '$ref' => '#/components/schemas/login_data'
    }

    response '201', 'Created' do
      it 'returns a 201 response' do |example|
        host! "test.customdomain.com"
        https!

        expect_any_instance_of(Api::Cisco::V1::LoginsController).
          to receive(:public_key).and_return(public_key)

        submit_request(example.metadata)
        assert_response_matches_metadata(example.metadata)

        expect(response.cookies["token"].present?).to eq true
        expect(response.cookies["token"]).to eq admin.access_tokens.last.key
      end
    end
  end
end
```

### Expected behavior
The test should pass (and it does with ruby 2.7.4)

### Actual behavior
The test fails with an argument error after upgrading to 2.7.7

```
  1) Login API /login post Found returns a 201 response
     Failure/Error: submit_request(example.metadata)

     ArgumentError:
       invalid domain: ".customdomain.com"
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-2.2.4/lib/rack/mock.rb:239:in `new'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-2.2.4/lib/rack/mock.rb:239:in `block in parse_cookies_from_header'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-2.2.4/lib/rack/mock.rb:236:in `each'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-2.2.4/lib/rack/mock.rb:236:in `parse_cookies_from_header'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-2.2.4/lib/rack/mock.rb:187:in `initialize'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-test-2.0.2/lib/rack/test.rb:360:in `new'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-test-2.0.2/lib/rack/test.rb:360:in `process_request'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/gems/rack-test-2.0.2/lib/rack/test.rb:155:in `request'
     # /Users/heaven/.rvm/gems/ruby-2.7.7@qarib/bundler/gems/rswag-ad95f1098ad5/rswag-specs/lib/rswag/specs/example_helpers.rb:20:in `submit_request'
     # ./spec/integration/api/cisco/v1/logins_spec.rb:47:in `block (5 levels) in <top (required)>'
```

The problem is in the wildcard domain `.customdomain.com` I'm setting in the controller.

### System configuration
**Rails version**: 6.1.7
**Ruby version**: 2.7.7
