### ISSUE TITLE
Prepending any `after_` callback doesn't work correctly

### ISSUE THREAD

**Issue by ghiculescu** [rails/rails#47007]
### Steps to reproduce

While investigating https://github.com/rails/rails/pull/46992 I found more issues, which I want to verify if they are issues before proceeding. I wrote some test cases: https://github.com/rails/rails/compare/main...ghiculescu:rails:after-save-prepend

Here's one example:

```ruby
    # controller 
    class FooController
      after_action :one
      after_action :two
      prepend_after_action :three

      def one
        @values << "1"
      end

      def two
        @values << "2"
      end

      def three
        @values << "3"
      end

      def index
        @values = []
      end
    end

      # test
      test "after_action order is correct" do
        @controller.process(:index)
        assert_equal ["3", "2", "1"], @controller.instance_variable_get("@values")
      end
```

The order should be 3 (prepended, so runs first), then 2, then 1. 2 should run before 1 because `after_` callbacks run in reverse orders for reasons explained [here](https://github.com/rails/rails/issues/5464#issuecomment-5815903). But according to that comment you can use `prepend` to override this order.

### Expected behavior

All the tests should pass.

### Actual behavior

All the tests fail.

Model test:

```
CallbacksTest#test_complete_callback_chain [/Users/alex/Code/rails/activemodel/test/cases/callbacks_test.rb:60]:
--- expected
+++ actual
@@ -1 +1 @@
-[:before_create_prepend, :before_create, :before_around_create, :create, :after_around_create, :after_create, :final_callback, :after_create_prepend]
+[:before_create_prepend, :before_create, :before_around_create, :create, :after_around_create, :after_create_prepend, :after_create, :final_callback]
```

Controller tests:

```
Failure:
AbstractController::Testing::TestCallbacks4#test_after_action_order_is_correct [/Users/alex/Code/rails/actionpack/test/abstract/callbacks_test.rb:154]:
Expected: ["3", "2", "1"]
  Actual: ["2", "1", "3"]

Failure:
AbstractController::Testing::TestCallbacks4#test_after_action_order_is_correct_with_subclass [/Users/alex/Code/rails/actionpack/test/abstract/callbacks_test.rb:160]:
Expected: ["4", "3", "2", "1"]
  Actual: ["4", "2", "1", "3"]
```

### System configuration
**Rails version**: `main`

**Ruby version**: 3.1.3
