### ISSUE TITLE
Database.yml doesn't allow sharing multiple/3-tier database options

### ISSUE THREAD

**Issue by jasonkarns** [rails/rails#47367]
### Steps to reproduce
1. rails new
2. convert config/database.yml to 3-tier config
3. convert special `shared` key to 3-tier config

Demo app here: https://github.com/jasonkarns/rails-shared-3-tier/blob/main/config/database.yml

### Expected behavior

Given a multiple-database rails app with 3-tier config, I would expect the `shared` stanza to support configuration options for each of the multiple databases, rather then applying the same shared config to _all_ databases.

I believe my expected behavior matches the expected behavior from the initial bug: https://github.com/rails/rails/issues/45299 as the sample config in that demo app also uses 3-tier config under the `shared` key: https://github.com/jandudulski/shared_migrations_bug/blob/bd607f308241fceeeb75d3f01f3b2f2ebe3cf901/config/database.yml

### Actual behavior

If the `shared` key is moved to a 3-tier config, then rails fails to load due to missing db adpater option.

```
/opt/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4.2/lib/active_record/connection_adapters/abstract/connection_handler.rb:261:in `resolve_pool_config': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
```

### System configuration
**Rails version**: Rails 7.0.4.2
**Ruby version**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin22]

### Rationale

**shared config merged to each db** (currently supported behavior)
```yml
# this works
shared:
  adapter: sqlite

development:
  primary:
    database: db/development.sqlite3
  replica:
    database: db/development-replica.sqlite3
```

This is the current behavior and means that the `shared` properties are merged into _each_ database across all environments. This means that the only options that may be extracted to 'shared' must be the same for primaries and replicas (or however many databases the app is connecting to).

**shared config merged to each environment**  (expected behavior)
```yml
# this does not work
shared:
  primary:
    adapter: sqlite
  replica:
    adapter: mysql

development:
  primary:
    database: db/development.sqlite3
  replica:
    database: replica_development
```

In this configuration, the `shared` is merged only to the top-level environment properties (but "deeply"). I would posit that this merging behavior is more useful. I have only used the multiple-databases feature of Rails in 2 different apps but my experience was the same with both apps: the multiple databases had very few options that were shared across databases. The names were different, the pooling was different, the login credentials were different (to wit, in the most common "read replica" scenario, the credentials would not be shared), even the adapters were different in one of the apps.

In contrast, the configuration options for a given database _across environments_ was identical: same adapter, same pool config, same migrations path, same use_metadata_table setting, same encoding. With so much of the configuration identical, it seemed a perfect case for `shared`. However, we were unable to use it because these options were different _per database_ (even though for a given database, they were the same across environments).

I realize the documentation doesn't actually state how the `shared` key is intended to operate with a 3-tier config. So it's possible this technically qualifies as a feature request instead of a bug. However, given that I presume the purpose of `shared` is to be able to avoid needing yaml anchor syntax, I propose that supporting 3-tier config with `shared` furthers that goal.

pinging @jandudulski as reporter of related [issue](https://github.com/rails/rails/issues/45299)

**Comment by eileencodes** [comment]
Can you paste what configurations you get and what configurations you expect? It would be easier than me having to clone the app and then get only be able to see what you get.

**Comment by jasonkarns** [comment]
Given `config/database.yml`:

```yml
shared:
  one:
    migrations_paths: "db/one"
  two:
    migrations_paths: "db/two"

development:
  one:
    adapter: sqlite3
    database: db/one.sqlite3
  two:
    adapter: sqlite3
    database: db/two.sqlite3
```

Expected `ActiveRecord::Base.configurations.configs_for(env_name: 'development')`:
```yml
one:
  adapter: sqlite3
  database: db/one.sqlite3
  migrations_paths: db/one
two:
  adapter: sqlite3
  database: db/two.sqlite3
  migrations_paths: db/two
```

Actual `ActiveRecord::Base.configurations.configs_for(env_name: 'development')`:
```yml
one:
  adapter: sqlite3
  database: db/one.sqlite3
  one:
    migrations_paths: db/one
  two:
    migrations_paths: db/two
two:
  adapter: sqlite3
  database: db/two.sqlite3
  one:
    migrations_paths: db/one
  two:
    migrations_paths: db/two
```

This example demonstrates the expected and actual configuration results. However, this example does not generate the `ActiveRecord::AdapterNotSpecified` error as the OP example does. (Because in this example, the adapter is explicitly listed under the development environment, instead of under the `shared` mapping.)
