### ISSUE TITLE
Active record not working properly locally with docker ( undefined method `body' for #<Rack::Files::Iterator )

### ISSUE THREAD

**Issue by parkournick2** [rails/rails#47835]
### Steps to reproduce

```ruby
# Your reproduction script goes here
```

### Expected behavior

Files should be correctly exposed by active record

### Actual behavior

When I try to access a link to a file in the active record locally, I can't download that file, this error only happens locally, not in production.

We ran our rails project using docker compose, but if the problem was docker compose then it would give the same error in production, wouldn't it?

![image](https://user-images.githubusercontent.com/61525227/229169109-deb87dcf-25ea-42f5-a144-44890f592745.png)

```
NoMethodError (undefined method `body' for #<Rack::Files::Iterator:0x00007f29e43b4d80 @path="/app/storage/ba/em/baemxcgy086vcgbgk6azyv11otxv", @ranges=[0..98186709], @options={:mime_type=>"text/plain", :size=>98186710}>

       @stream.body
              ^^^^^):
```

this is my storage.yml
```yml
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
amazon:
  service: S3
  access_key_id: <%= ENV["AWS_STORAGE_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_STORAGE_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["AWS_STORAGE_BUCKET"] %>
  region: <%= ENV["AWS_STORAGE_REGION"] %>
```

storage folder permissions
```bash
nicolas@nicolas:~/my-project$ sudo ls -l storage/
total 68
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 18:38 0g
drwxr-xr-x 3 nicolas nicolas 4096 mar 31 12:33 1o
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 18:35 1w
drw-rw-rw- 3 nicolas nicolas 4096 mar 31 11:57 38
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:08 9h
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:07 9x
drwxr-xr-x 3 nicolas nicolas 4096 mar 31 12:31 ba
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:15 bj
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 18:35 bm
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 18:35 ck
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:07 fy
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:07 ha
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:08 ob
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:09 xv
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:11 y3
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 18:02 yk
drw-rw-rw- 3 nicolas nicolas 4096 mar 30 17:19 yt
```

Dockerfile
```Dockerfile
# Dockerfile development version
FROM ruby:3.1.2-bullseye

# Install Postgresql 14
RUN apt-get update -y
RUN apt install curl ca-certificates gnupg libzmq5-dev -y
RUN curl https://www.postgresql.org/media/keys/ACCC4CF8.asc \
          | gpg --dearmor \
          | tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
RUN sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" > /etc/apt/sources.list.d/postgresql.list'
RUN apt update
RUN apt-get -y install postgresql-14

# Install node
RUN curl -sL https://deb.nodesource.com/setup_16.x -o /tmp/nodesource_setup.sh
RUN bash /tmp/nodesource_setup.sh
RUN apt install nodejs

# Skip installing gem documentation
RUN set -eux; \
	mkdir -p /usr/local/etc; \
	{ \
		echo 'install: --no-document'; \
		echo 'update: --no-document'; \
	} >> /usr/local/etc/gemrc

# Install gems
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN gem install bundler
RUN mkdir -p vendor/cache
ARG BUNDLE_WITHOUT=development:test
RUN bundle config set without "$BUNDLE_WITHOUT"
RUN bundle check || bundle install --jobs $(nproc)
COPY . ./ 

# Start server
EXPOSE 3000
ENTRYPOINT ["/app/bin/docker-entrypoint.sh"]

CMD ["bin/rails", "server", "-b", "0.0.0.0"]

```

docker-compose.yml
```yml
version: "3.9"

services:

  postgres:
    mem_limit: ${POSTGRES_CONTAINER_RAM_LIMIT:-0}
    image: postgres:14.2
    environment:
      POSTGRES_USER: nothing
      POSTGRES_PASSWORD: nothing
    ports: 
      - '5433:5432'
    volumes:
      - myApp-postgres:/var/lib/postgresql/data
      - .:/app
    profiles: ["dev"]
    env_file:
      - .env
      - .env.local

  redis:
    mem_limit: ${REDIS_CONTAINER_RAM_LIMIT:-0}
    image: redis:7.0
    ports:
      - '6380:6380'
    volumes:
      - .:/app
      - myApp-redis:/var/lib/redis/data
    command: redis-server --port 6380
    profiles: ["dev"]
    env_file:
      - .env
      - .env.local

  myApp:
    mem_limit: ${DEV_API_CONTAINER_RAM_LIMIT:-0}
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        BUNDLE_WITHOUT: ''
    volumes:
      - .:/app
      - gem_cache:/vendor/bundle/gems
    links:
      - postgres
      - redis
    ports:
      # Rails Port
      - '3000:3000'
      # Debugger port
      - '12345:12345'
    environment:
      - DATABASE_URL=postgresql://myApp:myApp@postgres:5432/myApp?encoding=utf8&pool=5&timeout=5000
      - REDIS_URL=redis://redis:6380/0
    env_file:
      - .env.local
      - .env
    profiles: ["dev"]

  sidekiq:
    mem_limit: ${DEV_WORKER_CONTAINER_RAM_LIMIT:-0}
    build:
      context: .
      args:
        BUNDLE_WITHOUT: ''
    command: bundle exec sidekiq 
    volumes:
      - .:/app
    links:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://myApp:myApp@postgres:5432/myApp?encoding=utf8&pool=5&timeout=5000
      - REDIS_URL=redis://redis:6380/0
    env_file:
      - .env
      - .env.local
    profiles: ["dev"]

  api:
    mem_limit: ${CONTAINER_RAM_LIMIT:-0}
    stdin_open: true
    tty: true
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '80:3000'
    env_file:
      - .env
    profiles: ["api"]

  worker:
    mem_limit: ${CONTAINER_RAM_LIMIT:-0}
    build:
      context: .
    command: bundle exec sidekiq 
    volumes:
      - .:/app
    env_file:
      - .env
    profiles: ["worker"]

volumes:
  yuri-postgres:
  yuri-redis:
  gem_cache:
```

### System configuration
**Rails version**:ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Ruby version**:Rails 7.0.4
