### ISSUE TITLE
Transactional behavior is inconsistent when replica DB is configured

### ISSUE THREAD

**Issue by kawahara** [rails/rails#48020]
### Steps to reproduce

Hello. When I am setting up replica in my database, the transaction behavior is different between the first query and the second and subsequent queries.

Rails version: 7.0.4.3, 6.1.7.3 
MySQL 8.0.32

make blank application

```
rails new sample
```

make database configuration

```yaml:config/database.yml
default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_bin
  username: <%= ENV['DB_USERNAME']||'root' %>
  password: <%= ENV['DB_PASSWORD']||'' %>
  host:     <%= ENV['DB_HOSTNAME']||'127.0.0.1' %>
  port:     <%= ENV['DB_PORT']||'3306' %>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  reconnect: true
  variables:
    sql_mode: STRICT_ALL_TABLES

development:
  primary:
    <<: *default
    database:  <%= ENV['DB_NAME']||'sample_development' %>
    port: <%= ENV['DB_PORT']||'3306' %>
  primary_replica:
    <<: *default
    database:  <%= ENV['DB_NAME']||'sample_development' %>
    port: <%= ENV['DB_PORT']||'3306' %>
    replica: true
```

Add replica configuration to ApplicationRecord.

```ruby
connects_to database: { writing: :primary, reading: :primary_replica }
```

Add sample model.

```
bundle exec rails g model Parameter name:string value:string
bundle exec rails db:migrate
```

Create multi_db configuration. (for Rails7. If Rails6, create configuration manually.)

```
bundle exec rails g active_record:multi_db
```

Change configuration for `config/initilizers/multi_db.rb`

```ruby
Rails.application.configure do
  config.active_record.database_selector = { delay: 2.seconds }
  config.active_record.database_resolver = ActiveRecord::Middleware::DatabaseSelector::Resolver
  config.active_record.database_resolver_context = ActiveRecord::Middleware::DatabaseSelector::Resolver::Session
end
```

And enter to console.

```
bundle exec rails c
```

First, execute transaction. I hope this transaction will be rollback.

```
ActiveRecord::Base.transaction { p = Parameter.first; Parameter.create!(name: p&.name || 'hello', value: p&.value || 'world'); raise RuntimeError  }
```

However, the transaction was committed.

```
 Parameter Load (0.2ms)  SELECT `parameters`.* FROM `parameters` ORDER BY `parameters`.`id` ASC LIMIT 1
  TRANSACTION (0.2ms)  BEGIN
  Parameter Create (0.3ms)  INSERT INTO `parameters` (`name`, `value`, `created_at`, `updated_at`) VALUES ('hello', 'world', '2023-04-12 00:20:20.709377', '2023-04-12 00:20:20.709377')
  TRANSACTION (0.5ms)  COMMIT
(irb):16:in `block (2 levels) in <main>': RuntimeError (RuntimeError)
```

One more.

```
ActiveRecord::Base.transaction { p = Parameter.first; Parameter.create!(name: p&.name || 'hello', value: p&.value || 'world'); raise RuntimeError  }
```

This time, it rolled back as expected.

```
  TRANSACTION (0.4ms)  BEGIN
  Parameter Load (0.4ms)  SELECT `parameters`.* FROM `parameters` ORDER BY `parameters`.`id` ASC LIMIT 1
  Parameter Create (0.3ms)  INSERT INTO `parameters` (`name`, `value`, `created_at`, `updated_at`) VALUES ('hello', 'world', '2023-04-12 00:20:47.280792', '2023-04-12 00:20:47.280792')
  TRANSACTION (0.8ms)  ROLLBACK
(irb):18:in `block (2 levels) in <main>': RuntimeError (RuntimeError)
```

After this, the transaction will work as expected, but if `reload!` is executed, the next transaction will not work as expected.

### Expected behavior

I expect a consistent rollback to take place.

### Actual behavior

Transaction not rolled back due to execution timing.

### System configuration
**Rails version**:

7.0.4.3, 6.1.7.3 

**Ruby version**:

3.1.2

**MySQL version**:

8.0.32
