### ISSUE TITLE
Rails 7.0.3 & 7.0.4 pool_config error only in test environment

### ISSUE THREAD

**Issue by aksharj** [rails/rails#48481]
Hi,

I am on `Rails 7.0.3 & ruby 2.7.4p191` and have the following model definition

```
class ExternalRecord < ApplicationRecord
  self.abstract_class = true
  #establish_connection :main_red
  connects_to database: {
    main_red: :main_red,
    main_green: :main_green,
    main_blue: :main_blue
  }
end
```
I want to switch to reading from different databases based on few conditions, `this seems to be working very well on development environment`

i am using below code to switch to different databases
```
ActiveRecord::Base.connected_to(role: @main_db_name.to_sym) do
        result = Api::V2::Gom::T1::Platform.ransack(params[:q]).result.page(params[:page]).per(get_rows_limit)
      end
```
but when when i try to run rspec tests, i get an error

hers is the relevant code in the test

```

RSpec.shared_examples "NON EMPTY(US Horizontals)" do |end_point, token|
  it "/#{end_point}" do
    get("/api/v2/#{end_point}", params: {
      authentication_token: @token,
    })
    data = JSON.parse(response.body)
    expect(response.status).to eql(200)
    expect(data).to be_an_instance_of(Array)
    expect(data.count).to be > 0
  end
end
```

in the processing of the request is where i switch to different database based on the certain conditions,but this is generating the following error.

```
ArgumentError (The `pool_config` for the :reading_main_red role and :default shard was `nil`. Please check your configuration. If you want your writing role to be something other than `:writing` set `config.active_record.writing_role` in your application configuration. The same setting should be applied for the `reading_role` if applicable.):
```
database.yml as pool setting. it would be great if someone can point me in the right directions, could it be something related my rails configuration or may be something in rspec that i a missing?

please help.

Thanks.

**Comment by aksharj** [comment]
I just upgraded the application to Rails `7.0.4` but i see the same error.

```
ArgumentError (The `pool_config` for the :main_red role and :default shard was `nil`. Please check your configuration. If you want your writing role to be something other than `:writing` set `config.active_record.writing_role` in your application configuration. The same setting should be applied for the `reading_role` if applicable.):
```

**Comment by eileencodes** [comment]
We don't have the bandwidth for application support and this is not a bug. The error is telling you what is wrong with your application.

If you want to not have a role named `:writing` then you need to define `config.active_record.writing_role = :main_red` to the role you want to treat as writing. Because of transactions the test environment needs to share the connection between the roles, otherwise you will not be able to read data on different connections because the data is never committed to the db.

**Comment by aksharj** [comment]
Thanks @eileencodes so much for your reply. actually i just tried that way as well. 

added this to application.rb

```
    config.active_record.reading_role = :main_red
    config.active_record.writing_role = :main_red
 
```

but i still get an error


```
       The `pool_config` for the :writing role and :default shard was `nil`. Please check your configuration. If you want your writing role to be something other than `:writing` set `config.active_record.writing_role` in your application configuration. The same setting should be applied for the `reading_role` if applicable.
     Shared Example Group: "NON EMPTY(US Horizontals)" called from ./spec/api/v2/data_ultimate_spec.rb:224
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/connection_adapters/pool_manager.rb:42:in `set_pool_config'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:238:in `block (3 levels) in setup_shared_connection_pool'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:233:in `each'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:233:in `block (2 levels) in setup_shared_connection_pool'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:230:in `each'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:230:in `block in setup_shared_connection_pool'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:228:in `each'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:228:in `setup_shared_connection_pool'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:190:in `enlist_fixture_connections'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:130:in `setup_fixtures'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activerecord-7.0.4/lib/active_record/test_fixtures.rb:10:in `before_setup'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/actionpack-7.0.4/lib/action_dispatch/testing/integration.rb:331:in `before_setup'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/activejob-7.0.4/lib/active_job/test_helper.rb:48:in `before_setup'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-rails-5.0.3/lib/rspec/rails/adapters.rb:74:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # ./spec/spec_helper.rb:102:in `block (3 levels) in <top (required)>'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
     # /Users/global/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/forwardable.rb:235:in `cleaning'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:34:in `block (2 levels) in cleaning'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/database_cleaner-core-2.0.1/lib/database_cleaner/cleaners.rb:35:in `cleaning'
     # /Users/global/.rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/forwardable.rb:235:in `cleaning'
     # ./spec/spec_helper.rb:101:in `block (2 levels) in <top (required)>'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `block in run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `map'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:608:in `run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/global/.rvm/gems/ruby-2.7.4/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
     # /Users/global/.rvm/gems/ruby-2.7.4/bin/rspec:23:in `load'
     # /Users/global/.rvm/gems/ruby-2.7.4/bin/rspec:23:in `<main>'
     # /Users/global/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
     # /Users/global/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'

```

here is my database.yml for test section

```
test:
  primary:
    adapter: postgresql
    database: shaleprofile_test
    database: "<%= ENV['DATABASE_NAME'] %>"
    username: "<%= ENV['DATABASE_USERNAME'] %>"
    password: "<%= ENV['DATABASE_PASSWORD'] %>"
    host: "<%= ENV['DATABASE_HOST'] %>"
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  main_red:
    adapter: postgresql
    username: etl
    database: "<%= ENV['API_MAIN_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  main_blue:
    username: postgres
    adapter: postgresql
    database_tasks: false
    password: "password"
    host: "ip"
    database_tasks: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  main_green:
    adapter: "postgresql"
    username: "postgres"
    database: "<%= ENV['API_MAIN_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prediction_red:
    adapter: "postgresql"
    username: "postgres"
    database: "<%= ENV['API_PREDICTION_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prediction_blue:
    adapter: "postgresql"
    username: "postgres"
    database: "<%= ENV['API_PREDICTION_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prediction_green:
    adapter: "postgresql"
    username: "postgres"
    database: "<%= ENV['API_PREDICTION_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  onshore_red:
    adapter: "postgresql"
    username: "postgres"
    database: "<%= ENV['API_US_ONSHORE_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  onshore_blue:
    adapter: "postgresql"
    username: "postgres"
    database: "<%= ENV['API_US_ONSHORE_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  onshore_green:
    adapter: "postgresql"
    username: "postgres"
    database: "<%= ENV['API_US_ONSHORE_DATABASE_NAME'] %>"
    password: "<%= ENV['API_DATABASE_PASSWORD'] %>"
    host: "<%= ENV['API_DATABASE_HOST'] %>"
    database_tasks: false
    replica: false
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

```

this seems to be complaining about the `set_pool_config` method also i have not defined shards in my connects_to but i am using databases, still the error message seems to refer too default shard, do i need to set a default shard?


Sorry, i have tried multiple configuration but stuck, any help would be really great here.
