### ISSUE TITLE
Precompile fails when building from a Dockerfile

### ISSUE THREAD

**Issue by JoaoPedroAssis** [rails/rails#48581]
Hi guys! I am currently implementing ephemeral environments for the PRs in my repository, and I've made great progress using ArgoCD and ApplicationSets. However, I build these images in staging mode using a staging database defined in Rails Credentials and all the environments use the same database. In my pipeline I can create and destroy databases in my managed cluster (Digital Ocean psql), to make each environment have their own clean database to perform tests. 

When I tried to make the database connections available through env vars, the docker build failed in github actions in the precompile step. How can I docker build my application?

Pipeline flow:

PR open -> create database -> build image -> create k8s namespace and deployment -> seed
PR close -> delete k8s resources -> delete database

Is there an Rails way to accomplish this behaviour? thanks in advance!!

### Steps to reproduce

I changed the config from:

```yaml
# database.yml
production: &production
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.credentials.dig(:db, :name) %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  port: <%= Rails.application.credentials.dig(:db, :port) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
```
to: (other values such as user and password could benefit from the solution, but I can use a root user that doesnt need to be changed, since I am the only one with access to the db. But i'm open to other implementations.)

```yaml
# database.yml
production: &production
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("DB_NAME",  "default_db_name") %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  port: <%= Rails.application.credentials.dig(:db, :port) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
```
In my github actions build step I use the `build-and-push` action from Docker: (I already tried to pass the arguments via Docker, but it did not work)

```yaml
- name: Build and push ${{ matrix.target }}
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          target: ${{ matrix.target }}
          push: true
          tags: organization/projects:preview-${{ matrix.target }}-${{ steps.docker-tag.outputs.tag }}
          cache-from: type=gha,scope=build-${{ matrix.target }}
```
In my deploymeny, I defined the env, but it has never reached this point because the build fails. It is safe to assume that the kubernetes envs would not have any effect, since the final image needs them to be built. Reading online i saw that is possible that the application needs to be started in order to run `rails assets:precompile`, but I already tried the `initialize_on_precompile` option and it also didnt work

### Expected behavior

The build step should complete successfully and the image should accept Env Vars to set the database name

### Actual behavior

The build step logs an error:

```
#15 [builder 8/8] RUN rails assets:precompile
#15 2.471 To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
#15 3.297 rails aborted!
#15 3.297 KeyError: Cannot load database configuration:
#15 3.297 key not found: "DB_NAME"
#15 3.297 /app/config/database.yml:20:in `fetch'
#15 3.297 /app/config/database.yml:20:in `<main>'
#15 3.297 /app/app/models/application_record.rb:3:in `<main>'
#15 3.297 /app/app/models/user.rb:3:in `<main>'
#15 3.297 /app/config/routes.rb:4:in `block in <main>'
#15 3.297 /app/config/routes.rb:3:in `<main>'
#15 3.297 /app/config/environment.rb:7:in `<main>'
#15 3.297 
#15 3.297 Caused by:
#15 3.297 KeyError: key not found: "DB_NAME"
#15 3.297 /app/config/database.yml:20:in `fetch'
#15 3.297 /app/config/database.yml:20:in `<main>'
#15 3.297 /app/app/models/application_record.rb:3:in `<main>'
#15 3.297 /app/app/models/user.rb:3:in `<main>'
#15 3.297 /app/config/routes.rb:4:in `block in <main>'
#15 3.297 /app/config/routes.rb:3:in `<main>'
#15 3.297 /app/config/environment.rb:7:in `<main>'
#15 3.297 Tasks: TOP => environment
#15 3.297 (See full trace by running task with --trace)
#15 ERROR: process "/bin/sh -c rails assets:precompile" did not complete successfully: exit code: 1
------
 > [builder 8/8] RUN rails assets:precompile:
#15 3.297 KeyError: key not found: "DB_NAME"
#15 3.297 /app/config/database.yml:20:in `fetch'
#15 3.297 /app/config/database.yml:20:in `<main>'
#15 3.297 /app/app/models/application_record.rb:3:in `<main>'
#15 3.297 /app/app/models/user.rb:3:in `<main>'
#15 3.297 /app/config/routes.rb:4:in `block in <main>'
#15 3.297 /app/config/routes.rb:3:in `<main>'
#15 3.297 /app/config/environment.rb:7:in `<main>'
#15 3.297 Tasks: TOP => environment
#15 3.297 (See full trace by running task with --trace)
------
WARNING: local cache import at /tmp/.buildx-cache not found due to err: could not read /tmp/.buildx-cache/index.json: open /tmp/.buildx-cache/index.json: no such file or directory
Dockerfile:28
--------------------
  26 |     COPY . ./
  27 |     
  28 | >>> RUN rails assets:precompile
  29 |     
  30 |     FROM ruby:3.1.0-alpine as production
--------------------
ERROR: failed to solve: process "/bin/sh -c rails assets:precompile" did not complete successfully: exit code: 1
```

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.2.2
