### ISSUE TITLE
Rails 7.0.6 label_for translations not working in index views

### ISSUE THREAD

**Issue by augustosamame** [rails/rails#48629]
### Steps to reproduce

generate a new rails project
generate a scaffold: `rails g scaffold Post title body`
run migrations
modify i18n `en.yml` file with the following content:

```
en:
  hello: "Hello world"
  activerecord:
    attributes:
      post:
        title: "Title from i18n"
        body: "Body from i18n"
```

Replace the labels in both index and show views with `<%= label(:post, :body) %>`
Or you can even do the replace in the single `posts` shared partial

```
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong><%= label(:post, :body) %>:</strong>
    <%= post.body %>
  </p>

</div>

```

### Expected behavior

The body label should show 'Body from i18n' in all views

### Actual behavior

All views show correct translated label. Index view shows the incorrect (default) `body` label

I did some testing and all views are fine, but for some reason, index view fails.

### System configuration

**Rails version 7.0.6**:

**Ruby version 3.2.2**:
