### ISSUE TITLE
Add support to set `schema_migrations_table_name` and `internal_metadata_table_name` per connection on database.yml

### ISSUE THREAD

**Issue by sobrinho** [rails/rails#49271]
### Steps to reproduce

```yaml
staging:
  primary:
    adapter: postgresql
    encoding: unicode
    schema_migrations_table_name: public.schema_migrations
    internal_metadata_table_name: public.ar_internal_metadata
    url: <%= ENV["DATABASE_URL"] %>
  auditing: 
    adapter: postgresql
    encoding: unicode
    migrations_paths: db/auditing_migrate
    schema_migrations_table_name: auditing.schema_migrations
    internal_metadata_table_name: auditing.ar_internal_metadata
    url: <%= ENV["DATABASE_URL"] %>
  
production:
  primary:
    adapter: postgresql
    encoding: unicode
    schema_migrations_table_name: public.schema_migrations
    internal_metadata_table_name: public.ar_internal_metadata
    url: <%= ENV["DATABASE_URL"] %>
  auditing:
    adapter: postgresql
    encoding: unicode
    schema_migrations_table_name: auditing.schema_migrations
    internal_metadata_table_name: auditing.ar_internal_metadata
    migrations_paths: db/auditing_migrate
    url: <%= ENV["AUDITING_DATABASE_URL"] %>
```

### Expected behavior
While in production we need separate databases for scalability reasons, we don't have to for staging environments.

Since we are using separate migrations paths for each connection, we don't want clashing version numbers when sharing the databases.

---

In our specific use case, we have 5 separate staging environments and 3 different databases meaning 15 databases in total and each database laying around 260GB of storage.

By allowing separate schemas, we could reduce from 15 databases to 5 and cut costs.

We could even reduce to 1 database by using separate schemas at the primary as well like `edge_app`, `edge_auditing`, `staging_app`, `staging_auditing` and so on.

---

_We are on Heroku which limits the database to specifically one database but other vendors works as the same such as Render, CrunchyData and etc._

Using Heroku as example, we are saying that we could move from (listed price):

15 x 30 x 8 x $0.556 (Standard-3 / 512GB) => $6,004.80 * 12 => $72,057.60

To:

1 x 30 x 8 x $8.056 (Standard-9 / 4TB) => $1,933,44 * 12 => $23,201.28

_We could argue about moving to a vendor which supports separate databases in the same server but let's assume it's not that simple due to compliance, prepaid/upfront contracts, no devops team and etc._

### Actual behavior
Feature request, not implemented yet.

### System configuration
**Rails version**: 6.1.7.4

**Ruby version**: 2.7.6
