### ISSUE TITLE
Assets precompile not compile activetext.css

### ISSUE THREAD

**Issue by ItaloCobains** [rails/rails#51394]
### Steps to reproduce

```ruby
# Generate project with jumpstart template. https://github.com/excid3/jumpstart
rails new myapp -d postgresql -m https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb
# and try deploy this on the vps
```

### Expected behavior
I expect activetext.css works

### Actual behavior
I'm trying deploy this template on my vps with kamal. I have success but my activetext.css not have in /public/assets
visit the [website](https://trytech.app/posts/new) and open devtools in network bar.

![image](https://github.com/rails/rails/assets/83548040/3a357b5d-436e-48ad-aac6-c8b7f2ed7d12)

### System configuration
**Rails version**: "~> 7.1.3", ">= 7.1.3.2"

**Ruby version**: 3.3.0

**Comment by ItaloCobains** [comment]
i'm resolve this changing activetext.css to activetext.scss.

```scss
@import "trix/dist/trix";

.trix-content .attachment-gallery > action-text-attachment,
.trix-content .attachment-gallery > .attachment {
  flex: 1 0 33%;
  padding: 0 0.5em;
  max-width: 33%;
}
.trix-content .attachment-gallery.attachment-gallery--2 > action-text-attachment,
.trix-content .attachment-gallery.attachment-gallery--2 > .attachment, .trix-content .attachment-gallery.attachment-gallery--4 > action-text-attachment,
.trix-content .attachment-gallery.attachment-gallery--4 > .attachment {
  flex-basis: 50%;
  max-width: 50%;
}

.trix-content action-text-attachment .attachment {
  padding: 0 !important;
  max-width: 100% !important;
}

```
