### ISSUE TITLE
i18n support for scaffolds?

### ISSUE THREAD

**Issue by yshmarov** [rails/rails#51405]
I think it would be great if there was an option to generating scaffolds with i18n support by default.

So when I run `rails g scaffold post title body:text` it would also inject i18n defaults into the `en.yml` file and into controllers & views.

Something like

```yml
# config/locales/en.yml

en:
  posts:
    create:
      notice: Post was successfully created.
    update:
      notice: Post was successfully updated.
    destroy:
      notice: Post was successfully destroyed.
  activerecord:
    attributes:
      posts:
        title: Title
        body: Body
```

```diff
# app/controllers/posts_controller.rb
-        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
+         format.html { redirect_to post_url(@post), notice: t('.notice') }
```

```diff
# app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
-    <strong class="block font-medium mb-1">Body:</strong>
+    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.posts.body) %>:</strong>
```

What do you think?
