### ISSUE TITLE
Docker Compose file with unusual indentation

### ISSUE THREAD

**Issue by cirdes** [rails/rails#52159]
### Steps to reproduce
Using `rails new rails-72 --database=postgresql --devcontainer` we got a compose.yml with unusual indentation

I have checked [docker-compose docs examples](https://docs.docker.com/compose/networking/) and they are different. It's seems that are missing an space before every item on a list like volumes: or networks:

### Expected behavior
```yaml
name: "rails_72"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    networks:
      - default
    
    ports:
      - 45678:45678
    depends_on:
      - selenium
      - redis
      - postgres
```

### Actual behavior
```yaml
name: "rails_72"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    networks:
    - default
    
    ports:
    - 45678:45678
    depends_on:
    - selenium
    - redis
    - postgres
```

### System configuration
**Rails version**: 7.2.0.beta2

**Ruby version**: ruby 3.2.2
