### ISSUE TITLE
`bin/rails dbconsole` does not work inside a Docker container for sqlite3 apps

### ISSUE THREAD

**Issue by jeromedalbert** [rails/rails#52588]
### Steps to reproduce

These repro steps deploy with the Fly.io [CLI](https://fly.io/docs/flyctl/install/) (but the issue happens with any deployment setup that uses the default Dockerfile):

```bash
rails new myapp -d sqlite3
fly launch --yes --generate-name
fly ssh console # This connects to a running Docker container in production

root@redacted:/rails# bin/rails dbconsole
```

### Expected behavior

sqlite3 client should launch:

```
SQLite version 3.40.1 2022-12-28 14:03:47
Enter ".help" for usage hints.
sqlite>
```

### Actual behavior

sqlite3 does not launch:

```
Couldn't find database client: sqlite3. Check your $PATH and try again.
```

### System configuration
**Rails version**: 7.2.0

**Ruby version**: 3.3.2

### Comments

To confirm that this is a general issue, I was also able to reproduce on a Rails Edge sqlite3 app deployed with Kamal by running `kamal app exec -i bash` (which connects to a Docker container using SSH).

**Comment by mjsommer-dealerware** [comment]
I am having the exact same issue with MySQL. The command `bin/rails dbconsole` should bring up the MySQL cli, but instead, I get `Couldn't find database client: mysql, mysql5. Check your $PATH and try again`. Our Rails app is running in the `web` container, and the MySQL database is running in the `db` container. The command `rails cb:migrate` works, but not a straight `rails db`.

**Comment by mjsommer-dealerware** [comment]
Hi @jeromedalbert , I am fine here. This was for one of our Rails apps, that is deployed across multiple containers, where Rails is in one container, and MySQL is in another.

**Comment by aruprakshit** [comment]
I cannot connect to the db console without a password explicitly given. `Rails 7.2.1`

My configuration file for docker-compose.yml and database.yml files are:

```yaml
services:
  db:
    image: postgres:16.4-alpine
    container_name: turboapp_db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env.development.local
    ports:
      - 5449:5432
volumes:
  db_data:
```

and 

```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  port: <%= ENV.fetch('DATABASE_PORT') %>


development:
  <<: *default
  database: turboapp_development
```
I can boot rails server, rails console.. But when I do `bundle exec rails db`, it asks me password. Why is the password not being fetched from the `config/database.yml` file? I can even do `bundle exec rails db:create db:migrate` successfully.

```sh
bundle exec rails c
Loading development environment (Rails 7.2.1)
turboapp(dev)>
^C
turboapp(dev)>
^C
turboapp(dev)> exit
╭─arup at deadpool in ~/Code/Ruby/Projects/turboapp on main✘✘✘ 24-08-24 - 13:13:36
╰─⠠⠵ bundle exec rails db:create db:migrate
Database 'turboapp_development' already exists
Database 'turboapp_test' already exists
╭─arup at deadpool in ~/Code/Ruby/Projects/turboapp on main✘✘✘ 24-08-24 - 13:13:56
╰─⠠⠵ bundle exec rails dbconsole
Password for user postgres:
```
