### ISSUE TITLE
Only `id` is shown  when inspecting records in Rails console in production

### ISSUE THREAD

**Issue by Uaitt** [rails/rails#52728]
### Steps to reproduce
1. Create a new Rails app (with either Rails 7.2.1 or 8.0.0.alpha): `rails new test-app`
2. Modify `config/database.yml` so that the production database points to the development database (it's fine to keep sqlite for this demonstration):
   ```yml
   default: &default
   adapter: sqlite3
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   timeout: 5000

   development:
     <<: *default
     database: storage/development.sqlite3
   production:
     <<: *default
     database: storage/development.sqlite3
  
3. Create a dummy model: `bin/rails g model User name surname`

Now, if you enter the dev console with `bin/rails c` this is what you'll see:
```rb
test-app(dev)> User.create(name: "John", surname: "Doe")
test-app(dev)> User.first
=> #<User:0x0000000120d516c0 id: 1, name: "John", surname: "Doe", created_at: "2024-08-28 07:12:10.878368000 +0000", updated_at: "2024-08-28 07:12:10.878368000 +0000">
```

And if you enter the console in production with `bin/rails c -e production`, you'll see this:
```rb
test-ap(prod)> User.first
=> #<User:0x000000011f7f8760 id: 1>
```

As you see, while inspecting the user I only get back the `id`.

Note that if you follow those steps with Rails 7.1, the output of the development and production console match (they both show all the attributes).

### Expected behavior

I expect to see all the object attributes even on production. This behavior has changed from Rails 7.2.

### Actual behavior

From Rails 7.2 onwards, when inspecting a model instance in the production console you only get back the id and not the whole set of attributes.

### System configuration
**Rails version**:
7.2.1

**Ruby version**:
3.3.4
