### ISSUE TITLE
Schema dumps incorrectly for secondary databases

### ISSUE THREAD

**Issue by dhh** [rails/rails#52776]
Consider this database.yml:

```yaml
development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  cache:
    <<: *default
    database: storage/cache.sqlite3
    migrations_paths: db/cache_migrate
```

There are two databases. Now assume that we haven't yet run the migrations. So there are no db/*schema.rb files yet.

When we run `rails db:prepare`, migrations for both databases will be run correctly, but when the schema.rb for the secondary cache database is due to be dumped, it'll be dumped as the development database.

This is happening because https://github.com/rails/rails/blob/main/activerecord/lib/active_record/tasks/database_tasks.rb#L214 calls which then calls https://github.com/rails/rails/blob/main/activerecord/lib/active_record/tasks/database_tasks.rb#L214 to trigger the SchemaDumper. But the `migration_connection_pool` references `migration_class`, which is always ActiveRecord::Base, so you get the schema that belongs to that. Which is the primary.

We need the call to the dumper to use a connection pool that belongs to the cache db for this to work correctly.
