### ISSUE TITLE
postgresql hstore column not working with schema dump and rspec

### ISSUE THREAD

**Issue by JProgrammer** [rails/rails#52944]
### Steps to reproduce
I have created an api repo via generator that replicates the issue https://github.com/JProgrammer/pg-hstore

When running the single [test](https://github.com/JProgrammer/pg-hstore/blob/main/spec/models/post_spec.rb#L4)

### Expected behavior
The hstore column will be created with the correct values mapped from the hash

### Actual behavior
The following error will be raised

```
Failures:

  1) Post creates a new post
     Failure/Error: expect { Post.create(data: { title: "Hello, world!" }) }.to change { Post.count }.by(1)
     
     TypeError:
       can't cast Hash
     # ./spec/models/post_spec.rb:5:in `block (3 levels) in <top (required)>'
     # ./spec/models/post_spec.rb:5:in `block (2 levels) in <top (required)>'
```

It appears that via rails console this will work, and with rails serve but not with `rspec` I also found an issue with a rake task where this also happens but could not replicated in the simple scenario, it could be to do with the threading used in the other parts of that rake task.

### System configuration
**Rails version**: 8.0.1

**Ruby version**: 3.3.4
