### ISSUE TITLE
Dependabot configuration creates frequent PRs

### ISSUE THREAD

**Issue by viktorianer** [rails/rails#53148]
Dependabot configuration creates frequent PRs that include all types of updates, regardless of severity. 

### Steps to reproduce

1. Configure Rails 8 project with Dependabot with daily updates for Bundler and GitHub Actions.
2. Allow Dependabot to run for a few days, [observe the number of pull requests](https://github.com/viktorianer/rails8-devcontainer-enhancements/pulls?q=is%3Apr+is%3Aclosed).
3. Inspect the frequency of unnecessary version bumps, especially for minor or patch updates.

### Expected behavior

Dependabot should group version updates by severity and limit major updates to security patches. Additionally, non-critical updates should be handled less frequently (e.g., weekly) to reduce PR noise.

A related example and proposed solution can be seen in my project PR: [rails8-devcontainer-enhancements/pull/11](https://github.com/viktorianer/rails8-devcontainer-enhancements/pull/11).

Here's a sample script that could simulate excessive and unnecessary pull requests from Dependabot in a Rails project:

https://github.com/viktorianer/rails8-devcontainer-enhancements/blob/main/.github/dependabot.yml

I would love to submit a PR with those changes. 💯 

### Actual behavior

Dependabot creates daily pull requests for all types of version bumps, regardless of importance, resulting in excessive pull requests and noise in the repository.

### System configuration

**Rails version**: Rails 8.0.0.beta1

**Ruby version**: ruby 3.3.4 (2024-07-09 revision be1089c8ec) [arm64-darwin23]

**Comment by viktorianer** [comment]
Hi @rafaelfranca,

As discussed during Rails World 2024, I’ve implemented the changes we talked about regarding Dependabot updates and PR management in my project. I’d love for you to take a look at the PR here: [rails8-devcontainer-enhancements/pull/11](https://github.com/viktorianer/rails8-devcontainer-enhancements/pull/11). 

Looking forward to your feedback!

**Comment by markhallen** [comment]
Another tactic to consider could be to auto-merge minor updates if the tests pass.

`.github/workflows/dependabot-auto-merge.yml`

```yml
name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
