### ISSUE TITLE
Signed_id in a Multi-tenanted scope (Horizontal Sharding)

### ISSUE THREAD

**Issue by uxxman** [rails/rails#53304]
### Steps to reproduce
When inside a horizontally sharded multi-tenant application, signed_id of a record inside :shard1 can be used to fetch a record inside :shard2 (when they have the same ID). 

```yml
development:
  primary:
    database: my_primary_database
    adapter: mysql2
  primary_shard_one:
    database: my_primary_shard_one
    adapter: mysql2
    migrations_paths: db/migrate_shards
  primary_shard_two:
    database: my_primary_shard_two
    adapter: mysql2
    migrations_paths: db/migrate_shards
```

```ruby
class ShardRecord < ApplicationRecord
  self.abstract_class = true

  connects_to shards: {
    shard_one: { writing: :primary_shard_one, reading: :primary_shard_one },
    shard_two: { writing: :primary_shard_two, reading: :primary_shard_two }
  }
end

signed_id = nil

ActiveRecord::Base.connected_to(role: :writing, shard: :shard_one) do
  signed_id = User.first.signed_id expires_in: 15.minutes, purpose: :auth
end

ActiveRecord::Base.connected_to(role: :writing, shard: :shard_two) do
  User.find_signed signed_id, purpose: :auth # => User found 
end
```

### Expected behavior
This should not happen otherwise a user from subdomain1 can use his/her signed_ids/tokens on other domains as well and impersonate as other users.

### Possible Solution
Since rails 8 introduced a ***sharded?*** method here(https://github.com/rails/rails/pull/51009) we can use it to enhance the purpose and also include current_shard value. So, a signed_id generated within a shard can only be used within that shard scope only.

```ruby
# activerecord/lib/active_record/signed_id
def combine_signed_id_purposes(purpose)
  full_purpose = [ base_class.name.underscore, purpose.to_s ]
  full_purpose << current_shard if sharded?
  full_purpose.compact_blank.join("/")
end
```

### System configuration
**Rails version**: main

**Ruby version**: 3.3.4
