### ISSUE TITLE
Configure real solid cable backend for new Rails 8 app when database type specified & compatible

### ISSUE THREAD

**Issue by pas256** [rails/rails#53630]
The default in a new Rails 8 app is using `async` for cable's implementation. As someone who has built a bunch with Hotwire, I just burned many hours trying to figure out why my Hotwire wasn't working. Naturally, I stripped down the code, opened a rails console and was watching the cable websocket traffic in the browser, confused as to why nothing was coming through.

It turns out, someone knew this might be an issue. In `cable.yml`, there is a big comment:

```
# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async
```

The zen of Rails is developer happiness and productivity. This choice to use `async` even when I specified I want to use `postgresql` doesn't feel like it is in my best interest. I am guessing there may be some other technical challenge I'm not familiar with, so apologies if this is more involved than I realize.

I would think that if someone runs:

    rails new myapp --database=postgresql

... that the solid family (cache, queue, cable) would be configured to use PostgreSQL, just like it will in production. Why use `async` which we know doesn't work in the console? Even more frustrating is there are no runtime warnings to let you know about this limitation, so it fails silently until you happen to dig deep an open `cable.yml` to see the comment.

### Steps to reproduce

    rails new myapp --database=postgresql

Create a view that contains:

```
<%= turbo_stream_from "test" %>
<div id="myelement">
  Loading...
</div>
```

Open a rails console with `rails c` and run:

```ruby
Turbo::StreamsChannel.broadcast_update_to(
  "test",
  target: "myelement",
  html: "<div>A new message from the console!</div>"
)
```

### Expected behavior

The `cable` websocket receives a message which changes the contents of `myelement`.

Or, I am warned that the broadcast is limited to only the currently running process. 

### Actual behavior

Due to cable using `async` as the backend, the console reports a broadcast happening:

```
[ActionCable] Broadcasting to test: "<turbo-stream action=\"update\" target=\"myelement\"><template><div>A new message from the console!</div></template></turbo-stream>"
```

However, the browser does not receive this message because they are two different processes and `async` only works within the same process.

### System configuration

**Rails version**: 8.0.0

**Ruby version**: 3.3.5

**Comment by CoryFoy** [comment]
Thanks for posting this. Just in case anyone is coming across this - the main option to run it in development if you don't want to spin up multiple databases is to follow the [Single Database Configuration](https://github.com/rails/solid_cable?tab=readme-ov-file#single-database-configuration) steps:

1. `rails g migration singlify_solid_cable` (or whatever you want to call it)
2. Copy the contents of `db/cable_schema.rb` into the migration. Mine ended up looking like this:
```
class SinglifySolidCable < ActiveRecord::Migration[8.0]
  def change
    create_table "solid_cable_messages", force: :cascade do |t|
      t.binary "channel", limit: 1024, null: false
      t.binary "payload", limit: 536870912, null: false
      t.datetime "created_at", null: false
      t.integer "channel_hash", limit: 8, null: false
      t.index ["channel"], name: "index_solid_cable_messages_on_channel"
      t.index ["channel_hash"], name: "index_solid_cable_messages_on_channel_hash"
      t.index ["created_at"], name: "index_solid_cable_messages_on_created_at"
    end
  end
end
```
3. Delete `db/cable_schema.rb`
4. Modify `config/cable.yml` to look like this:
```
development:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day

test:
  adapter: test

production:
  adapter: solid_cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
```
5. Run `rails db/migrate`
6. Restart any processes you have open

I had literally been banging my head for hours trying to figure out why the turbo stream stuff wasn't working and I was working in the context of background jobs which are pushing new data, so async wasn't going to cut it for me. I think I understand why they don't do it by default - they really want you to have this as a separate database, and people would just go with the default of having it all in one if they didn't split it out. But it was incredibly frustrating and maybe some sort of warning or something else could be in the console when using `async`

**Comment by pas256** [comment]
Thanks @rails-bot, yes, this is still an issue with Rails 8.0.2.

One other workaround if you want a development setup that is closer to production, is to modify your `config/database.yml` file:

```
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>


development:
  primary: &primary_development
    <<: *default
    database: myapp_development
  cable:
    <<: *primary_development
    database: myapp_development_cable
    migrations_paths: db/cable_migrate
```

... and then run `rails db:prepare` like normal.
