### ISSUE TITLE
db:setup not happy about writer/reader database layout

### ISSUE THREAD

**Issue by wdiechmann** [rails/rails#53704]
### Mitigation
Uncomment line marked !-! in `config/database.yml` and comment/remove writer/reader definitions

### Steps to reproduce
`rails new` then add

```
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  # !-! database: storage/development.sqlite3
  writer:
    <<: *default
    database: storage/development.sqlite3
  reader:
    <<: *default
    database: storage/development.sqlite3
  cache:
    <<: *default
    database: storage/development.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/development.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/development.sqlite3
    migrations_paths: db/cable_migrate
...

```
 
### Expected behavior

```
rails db:setup
Created database 'storage/development.sqlite3'
Created database 'storage/test.sqlite3'
You have 1 pending migration:
  20241122074649 DeviseCreateUsers
Run `bin/rails db:migrate` to update your database then try again.
```

### Actual behavior

```
rails db:setup
no implicit conversion of nil into String
Couldn't create '' database. Please check your configuration.
bin/rails aborted!
TypeError: no implicit conversion of nil into String (TypeError)

        raise DatabaseAlreadyExists if File.exist?(db_config.database)
                                                   ^^^^^^^^^^^^^^^^^^

Tasks: TOP => db:setup => db:create
(See full trace by running task with --trace)
```

### System configuration
**Rails version**: 8.1.0.alpha

**Ruby version**: 3.3.3
