### ISSUE TITLE
SQLite database tasks performed after `drop` on a single DB don't persist

### ISSUE THREAD

**Issue by rosa** [rails/rails#53832]
This was an issue raised by @joemasilotti, as he was wondering whether `db:reset` didn't work as expected. 

### Steps to reproduce
This can be easily reproduced with a new app where the `database.yml` configuration includes a single environment, for example, `development`, like this: 
```yml
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3
```

I've created a test app [here](https://github.com/rosa/phantom-db-sqlite-repro?tab=readme-ov-file#to-reproduce) to illustrate the  problem. Just cloning that repo and running: 
```
bundle install

bin/rails db:drop db:create db:schema:load --trace
bin/rails runner "puts Dog.count"
```
shows the problem, as that raises a

```
SQLite3::SQLException: no such table: dogs: (ActiveRecord::StatementInvalid)
SELECT COUNT(*) FROM "dogs" /*application='PhantomDbSqliteRepro'*/
```
even though the DB is correctly created and the schema correctly loaded. The problem is that those tasks are run on the same established connection in use before removing the file via [the `drop` task](https://github.com/rails/rails/blob/91d456366638ac6c3f6dec38670c8ada5e7c69b1/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb#L23-L26). 

The connection is established in [`check_current_protected_environment`](https://github.com/rails/rails/blob/91d456366638ac6c3f6dec38670c8ada5e7c69b1/activerecord/lib/active_record/tasks/database_tasks.rb#L635-L649), which is [run before the `drop` task](https://github.com/rails/rails/blob/91d456366638ac6c3f6dec38670c8ada5e7c69b1/activerecord/lib/active_record/railties/databases.rake#L64). Then, this connection is kept and reused every time we call `establish_connection`: https://github.com/rails/rails/blob/91d456366638ac6c3f6dec38670c8ada5e7c69b1/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb#L126-L134  

`clobber` is `false`, the owner is always `ActiveRecord::Base`, and there's a single DB config, so `existing_pool_config.db_config` always matches the `db_config` we're passing.

This can't be reproduced if you have both `development` and `test` environments configured in `database.yml` because we switch between the two DB configs when dropping the two DBs, so before creating the `development` DB, we run [this once for the test DB](https://github.com/rails/rails/blob/91d456366638ac6c3f6dec38670c8ada5e7c69b1/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb#L136), disconnecting from the connection used when dropping the `development` DB.

### System configuration
**Rails version**: Edge, but I've verified it happens with Rails >= 7.2 as well. 

**Ruby version**: 3.3.6

### A possible fix

This fixes the problem: 
```diff
diff --git a/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb b/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb
index ce073ae145..67a3f64b4e 100644
--- a/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb
+++ b/activerecord/lib/active_record/tasks/sqlite_database_tasks.rb
@@ -20,6 +20,8 @@ def create
       end

       def drop
+        connection.disconnect!
+
         db_path = db_config.database
         file = File.absolute_path?(db_path) ? db_path : File.join(root, db_path)
         FileUtils.rm(file)
```
as it ensures we always disconnect before removing the files and leaving the existing connection in a bad state, but I haven't created a PR as I wasn't sure if that's an acceptable fix. I think this might be related to https://github.com/rails/rails/pull/48560, although in this case, it only affects SQLite. 

Let me know if I can help in any way!

**Comment by rafaelfranca** [comment]
I think that is a good fix. Can you open a PR?

**Comment by rosa** [comment]
Thanks a lot @rafaelfranca! Here it is: https://github.com/rails/rails/pull/53893

**Comment by jaspervanbrian** [comment]
@rosa Is this issue related to what I'm working on? Because I'm facing an issue on configuring `solid_cache` with sqlite3. I'm just trying it out on my first time in development environment and it seems it does not create migrations. I am not sure what is happening.

```
# config/database.yml
...
sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: my_app_development
  cache:
    <<: *sqlite
    database: solid/my_app_development_cache.sqlite3
    migrations_paths: db/cache_migrate
...
```

```
# config/environments/development.rb
...
  # Change to :null_store to avoid any caching.
  config.cache_store = :solid_cache_store
...
```

```
# config/cache.yml
default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default
  database: cache

test:
  <<: *default

production:
  database: cache
  <<: *default
```

After setting up the sqlite3 for solid cache:
```
$ rails db:drop
$ rails db:create
$ rails db:migrate
# $ rails db:migrate:reset
```

These errors pop up:
```
Could not find table 'solid_cache_entries' 
SQLite3::SQLException: no such table: solid_cache_entries: (ActiveRecord::StatementInvalid)
```

**Comment by rosa** [comment]
@jaspervanbrian I'm not sure. What does your `database.yml` config looks like in full?

**Comment by jaspervanbrian** [comment]
@rosa this is my full `database.yml`:

```yml
# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: my_app_development
  cache:
    <<: *sqlite
    database: solid/my_app_development_cache.sqlite3
    migrations_paths: db/cache_migrate

  # The specified database role being used to connect to PostgreSQL.
  # To create additional roles in PostgreSQL see `$ createuser --help`.
  # When left blank, PostgreSQL will use the default role. This is
  # the same name as the operating system user running Rails.
  #username: my_app

  # The password associated with the PostgreSQL role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: my_app_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: my_app_production
    username: my_app
    password: <%= ENV["my_app_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_app_production_cable
    migrations_paths: db/cable_migrate
```

I followed up my issue here on our discussion: https://github.com/rails/solid_queue/issues/419
I've temporarily fixed this issue by creating my own migration here on `db/cache_migrate` as specified on the cache `migration_paths`:

```ruby
class CreateSolidCacheEntries < ActiveRecord::Migration[8.0]
  def change
    create_table :solid_cache_entries do |t|
      t.binary :key, limit: 1024, null: false
      t.binary :value, limit: 536870912, null: false
      t.datetime :created_at, null: false
      t.integer :key_hash, limit: 8, null: false
      t.integer :byte_size, limit: 4, null: false

      t.index :byte_size
      t.index [ :key_hash, :byte_size ]
      t.index :key_hash, unique: true
    end
  end
end
```

so now, `db/cache_schema.rb` looks like this:

```ruby
ActiveRecord::Schema[8.0].define(version: 2024_12_28_075546) do
  create_table "solid_cache_entries", force: :cascade do |t|
    t.binary "key", limit: 1024, null: false
    t.binary "value", limit: 536870912, null: false
    t.datetime "created_at", null: false
    t.integer "key_hash", limit: 8, null: false
    t.integer "byte_size", limit: 4, null: false
    t.index ["byte_size"], name: "index_solid_cache_entries_on_byte_size"
    t.index ["key_hash", "byte_size"], name: "index_solid_cache_entries_on_key_hash_and_byte_size"
    t.index ["key_hash"], name: "index_solid_cache_entries_on_key_hash", unique: true
  end
end
```

instead of 

```ruby
ActiveRecord::Schema[8.0].define(version: 2024_12_28_075546) do
end
```

**Comment by rosa** [comment]
@jaspervanbrian that doesn't look like this issue at all, no. This issue only happens when you have `development` as the only environment configured, but you have others. Your issue seems to be a different Rails bug related to running `db:migrate` with an empty secondary DB, so your `db/cache_schema.rb` file got wiped out.

**Comment by jaspervanbrian** [comment]
> @jaspervanbrian that doesn't look like this issue at all, no. This issue only happens when you have `development` as the only environment configured, but you have others. Your issue seems to be a different Rails bug related to running `db:migrate` with an empty secondary DB, so your `db/cache_schema.rb` file got wiped out.

@rosa yes I agree, that's why at first I was hesitant and not sure if this issue is related to what I'm working on. Looks like #52829 and https://github.com/rails/solid_cache/issues/228 is more relevant to my issue here...

**Comment by mackuba** [comment]
I think I'm hitting the same issue… my `config/database.yml` looks like this:

```yml
development:
  adapter: sqlite3
  database: db/blueskydev.sqlite3
  timeout: 5000

production:
  adapter: sqlite3
  database: db/bluesky.sqlite3
  timeout: 20000
```

With the db file deleted, `db:migrate` will create and initialize a new one (from schema), but `db:migrate:reset` will not (it prints the migrations, but file is missing in the end).
