### ISSUE TITLE
ActiveStorage creates conflicting checksums when using S3-compatible services on Blob.create_and_upload!

### ISSUE THREAD

**Issue by richjdsmith** [rails/rails#54374]
## Description
When using ActiveStorage with S3-compatible services (specifically Cloudflare R2), `ActiveStorage::Blob.create_and_upload!` fails because it sends two different checksums to the storage service. While Amazon S3 accepts multiple checksums, other S3-compatible services may not support this behavior.

## Environment
- Rails version: 8.0.1
- Ruby version: 3.3.6
- AWS SDK S3 gem version: 1.178.0
- Storage service: Cloudflare R2 (S3-compatible)

## Steps to Reproduce

1. Configure ActiveStorage to use an S3-compatible service:
```yaml
# config/storage.yml
cloudflare:
  service: S3
  endpoint: https://account_id.r2.cloudflarestorage.com
  access_key_id: access_key
  secret_access_key: secret_key
  region: auto
  bucket: bucket_name
```

2. Attempt to upload a file using `create_and_upload!`:
```ruby
blob = ActiveStorage::Blob.create_and_upload!(
  io: params[:file],
  filename: params[:file].original_filename,
  content_type: params[:file].content_type
)
```

## Current Behavior
The upload fails with:
```
Aws::S3::Errors::InvalidRequest You can only specify one checksum at a time.
```

Debug logs show that two checksums are being sent:
```ruby
put_object(
  body: #<ActionDispatch::Http::UploadedFile...>,
  content_md5: "ggvRot1GXgDw4lbwRpD6eQ==",    # First checksum from ActiveStorage
  content_type: "image/jpeg",
  content_disposition: nil,
  metadata: {},
  bucket: "bucket_name",
  key: "key123",
  checksum_algorithm: "CRC32"                  # Second checksum from AWS SDK
)
```

## Expected Behavior
ActiveStorage should either:
1. Allow configuration of checksum behavior for S3-compatible services
2. Only send one type of checksum
3. Detect S3-compatible services and adjust behavior accordingly

## Workaround
The issue can be worked around by manually creating the blob with the checksum in advance:

```ruby
service = ActiveStorage::Blob.service
key = SecureRandom.base58(24)
 # Calculate checksum manually, in advance
checksum = Digest::MD5.file(params[:image].tempfile).base64digest

blob = ActiveStorage::Blob.create!(
  key: key,
  filename: file.original_filename,
  byte_size: file.size,
  checksum: checksum,  # Prevent ActiveStorage from adding MD5
  content_type: file.content_type,
  service_name: service.name
)

service.upload(
  key, 
  file,
  content_type: file.content_type
)
```

This allows the AWS SDK to handle checksums with just CRC32, which works with S3-compatible services.

## Additional Notes
- Regular file uploads through forms work fine (they use a different code path)
- Direct uploads through ActiveStorage's built-in controller also work
- The issue specifically occurs with `create_and_upload!`
- This affects any S3-compatible service that doesn't support multiple checksums

## Suggested Fix
Consider adding a configuration option in ActiveStorage's S3 service to specify checksum behavior:

```yaml
cloudflare:
  service: S3
  # ...other configs...
  checksum_mode: single  # or 'multiple' for regular S3
```

Or detect S3-compatible services based on the endpoint and adjust behavior automatically.

**Comment by richjdsmith** [comment]
Looks like this may be related to https://github.com/aws/aws-sdk-ruby/issues/3174

**Comment by richjdsmith** [comment]
Closing this for now. It appears to be an Amazon AWS decision that is affecting multiple S3 compatible cloud storage options. 

Not really a Rails issue, but certainly bothersome. 

Quick fix for anyone that finds this comment thread is to pin an older version of the AWS S3 gem and its dependent. 

```
# S3 Compatible storage service interaction
gem "aws-sdk-s3", "1.170", require: false
gem "aws-sdk-core", "3.211"
```

**Comment by jayelkaake** [comment]
I don't think this should be closed yet because it looks like AWS's is choosing to keep the checksum requirement as default.

## Best short term solution
```ruby
# in config/initializers/aws.rb
Aws.config.update(request_checksum_calculation: 'when_required') if defined?(Aws)
```

## Best long term solution?
@richjdsmith can someone (maybe me if you're OK with it) put up a PR to include the checksums like you suggested in the ActiveStorage core?

**Comment by woodhull** [comment]
Should this actually be closed? It sounds like additional configuration options in storage.yml is actually what's required. 

See "Compatibility": https://developers.cloudflare.com/r2/examples/aws/aws-sdk-ruby/

I think @richjdsmith was on the right track with the suggested extension of storage.yml config.

**Comment by jspooner** [comment]
The [temporary solution](https://github.com/rails/rails/issues/54374#issuecomment-2617377315) from  @richjdsmith  worked for me.  TY!

**Comment by paulhenri-l** [comment]
Activestorage already forwards options to the underlying service (s3 in our case)

So all that is needed is to add cloudflare's recommended options

Which gives us:
```yaml
# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: "" # e.g. 'us-east-1'
  bucket: your_own_bucket-<%= Rails.env %>
  http_open_timeout: 0
  http_read_timeout: 0
  retry_limit: 0
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"
```

Then it works 😎

**Comment by acpopper** [comment]
@paulhenri-l 's answer worked like a charm. Thanks!

**Comment by erozas** [comment]
@paulhenri-l's answer worked for me as well with the `aws-sdk-s3` version 1.185. However, if anybody is using this with Cloudflare I had an issue with the timeout and `region` settings. What worked for me was:

```yaml
cloudflare:
  service: S3
  endpoint: https://<%= Rails.application.credentials.dig(:cloudflare, :account_id) %>.r2.cloudflarestorage.com
  access_key_id: <%= Rails.application.credentials.dig(:cloudflare, :r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:cloudflare, :r2, :secret_access_key) %>
  bucket: <%= Rails.application.credentials.dig(:cloudflare, :r2, :bucket) %>
  region: auto
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"
```
