### ISSUE TITLE
db:schema:load rake task depends on db:test:purge which has hardcoded 'test' env_name

### ISSUE THREAD

**Issue by thomasnemer** [rails/rails#54847]
### Steps to reproduce
* Create a new rails application, replace `sqlite3` gem with `pg` in Gemfile.
* edit `config/database.yml` so that `test` environment database points to localhost:1234 and production database points to localhost:5432 : 
```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
test:
  <<: *default
  url: postgres://user:password@localhost:1234/test_db
production:
  <<: *default
  url: postgres://user:password@localhost:5432/prod_db
```
* run a postgresql container exposing port 5432 but do not run a container exposing port 1234 (you want 'production' database only, no 'test' database) : `docker run -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -p 5432:5432 postgres`
* init production database and run `db:schema:load` rake task

```shell
export DISABLE_DATABASE_ENVIRONMENT_CHECK=1
export RAILS_ENV=production
bin/rails db:migrate
bin/rails db:schema:load
```

### Expected behavior

`db:schema:load` rake task should run successfully against the 'production' database

### Actual behavior
`db:schema:load` rake task fails because it tries to connect to 'test' database and tells to create it first, or fails trying to connect to it if you created it before.

### System configuration

**Rails version**: 8 (also 7)

**Ruby version**: any

### Details
The task fails because it depends on another one : `db:test:purge` which has an hardcoded `test` environment name. This dependency was introduced in [this commit](https://github.com/rails/rails/commit/adb64db43dba5cad1007ce57e25df67f8b3e91f8#diff-4a42b5efdab725af0936f94b4a84dcf6a8be8738e28ed265e0a3e74f275f5048R491).
