### ISSUE TITLE
`db:migrate:reset` is not recreating non-primary databases

### ISSUE THREAD

**Issue by javierav** [rails/rails#55045]
### Steps to reproduce
It's currently happening to me with the solid_cable database, but that's because it's the only one I've set up in development other than the main one.

```yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  cable:
    <<: *default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate
```

1. Create a migration and run it with `db:migrate`.
2. Change that migration and run `db:migrate:reset`.

### Expected behavior
Primary database must be recreated by reapplying existing migrations without using the schema. The solid_cable database, since it has no migrations in its directory, must be recreated using the schema.

### Actual behavior
Primary database is working correctly, but the solid_cable database is created empty and its schema is updated to:

```ruby
# db/cable_squema.rb
ActiveRecord::Schema[8.1].define(version: 0) do
end
```

### System configuration
**Rails version**: 8.1.0.alpha 730367e
**Ruby version**: ruby 3.4.2 (2025-02-15 revision d2930f8e7a) +PRISM [arm64-darwin24]

Related issues: rails/solid_queue#540 rails/rails#52829
