### ISSUE TITLE
Handle links and other safe content inside translations

### ISSUE THREAD

**Issue by runephilosof-abtion** [rails/rails#55245]
Currently, if I want to put a link into a translation, I have to do
```erb
<%= t(".text", insert: link_to(t(".insert"), root_path)).html_safe %>
```
or
```erb
<%= t(".text_html", insert: link_to(t(".insert"), root_path)) %>
```

However, the `text_html` translation should not have to know whether the `insert` contains html or not.
~Also, the `insert` translation cannot have unescaped html content, because it is used as content inside another `_html` translation.~

The rails i18n guide does not mention how to do this nicely.

The best would be if rails-i18n could handle it automatically by being aware of SafeBuffer.

```yml
text: some <> text with an %{insert}
text_html: some &lt;&gt; text with an %{insert}
insert: a link, properly escaping <>
```

```erb
<%= t(".text", insert: link_to(t(".insert"), root_path)) %>
```

Rails-i18n should handle safe joining the above example.

`link_to` returns a `html_safe` string, so this should output 
```html
some &lt;&gt; text with an <a href="/">a link, properly escaping &lt;&gt;</a>
```
